### PR TITLE
sensor lennartz MKIII lite set up

### PR DESCRIPTION
**Pull request by salichon**
NB: PAZ to be confirmed
and/or checked for the MKIIlite

### CODE REVIEW

**Comment by salichon** [comment]
@ozym I don t understand the conflict  since the resp/auto.go file was comitted with the changes.

**Comment by salichon** [comment]
@nbalfour wrt the PAZ for the LE-3Dlite isntruments 
Shall we correct the Poles and Zeroes of all  the L3Dlite with regards to that updated document ?  
 http://www.lennartz-electronic.de/index.php/downloads-en/category/1-manuals?download=5:seismometers-manual

**Comment by ozym** [comment]
The problem is related to gofmt with the "-v" flag. I've fixed the conflict but need to see why it was there in the first place.

**Comment by salichon** [comment]
Sweet thanks

**Comment by nbalfour** [comment]
@ozym yes, i think we should correct the responses for the other sensors.

**Comment by ozym** [comment]
@salichon I suspect it may be related to your version of the go compiler when building the auto.go file.

**Comment by salichon** [comment]
okay Merci Mark , 
which version is recommended ? 
I  have a 1.7 linux/amd64 on the laptop

**Comment by salichon** [comment]
@nbalfour @ozym @quiffman 
Good day ! 
 i m going to merge that branch 
though, double checking on a long WE tuesday -> "Is it safe?"
In addition:  
Which go version + config Should I have to prevent from formating errors (see mark s commits) ? 
Thanks,
Cheers
Jerome

**Comment by ozym** [comment]
@salichon in the `.travis.yml` there is an entry saying what version of go will be used to do the testing and building.

**Comment by salichon** [comment]
FYI I installed go1.9.2.linux-amd64.tar.gz

As i realized this might be relevant to run go from a docker container perhaps. ..

**Pull request merged**
