### PR TITLE
CRLZ closed 2014 - Connections Closed then

### PR DESCRIPTION
**Pull request by salichon**
metadata corrections
Connections are closed now

### CODE REVIEW

**Review by mnaguit — COMMENTED** [review]
Looks good @salichon 

Just a quick query: `install/streams.csv` has LC 10 closed in 1997. Does that look weird?

**Comment by salichon** [comment]
yo @mnaguit 
weird of course - but the sensor on 10  lasts longer  with :
`install/sensors.csv:Guralp Systems Ltd.,CMG-3ESP-Z,T3738,CRLZ,10,0,,0,0,0,0,0,0,1999-06-14T02:51:00Z,2014-01-09T00:00:00Z `

I suspect we may have to clarify and rework the CRLZ metadata by inspection of the data 
I choose the simple most encompassing date so far (to me)

**Comment by mnaguit** [comment]
Hahaha. We can start with this simplest step.
Then we can divelater into the PITA step.  😄

**Review by mnaguit — APPROVED** [review]
😄

**Pull request merged**
