### PR TITLE
WHSZ new station

### PR DESCRIPTION
**Pull request by mnaguit**
open LC 10 & 20 for short period and strong motion

### CODE REVIEW

**Comment by salichon** [comment]
I  reckon this should be SI as 
`SI | NZ | South Island regional seismic network`

**Comment by ozym** [comment]
I think the idea is to make this a national network scope site, just that we don't have any broadbands to install at the moment.

**Comment by salichon** [comment]
Okay  thanks:)
 so it will rather a NZ then

**Comment by ozym** [comment]
It wasn't kicked off as a national network (i.e 3 letter code ending in Z) so I'd suggest SP (southern alps) rather than SI, we can change it later.

**Comment by salichon** [comment]
FYI @JonoHanson Any thoughts about this ?

**Comment by mnaguit** [comment]
Will wait for @JonoHanson response on this, for the network code, prior to changing the PR.

**Comment by JonoHanson** [comment]
I think the Delta meeting is the appropriate place to confirm this. So if you have a clear proposed choice, feel free to move forward.

**Comment by mnaguit** [comment]
Hi @samgeonet @salichon @ozym 
Per Delta meeting today, the network code is now updated to SI.
Kindly review.

**Comment by mnaguit** [comment]
Hi @salichon @samgeonet @KOgeonet @ozym 
Gentle reminder to review this PR. Thanks!

**Comment by salichon** [comment]
@mnaguit still it needs to be updated with the porper subnetwork. (not `SM`)  :)

**Comment by mnaguit** [comment]
Which file needs to be updated for that? @salichon 
> @mnaguit still it needs to be updated with the porper subnetwork. (not `SM`) :)

**Comment by mnaguit** [comment]
Hi @ozym . Are you happy with this PR? Thanks.

**Pull request merged**
