### PR TITLE
updated visibility checks

### PR DESCRIPTION
**Pull request by ozym**
Turns out the visibility file wasn't being verified in testing.

Have added checks and updated the file to pass.

### CODE REVIEW

**Comment by meganmadley** [comment]
@ozym, slightly confused about the use of the double quotes (" "), for RGCR it was removed but then added for TGOH?

**Comment by elidana** [comment]
Thanks @ozym !!

No need of double quotes. This is some inherited free text file from the old Delta Oracle DB. We will need to work on this at some point and remove the free text.
But double quotes surely unnecessary

**Review by elidana — APPROVED** [review]

**Comment by meganmadley** [comment]
Do we want to remove the double quotes for TGOH before this is merged? @elidana @ozym

**Comment by meganmadley** [comment]
Had a look @elidana and there are actually heaps with double quotes, probably could just get this merged now and look at removing when we decide to do a bigger update on this file

**Review by meganmadley — APPROVED** [review]

**Comment by elidana** [comment]
yes, sounds good. We can definitively remove double quotes in a separate one. The rework is probably a bit more work than just removing double quotes.
@ozym , I can merge this if you're ok (or feel free to merge it)

**Comment by ozym** [comment]
The double quotes are needed when there's a comma in the message.

**Comment by ozym** [comment]
@elidana merge away.

**Comment by elidana** [comment]
> The double quotes are needed when there's a comma in the message.

:facepalm: oh dear, of course! Thanks for clarifying that

**Pull request merged**
