### PR TITLE
NZE changing the start time of recent deploy

### PR DESCRIPTION
**Pull request by meganmadley**
In an effort to try and get around the descending data, I have changed the start date for NZE to be 2021-12-14 instead of 2021-12-13. I have not changed the closing time of the previous day (2021-12-12) to try and avoid the annoying files on the 13th Dec. Let me know what you think! We won't merge this unless you think it's a good idea @ozym.

### CODE REVIEW

**Comment by ozym** [comment]
Here's the raw transition data, Looks to me like the previous deployment may need to stop a little earler (***) but the start of the next would be fine (+++).

```
NZE 2021-12-11T22:15:00Z 5778448
NZE 2021-12-11T22:30:00Z 5778517
NZE 2021-12-11T22:45:00Z 5778580
NZE 2021-12-11T23:00:00Z 5778642
NZE 2021-12-12T19:15:00Z 5990020 ***
NZE 2021-12-12T19:30:00Z 6010020
NZE 2021-12-12T19:45:00Z 6000020
NZE 2021-12-12T20:00:00Z 6020020
NZE 2021-12-13T20:15:00Z 5776667
NZE 2021-12-13T20:30:00Z 5776658
NZE 2021-12-13T20:45:00Z 5776656
NZE 2021-12-13T21:00:00Z 5776660
NZE 2021-12-13T21:15:00Z 5776669
NZE 2021-12-13T21:30:00Z 5776690
NZE 2021-12-13T21:45:00Z 5776714
NZE 2021-12-13T22:00:00Z 5776745
NZE 2021-12-13T22:15:00Z 5776784
NZE 2021-12-13T22:30:00Z 5776827
NZE 2021-12-13T22:45:00Z 5776876
NZE 2021-12-13T23:00:00Z 5776929
NZE 2021-12-13T23:15:00Z 5776982
NZE 2021-12-13T23:30:00Z 5777038
NZE 2021-12-13T23:45:00Z 5777092
NZE 2021-12-14T00:00:00Z 5777150 +++
NZE 2021-12-14T00:15:00Z 5777206
NZE 2021-12-14T00:30:00Z 5777264
NZE 2021-12-14T00:45:00Z 5777319
NZE 2021-12-14T01:00:00Z 5777369
NZE 2021-12-14T01:15:00Z 5777415
```

**Comment by meganmadley** [comment]
@ozym would it be easier to have the end date before the previous day? That would remove the large gap so it would be `2021-12-11T23:00:00Z` instead of `2021-12-12T19:15:00Z`?

**Comment by salichon** [comment]
kia ora
for the sake of clarity to me ,
What is required here is the start/end form the _streams and recorders_  that will be accounted downstream,  right / 
We don t need to change firmware, sites but for consistencies when required. 
@meganmadley

**Comment by meganmadley** [comment]
thanks @salichon, am just aiming for it being consistant

**Comment by ozym** [comment]
The comment from @salichon points towards the difference between what was where (equipment) vs what was being recorded (streams). This means to me the bits about firmware and installation should match the ship logs as appropriate, whereas the streams should match the data being recorded (streams.csv).

**Comment by ozym** [comment]
Maybe we just need to update the streams.csv file and leave the rest as is (previous work should be fine).

**Comment by meganmadley** [comment]
Have removed changes to install/firmware and network/sites by changing them back to what they were

**Comment by ozym** [comment]
@salichon could you have a look.

**Review by salichon — APPROVED** [review]
All go to me 
Say we state  for Day  of deploy there is out from the DB.  to mitigate settling dat sets.
All good to me

We can even round the date 2021-12-11T23:59:59Z to 2021-12-12T00:00:00Z. if more convenient  this should work.

**Comment by salichon** [comment]
@meganmadley very sorry ... trying to find my ways in having 
  the site *40* is closed at **2021-12-12T21:00:00Z**  as for the streams 
 but the  related recorders closes at **2021-12-12T23:59:59Z**  so are doing the enviromment constituents and gauges.

**Pull request merged**
