### PR TITLE
Staylorofford patch 1

### PR DESCRIPTION
**Pull request by staylorofford**
TEMO webcam swap.

I have used timing conventions of the last session ending 1 second after the last data, and the new session starting 1 second before the new data. This is because there are images between these two times that are not taken from the mount + view and are not in the correct format, otherwise both times would be 1 second before the new data.

### CODE REVIEW

**Review by rumachan — DISMISSED** [review]
Hadn't realised Cam had to change the camera. Night images are beautiful!
The changes  look good, though I haven't checked the date/time of the transition. I'm assuming you've got that correct. What you've got makes sense.

EDIT
Have now checked date/time and they are good.

**Comment by staylorofford** [comment]
Thanks Steve. If you could can you please check the timing? You may find or feel that what I have chosen is not appropriate.

**Comment by rumachan** [comment]
Sorry, was being lazy, will do.

**Comment by rumachan** [comment]
Sam, have revised review. I think what you chose to do to avoid non-normal images is an obvious way to deal with the situation.You still pass!

**Comment by staylorofford** [comment]
The travis build failed so I have shuffled the lines around. I suspect it wants serial numbers to be ascending at a given site when the camera model is the same. This is interesting as it puts the newer installation ahead of the older one in the file which is unusual. We will see if it resolves now.

**Comment by staylorofford** [comment]
FYI @ozym, was this intended?

**Comment by ozym** [comment]
Yup, without looking, the goal is to make it easier for git to merge rather than for user to find/edit ... (smiley face here).

**Comment by staylorofford** [comment]
OK, @rumachan could you please cast your eye once more over the changes just to check they're still making sense with the line swap and then I will merge.

**Comment by rumachan** [comment]
TOTM example above TEMO has current entry above older ones such its consistent. Think its still clear. Given its a complex CSV file, anyone wanting to use it will be prepared to examine it closely anyway.

**Comment by staylorofford** [comment]
Thanks Steve, can you please reapprove then I can merge.

**Review by rumachan — APPROVED** [review]

**Comment by staylorofford** [comment]
This classes as a moderate change, so I do need @CBurton90 or am approved RIM team member to review.

**Review by CBurton90 — APPROVED** [review]
Serial looks correct to me

**Pull request merged**
