### PR TITLE
135A strong motion station Closing date

### PR DESCRIPTION
**Pull request by salichon**
Housecleaning for old strong motion station

### CODE REVIEW

**Comment by mnaguit** [comment]
Hi @salichon . Should we close the recorders.csv too? (under install/recorders.csv)

**Comment by salichon** [comment]
@samgeonet 
thanks 
corrected

**Comment by salichon** [comment]
Igot it right now..  overlaping changes- thank

**Comment by salichon** [comment]
@mnaguit Would you approve again - I Resolved a confilct 
Thansk 
cheers
Jerome

**Comment by salichon** [comment]
Verified with what we got: https://service.geonet.org.nz/fdsnws/station/1/query?station=101D
FYI @samgeonet

**Pull request merged**
