### PR TITLE
Hydrophone array Delta datalogger Q330/6 configuration 

### PR DESCRIPTION
**Pull request by salichon**
Hydrophone arrays have only a Q330/3 configuration
They have a Q330/6 configuration now
`autogo provided`

### CODE REVIEW

**Comment by mnaguit** [comment]
`Q330S/6` is the new datalogger. Is `Q330S/6` recognized by the code as having the same response as `Q330/6` ?

**Comment by CBurton90** [comment]
@mnaguit @salichon As Muriel said I think we need to explicitly state `Q330S/6`. Sorry this combination change caught me off guard : (

**Comment by salichon** [comment]
oui oui done and dusted now :) thanks !

**Review by mnaguit — APPROVED** [review]
👍

**Comment by salichon** [comment]
happy with it @CBurton90?

**Review by CBurton90 — APPROVED** [review]

**Pull request merged**
