### PR TITLE
CMWZ sensor swap

### PR DESCRIPTION
**Pull request by mnaguit**
- from Kinemetrics FBA-ES-T to Guralp Fortis
- for HN(ENZ) at LC 20

### CODE REVIEW

**Review by CBurton90 — APPROVED** [review]

**Review by salichon — COMMENTED** [review]
ola!  @mnaguit 
this needs  a assets entry i think

**Comment by mnaguit** [comment]
> ola! @mnaguit this needs a assets entry i think (and firmware maybe)

Entry for Fortis TF1114 already in `sensors.csv `
For firmware, we don't have version control yet for this sensor yet.

**Comment by salichon** [comment]
Okay - no worries mmy bad - Guralp fortis is a Strong motion Sensor (not a  "recorder" version)  :)

**Comment by mnaguit** [comment]
PR ready to be merged now Sir @salichon ? Thanks 😉

**Review by salichon — APPROVED** [review]

**Pull request merged**
