### PR TITLE
BWHS reoccupy

### PR DESCRIPTION
**Pull request by salichon**
BHWS station reoccupied:
Created site 21 BN/HN   
Corrected site 20 BN/HN

### CODE REVIEW

**Comment by salichon** [comment]
@jristau  I assigned you here too  FYI  and to follow the process / and or to merge  while delta updating :)

**Comment by salichon** [comment]
Corrected some ended dates on site 20 from 2015 that were not relevant to the data apparently

**Comment by ozym** [comment]
@salichon it's probably the trailing "0" on the location which the csv reading code doesn't handle too well (a bug as these should give an indicate in accuracy).

**Comment by salichon** [comment]
yeap Thanks Mark .. again this one!
sorry i forgot

**Comment by salichon** [comment]
height is also at 0 ...
I ll set this up to a default 9999

**Comment by samgeonet** [comment]
Device says its 31.3m elevation

**Comment by nbalfour** [comment]
That sounds way off given the location. Must be from the external GPS on a roof. On maps I get anything from 2-12 m

**Comment by samgeonet** [comment]
Just had a another look on the CUSP - it now says 20.7m elevation. The antenna looks to be about 3m off the ground at the site.

**Comment by salichon** [comment]
@sam @nbalfour 
are you willing to  set up a realistic elevation ?

**Comment by samgeonet** [comment]
This will be a problem for all urban strong motion sites. I believe the elevation is taken from the GPS antenna and these are not accurate in urban areas

**Comment by nbalfour** [comment]
Yes, it is a problem and we have recently had complaints about it, especially for the Christchurch sites. It's not an issue from an earthquake location perspective but it is when people try to study the shallow subsurface and site response. I'll have a chat with @peanutty about it and @JonoHanson has looked into it as well in relation to resolve the complaint.

**Comment by JonoHanson** [comment]
I propose using 3m as the elevation (based on Google Earth, Tumonz and having visited it in the field). But as Nat has mentioned, we know this  and are working on what do with wayward elevation data.

**Comment by samgeonet** [comment]
Google Earth indicates the ground level for the Hospital is around 7m

**Comment by salichon** [comment]
I deem the latest goolge earthof 7 meters 
and i ll proceed to the height update

**Comment by salichon** [comment]
Delta update BWHS:
 I added a commit in the PR to fix the BHWS site height
@nbalfour @ozym @samgeonet

**Comment by salichon** [comment]
@nbalfour @ozym @samgeonet
This stations also needs to be reopened (a new commit)
sorry I ll proceed accordingly.

**Comment by salichon** [comment]
All good 
it s already opened!

**Comment by salichon** [comment]
on hold before other reviews.

**Comment by salichon** [comment]
@mnaguit 
hi there for you to have a look at the different changes on this station
 and tell me when we proceed to the merging ;))))
 when we catch up for a delta training .... yay!
thanks
jerome

**Comment by salichon** [comment]
@ozym Is BWHS all good for you ? 
( I think so I m perhaps tight,  following the process policy for 3 reviewers ... sorry )

**Comment by salichon** [comment]
right  ill proceed

**Pull request merged**
