### PR TITLE
VRZ datalogger swap

### PR DESCRIPTION
**Pull request by mnaguit**
- from Q330S/6 (SN 6719) to Centaur (SN 9457)
- for LC 10 (LH/HH-ENZ)
- Centaur firmware v4.5.20

Current network metadata does not match details in the latest (https://github.com/GeoNet/tickets/issues/12438#issuecomment-1360646320). Would you like me  to update the coordinates and elevation? @CBurton90

### CODE REVIEW

**Review by CBurton90 — APPROVED** [review]

**Comment by CBurton90** [comment]
@mnaguit no that's fine

**Comment by mnaguit** [comment]
How about you Sir @salichon ? Happy? 😄

**Review by salichon — APPROVED** [review]
this is looking good
image

**Comment by mnaguit** [comment]
🤣

**Pull request merged**
