### PR TITLE
chore: remove the altus config app

### PR DESCRIPTION
**Pull request by ozym**
This altus app is no longer used and its configuration is now not required. Extra information has been added to a docs file for future reference.

### CODE REVIEW

**Comment by mnaguit** [comment]
Hi @ozym , what should we be checking to have a meaning review of this PR (same as the CUSP)? Thanks.

**Comment by ozym** [comment]
@mnaguit I guess there isn't much to review (it's simply part of the process) - but I have transcribed some of this context from the source code files that will be deleted into a document for future reference. So a review of that, including my transcription of details, would be great.

**Comment by mnaguit** [comment]
Thanks @ozym, can you please enlighten me where the source files are? 
From a quick check of the changes, I observed the file name is `Kinematics-Altus.md` and should be changed to `Kinemetrics-Altus.md`.

**Comment by ozym** [comment]
@mnaguit have renamed the files, the ones you can't find have been deleted. They will be in the PR but not shown fully, e.g. main.go and build.go

**Review by mnaguit — APPROVED** [review]

**Review by junghao — APPROVED** [review]

**Pull request merged**
