### PR TITLE
add geomag SBAM metadata and GSM-90F1 proton model

### PR DESCRIPTION
**Pull request by elidana**
this is adding SBAM metadata and the most recent proton model (GSM-90F1).
Response file need to be checked as I did copied the one we already have for the GSM-90 model
specs I was able to find thanks to mr. google are: https://www.gemsys.ca/wp-content/uploads/2013/04/GSM-90-Monitoring.pdf or https://www.gemsys.ca/wp-content/themes/gemsystems/pdf/GEM_gsm90-didd-superg_Observatory_monitoring.pdf

### CODE REVIEW

**Review by merijnthornton — DISMISSED** [review]
LGTM

**Comment by elidana** [comment]
thanks @merijnthornton ! If it looks fine can you please approve?

**Comment by elidana** [comment]
hi @ozym , can I please have your thumbsup for this one? I had to resolve some conflicts and have added a previous install at Scott Base

**Comment by ozym** [comment]
I'm not 100% sure what the difference between the 90 and 901F is (I thought they were the same and their response will be), the old 19 was different.

**Comment by ozym** [comment]
We don't have the slow version as far as I recall.

**Comment by elidana** [comment]
this was based on some messages @merijnthornton sent me (copied below) for EYWM, that then expanded further
> Proton is a standard GEM GSM-90.

> Just saw that it says gsm-19. that should be gsm -90
> gsm 90 is the observatory grade magnetometer. Gsm 19 is the walking survey magnetometer. 
> I see you have put GSM90 for AHAM
> The only difference is the sampling time. F stands for fast sampling (1 seconds)
> All three (four inc old SBA) now have F models.


that's an image @merijnthornton shared for SBAM
image (5)


and this photo is from 2017 (West Melton)
image

**Review by tanjapetersen — APPROVED** [review]
looks good to me

**Comment by elidana** [comment]
great thanks!!

**Pull request merged**
