### PR TITLE
HOWZ datalogger swap

### PR DESCRIPTION
**Pull request by mnaguit**
- from Q330/3 SN957 to Centaur SN9508
- for LC 10(EH-ENZ)
- Centaur firmware v4.5.20

Tagging @moorematthew & @meganmadley , in place of @CBurton90 @salichon (currently at the Geosciences conference) ... to move this PR along 😄 
Whoever reviews this PR first, wins! 🎖️

### CODE REVIEW

**Review by meganmadley — APPROVED** [review]
LGTM! Checked values (time/dates, SN's, FW numbers) with those in the equipment change ticket

**Review by moorematthew — APPROVED** [review]
Look good @mnaguit and congrats on your 🎖️ @meganmadley

**Comment by mnaguit** [comment]
Yay! The winning tandem is MM (Matt-Megan). Better luck next time JC (Jerome-Conrad) 😆

**Comment by CBurton90** [comment]
@mnaguit We all know Jerome would be left for dead in a PR review race 🤣

**Pull request merged**
