### PR TITLE
TRWZ sensor + datalogger swap

### PR DESCRIPTION
**Pull request by Thomas-Benson**
- Removing L4C-3D (2905) from TRWZ LC 10
- Replacing with LE-3DliteMkIII (J-0942) at same location
- Removing Q330S/3 (4855) from place Traveller
- Replacing with Centaur CTR4-6S (9497) at same place
- Installing new TitanSMA (001719) at new location code LC 20
- New site coordinates `-41.398030, 175.687893, 371`
- Both SP sensor and Sm recorder have orientation 0(N) and non-axial channel codes
- Using latest firmware versions:
  -  4.5.22 for TitanSMA
  -  4.8.5 for Centaur
- Streams affected:
  - LC 10 EH-ENZ replaced sensor
  - LC 10 HN-ENZ new SM stream

### CODE REVIEW

**Review by CBurton90 — DISMISSED** [review]

**Review by mnaguit — CHANGES_REQUESTED** [review]
Hi @Thomas-Benson . Can you please double check all entries with the Titan recorder? The ticket has serial number `(00)2210`. Thanks!

**Comment by Thomas-Benson** [comment]
Fixed @mnaguit. Thanks for catching that! It looks like the original version of the ticket had the wrong SN and was updated after I made this PR.

**Review by mnaguit — APPROVED** [review]
Thanks @Thomas-Benson

**Review by CBurton90 — APPROVED** [review]

**Comment by Thomas-Benson** [comment]
Delta merged

**Pull request merged**
