### PR TITLE
WRCS Basalt to TitanSMA SM Recorder Swap

### PR DESCRIPTION
**Pull request by Thomas-Benson**
Removing Basalt (564) from WRCS LC 10
Replacing with TitanSMA (003283) at same location
Using latest TitanSMA firmware version 4.5.22
Updated streams to continuous from `2020-02-09`
Streams affected WRCS LC 10 HN-12Z

### CODE REVIEW

**Review by mnaguit — APPROVED** [review]

**Review by gva6500 — DISMISSED** [review]

**Review by CBurton90 — DISMISSED** [review]

**Comment by Thomas-Benson** [comment]
Updated orientation to `282`

**Review by CBurton90 — DISMISSED** [review]

**Comment by mnaguit** [comment]
Do we need to update the azimuth of Basalt (since 2014) in this station, from 112 to 282?
@Thomas-Benson @CBurton90 thanks!

**Comment by Thomas-Benson** [comment]
Updated historical Basalt installations from 112 to measured orientation of 282

**Review by mnaguit — APPROVED** [review]
thanks @Thomas-Benson 👍

**Review by CBurton90 — APPROVED** [review]

**Pull request merged**
