### PR TITLE
DART Stations/sites parameters

### PR DESCRIPTION
**Pull request by salichon**
- Elevation to ~9999~ 0
- Depth from N1 average on first deployed stable day
- Site code to match Pressure/height site codes

### CODE REVIEW

**Review by ozym — COMMENTED** [review]
I'd suggest not having an elevation, i.e. ",," rather than ",9999," ... that way it's known there's no elevation ...

**Comment by ozym** [comment]
@salichon or perhaps, it should simply be 0, as this is the height of the ocean (in theory), we assume for these sites that elevation means the height of the water surface which is then above the "height" or "depth" of water. 

That is, distinguish between a water sensor in crater lake, vs on the ocean floor.

**Comment by salichon** [comment]
okay i was not  sure this latest would pass the test - this was my first  guess ...

**Review by ozym — APPROVED** [review]
nice.

**Comment by salichon** [comment]
@JonoHanson @CBurton90 bump :)

**Review by CBurton90 — APPROVED** [review]

**Review by JonoHanson — APPROVED** [review]

**Pull request merged**
