### PR TITLE
Adding new NZA, NZC, and NZE values

### PR DESCRIPTION
**Pull request by meganmadley**
Adding the changes from NIWA

Files used here:
[dartNZA_2022utide.csv](https://github.com/GeoNet/delta/files/8193730/dartNZA_2022utide.csv)
[dartNZE_2022utide.csv](https://github.com/GeoNet/delta/files/8193731/dartNZE_2022utide.csv)
[dartNZC_2022utide.csv](https://github.com/GeoNet/delta/files/8193732/dartNZC_2022utide.csv)
 
Amplitude *100 to get in the correct units to match the rest of the file, consider changing this later

### CODE REVIEW

**Comment by salichon** [comment]
Hi  there
These are related to a new deployment right ?
as in "_Analyse a month worth of data for the redeployed data buoys NZA, NZC and NZE and provide tidal constituents in the same format as the previous work."_
Therefore it outdates the previous one...

Changing them straight  like this is slightly uncomfortable unless i missed something   (like changing a site lat/lon without the location code) 
 
Can we follow that up on ticket  also unless my view is not relevant, alhtough i think this chnage  should be more  documented/ explained :)  ?

**Review by salichon — COMMENTED** [review]
more info required i d assume

**Comment by meganmadley** [comment]
Hey @salichon, @ozym is in the process of updating this file so that we can add deployment dates, will probably update or redo this PR after that's been merged. PR if interested https://github.com/GeoNet/delta/pull/1289

**Comment by salichon** [comment]
cool and great :) 
 you can push the change later on the same PR all good

**Comment by salichon** [comment]
ok matches wiht : https://github.com/GeoNet/delta/pull/1289

**Comment by meganmadley** [comment]
Due to ordering and funky stuff, am just going to delete this PR and start again with a new PR that has the new start and end dates

**Comment by meganmadley** [comment]
Using this PR now instead https://github.com/GeoNet/delta/pull/1290 which has the start and end dates.

**Pull request closed without merging**
