### PR TITLE
JSCB response files

### PR DESCRIPTION
**Pull request by mnaguit**
- first trial: work on yaml files

Hi @ozym . I'm experimenting on this (apologies, my first time). What do you think? Is this the way to go? Thanks!

### CODE REVIEW

**Review by ozym — CHANGES_REQUESTED** [review]
Sorry @mnaguit that's the old way of doing things.

The configuration is actually in:

```
resp/files/combined_Canterbury-Seismic-Instruments_Cusp_200sps.xml
```
this is why the question was asked about the sensor being different.

What you need to do is update:

```
install/components.csv
```

and make some lines similar to the CuspM & Cusp-Me sensors.

**Comment by mnaguit** [comment]
Yay, it is good to learn new things...will revise now! Thanks for your very quick response @ozym 👍 
Changes made, ready for your review.

**Review by ozym — APPROVED** [review]
Looks good, worth a go.

**Review by salichon — APPROVED** [review]
Thanks @mnaguit @Thomas-Benson 
to wshow the new ways :)

**Comment by ozym** [comment]
Should have mentioned you will also need to update the channels.csv file too

install/channels.csv

**Pull request merged**
