### PR TITLE
Alloy FW upgrades for Wednesday 12

### PR DESCRIPTION
**Pull request by meganmadley**
MAKO - 5921R40124 - 2022-10-11T20:31:20

### CODE REVIEW

**Comment by meganmadley** [comment]
PARW - 5920R40110 - 2022-10-11T21:28:00

**Comment by aleks-spes** [comment]
MCNL - 5920R40019 - 2022-10-11T21:01:27

**Comment by aleks-spes** [comment]
RGMT - 5944R40034 - 2022-10-11T21:29:41

**Comment by aleks-spes** [comment]
TURI - 5945R40085 - 2022-10-11T22:31:08

**Comment by meganmadley** [comment]
TGHO - 5920R40012 - 2022-10-11T22:32:30

**Comment by meganmadley** [comment]
@aleks-spes your values look good to me!

**Review by aleks-spes — APPROVED** [review]
Looks good!

**Pull request merged**
