### PR TITLE
Add topographic elevations to stations with unknown elevations

### PR DESCRIPTION
**Pull request by Thomas-Benson**
- Attempting to rectify the large number of (mostly historical) sites with unknown elevations in delta.
  - Unknown elevations are recorded as `9999m`, which has possible ELS implications for future versions of SeisComp if left in its current state.
  - Elevation values here were retrieved from the LINZ data service.
  - Mostly from https://data.linz.govt.nz/layer/50768-nz-contours-topo-150k/, with gaps filled in from https://data.linz.govt.nz/layer/51768-nz-8m-digital-elevation-model-2012/
 
TODO: a few sites that are offshore/outside NZ that didn't have topographic data available

### CODE REVIEW

**Review by salichon — COMMENTED** [review]
this is looking good to  me 
- some occasional rounding to the closest  meter would ne nice
- some very occasional formating is better e.g _009_ -> _9_ instead (see WI227 and OT001)

**Comment by Thomas-Benson** [comment]
- Fixed a bug in my rounding script which was messing up entries it wasn't meant to
- Added elevations for a few more stations that my automatic script didn't find the first run through
- Redid the rounding with better formatting
- Stripped unneccessary trailing zeroes in stations.csv.

**Comment by Thomas-Benson** [comment]
@salichon who else did you think needs to review this one?

**Review by salichon — APPROVED** [review]
@staylorofford  or @CBurton90  woudl you be happy (as much as can be)  to bless  this site elevation PR ? 
Thanks  a lot ! 
cheers
jerome

**Review by CBurton90 — APPROVED** [review]

**Pull request merged**
