### PR TITLE
Add Alloys + Zephyrs

### PR DESCRIPTION
**Pull request by moorematthew**

### CODE REVIEW

**Comment by samgeonet** [comment]
@elidana @staylorofford can you please merge once approved

**Comment by samgeonet** [comment]
They are in numerical order @elidana

**Comment by moorematthew** [comment]
@elidana Not sure I can squash the 2 commits as I don't have merging rights?

**Comment by elidana** [comment]
@samgeonet and @moorematthew all done now, apologies if I though they were not sorted numerically

**Pull request merged**
