### PR TITLE
QRZ & KUZ - Update sensor serial numbers 

### PR DESCRIPTION
**Pull request by moorematthew**

### CODE REVIEW

**Comment by moorematthew** [comment]
change ticket here (KUZ): https://github.com/GeoNet/tickets/issues/8910
QRZ: https://github.com/GeoNet/tickets/issues/9545

**Review by mnaguit — APPROVED** [review]
Looks consistent @moorematthew 😄 

Tagging @salichon in here, just in case he wants to scold you. 😆

**Comment by salichon** [comment]
Hello my dears @moorematthew @mnaguit 
I reckon not all of us have the power to merge 
since it s been done and reviewed by you guys - 
If necessary i can t at least push ze button ....  or Muriel either ways this is good !
NB: The commits would be more specific about the changes if we need to track those for a good practice.

**Comment by moorematthew** [comment]
@salichon I am the one without such merging powers! Happy for it to be merged now though. @mnaguit was just making sure you had the opportunity to make me pay for my mistakes 🤣

**Comment by mnaguit** [comment]
What is happening in here gentlemen? @salichon @moorematthew 
Anything I can do to make your Monday morning lovely? 😆

**Pull request merged**
