### PR TITLE
DART  Network Station Sites Creation

### PR DESCRIPTION
**Pull request by salichon**
- This branch contains the base information for the DART stations and sites  for  NZA NZE, NZC and NZF
- Documentation is attached for naming and convention 
--> (Postponed when more informed on another PR)
- No instrumentation metadata is attached in this version:  waiting for the data and formats to be described (will be provided later)

### CODE REVIEW

**Comment by salichon** [comment]
Okay indeed ... - Delta Markup format and additional content will be  added later on another PR.

**Comment by JonoHanson** [comment]
can we put in here what the proposed long names are for all DART buoys, please, so that we have that visibility?

e.g. NZA, Offshore Wellington Hikurangi
NZB,
NZC, Offshore Gisborne Hikurangi
NZD, 
NZE, Offshore East Cape Kermadec
NZF, Offshore Raoul Kermadec
NZG,
NZH,
NZI,
NZJ
NZK,
NZL

**Comment by JonoHanson** [comment]
merging of PR paused while we sort out the long names for the sites

**Comment by JonoHanson** [comment]
I like it, but I propose taking the direction part out, so:

Naming: _**Offshore** **City/Region**(NZ) or **Island** (overseas) of reference **Trench** of reference_  


e.g. NZA, Offshore Wellington Hikurangi
NZB, Offshore Hawke's Bay Hikurangi  
NZC, Offshore  Gisborne Hikurangi
NZD, Offshore Bay of Plenty Kermadec
NZE, Offshore East-Cape Kermadec
NZF, Offshore Raoul Kermadec
NZG, Offshore Tongatapu Tonga
NZH, Offhore Niue Tonga 
NZI, Offshore Samoa Tonga
NZJ, Offshore Norfolk Island New Hebrides
NZK, Offshore New-Caledonia New Hebrides
NZL, Offshore Vanuatu New Hebrides

**Comment by salichon** [comment]
@JonoHanson  
This PR ma   require at least an additional information, the World Meteorolgical Organisation Identfier given to the Buoys  ( 7 digits XX12345  )   XX being the WMO region number

**Comment by JonoHanson** [comment]
Another long name proposal

Naming: Offshore City/Region(NZ) or Island (overseas) of reference Trench of reference - 7 Digit WMO number

e.g. NZA, Offshore Wellington Hikurangi - 7654321
NZB, Offshore Hawke's Bay Hikurangi - 1234567
NZC, Offshore Gisborne Hikurangi - etc.
NZD, Offshore Bay of Plenty Kermadec
NZE, Offshore East Cape Kermadec
NZF, Offshore Raoul Kermadec
NZG, Offshore Tongatapu Tonga
NZH, Offshore Niue Tonga
NZI, Offshore Samoa Tonga
NZJ, Offshore Norfolk Island New Hebrides
NZK, Offshore New Caledonia New Hebrides
NZL, Offshore Vanuatu New Hebrides

**Comment by JonoHanson** [comment]
One last long name proposal - the three options will be put to the DART Data Management working group and approved there

Naming – 7 Digit **WMO number** 

e.g. NZA, 7654321
NZB, 1234567
NZC, 2345678
NZD, 3456789
NZE, 4567890
NZF, 5678901
NZG, 6789012
NZH, 7890123
NZI, 8901234
NZJ, 9012345
NZK, 0123456
NZL, 0987654

**Comment by JonoHanson** [comment]
@salichon the long name format above has been approved by the Delta DM working group.

however I'd query why there is not depth information for the DARTs that have been deployed. Can we add that, please.

**Comment by salichon** [comment]
@JonoHanson okay - the depth information will  be informed when we ll set the instrumentation (BPR).
so far the site is located or considered at the sea level.

**Comment by JonoHanson** [comment]
@salichon roger, lets do this.

**Pull request merged**
