### PR TITLE
Recorder swap for BOWS

### PR DESCRIPTION
**Pull request by mnaguit**
- for LC 20 with HN(12Z) streams
- firmware as is ~(no change for version m001.03.08)~
- from EQR120 (46535) to EQR120(46529)

Kindly let me know if an update in firmware is needed. @moorematthew 
Thanks!

### CODE REVIEW

**Comment by mnaguit** [comment]
Okidoki. Thanks @moorematthew . I'll update the metadata, noting the `2.1.1` is the first entry for EQR120 firmware version. Shall I put it this format: `m2.1.1` or `m002.01.01` ? Thank you. 😃

**Comment by moorematthew** [comment]
@mnaguit hmm good question. I think lets go with just `2.1.1` as that's how the device lists it now vs the previous FW version was listed in the device as `mXXX.XX.XX`. See below pics. Also open to other ideas....

BOWS EQR FW


EQRFW

**Review by moorematthew — APPROVED** [review]
Looks good to me

**Comment by mnaguit** [comment]
Okidoki. Thanks @moorematthew 👍 
This PR is waiting for your approval (& @salichon ), then we're all good! 😄

**Review by moorematthew — APPROVED** [review]
All good for me :)

**Comment by moorematthew** [comment]
@salichon took some pleasing but glad we got there in the end

**Pull request merged**
