### PR TITLE
MKAZ changedatalogger

### PR DESCRIPTION
**Pull request by mnaguit**
change logger Q330 to Q330S/6

### CODE REVIEW

**Comment by salichon** [comment]
@peanutty @mnaguit 
I refer here your remark  about the asset numbers of the other stations and specifically MBAZ serial
 https://github.com/GeoNet/tickets/issues/2778

**Comment by mnaguit** [comment]
@salichon It's MKAZ, not MBAZ.

@peanutty 
MKAZ is now on Q330S/6 Serial number 6136. 
Whereas for ETAZ, the same datalogger (Q330S/6 Serial number 6136) was specified in the ticket: https://github.com/GeoNet/tickets/issues/2778

**Comment by ozym** [comment]
This is what I see right now ....

``` xml
<?xml version="1.0" encoding="utf-8"?>
<status>
  <q330 id="seismic-moumoukai" address="seismic-moumoukai" ipaddr="192.168.196.214" host="seismic-moumoukai.wan.geonet.org.nz" serial="0x003350092f58ff826" kmi="6142" sysver="116" timestamp="1531104374"/>
</status>
```

``` xml
<?xml version="1.0" encoding="utf-8"?>
<status>
  <q330 id="seismic-easttamakireservoir" address="seismic-easttamakireservoir" ipaddr="192.168.196.134" host="seismic-easttamakireservoir.wan.geonet.org.nz" serial="0x0033500dce457e0ce" kmi="6136" sysver="116" timestamp="1531104332"/>
</status>
```

**Comment by peanutty** [comment]
@mnaguit @salichon @ozym the boys made a balls up with serial numbers in tickets. Long serial numbers should be correct (marks previous comment confirms this)

**Comment by mnaguit** [comment]
@salichon @ozym @peanutty 
Thanks Mark and Dan. So I guess I would have to create new pull request for MKAZ, before I can start with ETAZ.

**Comment by mnaguit** [comment]
https://github.com/GeoNet/delta/pull/341

merged: MKAZ new pull request for serial correction

**Pull request merged**
