### PR TITLE
NSxx MRP Ngatamariki private commercial - metadata removal

### PR DESCRIPTION
**Pull request by salichon**
metadata removal - no streams - commercial experiment
no data in the archive

### CODE REVIEW

**Review by mnaguit — COMMENTED** [review]
Is `TC20121206,INFR,82` in `install/sensors.csv` supposed to be deleted?
Thanks @salichon

**Comment by salichon** [comment]
Thanks @mnaguit - correction is performed
Will be another blessing

**Review by mnaguit — APPROVED** [review]
Thanks @salichon 👍

**Review by mnaguit — APPROVED** [review]
No worries @salichon 👍

**Pull request merged**
