### PR TITLE
RTxx - RT01 to RT11 - Closing NX stations

### PR DESCRIPTION
**Pull request by salichon**
RTxx stations 01 to 11 Changed 9999 (opened) dates  and made consistent 
 to the best of our knowledge or default dates,
for the most informed batch of the Rtxx stations

### CODE REVIEW

**Review by mnaguit — COMMENTED** [review]
-	_Just a comment:_ The end date for open RT* is set to the latest end date available for this bunch of stations (which is in 2013). Reference -`sites.csv`
-	_A query:_ For all stations, regardless of the chosen end dates, is there a need to match the end dates both files (`sites.csv` and `stations.csv`) for consistency?

**Comment by salichon** [comment]
@mnaguit i ll go back to this RT01 to RT11 closing dates  thanks :)

**Comment by salichon** [comment]
@mnaguit hello! 
 as long as the sites are opening after the stations there is no logical need for  a same start.
I have done it anyway :) 
cheers
jerome

**Comment by mnaguit** [comment]
> @mnaguit hello! as long as the sites are opening after the stations there is no logical need for a same start. I have done it anyway :) cheers jerome

Hi @salichon 
Thanks. How about the other way around, looking at the end date...the site is already closed but the station is still open?

**Comment by salichon** [comment]
Heelo @mnaguit 
> (e.g. for RT10, site was closed in 2009 while station was closed in 2013).
i m not sure there do you mean RT01?

**Comment by mnaguit** [comment]
Hi @salichon 
I'm comparing the end dates of s`ites.csv` & `stations.csv`
If they don't necessarily need to match, then it's all good.

**Review by mnaguit — APPROVED** [review]

**Pull request merged**
