### PR TITLE
SB building array BN 50Hz are CLOSED by Dec 2019

### PR DESCRIPTION
**Pull request by salichon**
Date used is a default for the latest archived SB network 50 Hz data stored. (2019.344)

### CODE REVIEW

**Comment by salichon** [comment]
Hi @mnaguit  
- I  ll reopen the AVAB 200Hz  Provided  that NO 200 Hz  HN  data were stored for a long period  between Feb 2012  and October 2019 , i ll reflect this into delta.
- Can you  detail your comments about HBRB since i see  it s already closed since September for the 50  Hz ?
- There are only data for CBLB from 2018 , and  the HN data  are starting from 2019, I ll anyhow close only the 50 Hz  streams according to the default date for the building arrays.

**Comment by mnaguit** [comment]
Hi @salichon . Thanks.

- For AVAB: based on data archive for 2019 HN* streams are available in all LC from 2019.283 to 2019.345
- Yes you're right for HBRB. I thought the ticket closing the 50hz is still pending. 50hz streams are indeed closed in September 2019 and opening/closing for 200hz were updated as well. So all good for this array.
- Yes for CBLB. As all 50hz streaming were turned off wrt that 200hz switch, then we have to update all metadata corresponding to that switch.

Also, kindly include in the loop other reviewers so that they can start looking into these changes and for everyone to be in the same page.

**Comment by salichon** [comment]
@mnaguit the last change have been made
@ozym @samgeonet 
It s a kind of tedious PR with lots of  similar change on the streams provided into the metadata- sorry.
AVAB 200Hz closed and opened shows the HN absence within 2012-2019 in our data.   
cheers

**Comment by salichon** [comment]
Hello @ozym
Is this PR for closing 50 Hz okay for you?  ( while not asking to review all the building arrays closing dates , just the 50 Hz closing in general for sure ...  ) 
thanks
cheers
jeorme

**Comment by salichon** [comment]
@mnaguit @samgeonet 
all right there is a bit to re- review here 
FYI @jygns

**Comment by salichon** [comment]
@mnaguit update - We are getting there :) 
thanks

**Comment by salichon** [comment]
@mnaguit 
Last change   I hope :)
thanks

**Pull request merged**
