### PR TITLE
Update firmware.csv

### PR DESCRIPTION
**Pull request by ricardojohansson**
Updated firmware to (11.01) on CR6 SN4117 & SN 15369, plus added entries for the three recently purchased CR6 (SN 17444, 17445 & 18430) - all having 11.01

### CODE REVIEW

**Review by rumachan — CHANGES_REQUESTED** [review]
There are some issues where start time is earlier than previous endtime, such as this. This will be why the changes fail the technical check

Campbell Scientific,CR6,15369,CR6.Std.10.02,2021-05-07T00:00:00Z,2022-04-01T23:59:00Z,
Campbell Scientific,CR6,15369,CR6.Std.11.01,2022-04-01T00:00:00Z,9999-01-01T00:00:00Z,

**Comment by ricardojohansson** [comment]
Thanks for spotting @rumachan... I've updated the offending dates

**Comment by ozym** [comment]
@rumachan I've rebased this PR onto the main branch.  I think it was waiting on your sign-off before being merged.

**Review by rumachan — APPROVED** [review]
Sorry, apparently I completely forgot about this! All good

**Comment by rumachan** [comment]
Thanks @ozym that one must have fallen through the cracks.

**Pull request merged**
