### PR TITLE
HRMT new tsunami gauge site equipment install

### PR DESCRIPTION
**Pull request by meganmadley**
Got the start time from @CBurton90's image in slack 2022-12-22T00:31:15

image

### CODE REVIEW

**Review by elidana — COMMENTED** [review]
hei @meganmadley , not 100% sure but I wonder if we also need an entry in the `install/connections.csv` file with something like
`HRMT,40,Horomatangi Reefs,,0,2022-12-22T00:31:15Z,9999-01-01T00:00:00Z`
?

will continue review other bits now

**Review by salichon — CHANGES_REQUESTED** [review]
Ciao there indeed 
You re   missing the bit of virtual "wire"  between the datalogger and the sensor
as in the `connections.csv` 
all good to have  `HRMT,40,Horomatangi Reefs,,0,2022-12-22T00:31:15Z,9999-01-01T00:00:00Z` (pin number set to `0` or `' '` to default either ) -

**Comment by CBurton90** [comment]
@meganmadley I think we can put the sensor dip as `90` (similar to NBRT/TAUT) as Jackson confirmed they are a vertical mount. Thanks for using my screenshot (haha).

**Review by salichon — APPROVED** [review]
sweet as a mince pie to me

**Comment by meganmadley** [comment]
Thanks @elidana and @salichon, have added the connections file

**Comment by meganmadley** [comment]
Have added the sensor dip @CBurton90 :)

**Review by CBurton90 — DISMISSED** [review]

**Comment by salichon** [comment]
Sensor dip should not have too much importance since we are on a  pressure measurement

**Comment by meganmadley** [comment]
Oh well, it's been changed anyways

**Comment by elidana** [comment]
have checked with @salichon the scale factor, good to keep 1 as it is freshwater

**Review by elidana — DISMISSED** [review]
looks good, thanks @meganmadley !

**Review by ozym — DISMISSED** [review]
It shouldn't have a dip as it's a pressure sensor (i.e. the sensor points in all directions) so we usually use 0.

**Comment by meganmadley** [comment]
Changed sensor dip back to 0 (@CBurton90 and @ozym)

**Review by ozym — APPROVED** [review]

**Review by elidana — APPROVED** [review]
thanks for changing sensor dip back to 0!
I think is now good to be merged? (after squashing all commits)

**Comment by meganmadley** [comment]
Thanks everyone! :)

**Comment by CBurton90** [comment]
@meganmadley Sorry about that!

@ozym might be worth considering an updated PR in the new year then to revert all to 0 as there seems quite a mix between 0 and 90

**Comment by salichon** [comment]
@CBurton90 you mean a general  Gauge dips deep house cleaning in delta  i guess

**Comment by CBurton90** [comment]
> @CBurton90 you mean a general Gauge dips deep house cleaning in delta i guess

@salichon now you are speakin ma language

**Pull request merged**
