### PR TITLE
RAHZ EH  sensor swap

### PR DESCRIPTION
**Pull request by salichon**
Replace the L4C-3D  with a LE-3Dlite Mk3 on RAHZ

### CODE REVIEW

**Comment by salichon** [comment]
Waiting for confirmation of the former assets serial number - Prior to merging

**Comment by mnaguit** [comment]
Hi @salichon 
Currently reviewing this PR. Data starts to come in around 2018-09-27T00:28:00UTC
Should this be the opening time for Lennartz?

rahz_review

**Comment by salichon** [comment]
Hi there @mnaguit 
since there are no data before since  a while i felt  confident to start the response the day of the install  2018-09-27T00:00:00Z and closed the previous on the 26/09

**Comment by mnaguit** [comment]
Noted @salichon . Just checking. As an apprentice, my delta master trained me to be very particular with opening and closing times. =)

Sending the review now...

**Pull request merged**
