### PR TITLE
MSZ CMG-3ESP to TH120-2 BB sensor swap

### PR DESCRIPTION
**Pull request by Thomas-Benson**
- Removing CMG-3ESp (T3E65) from MSZ LC 10
 - Replacing with TH120-2 (2837) at same location
 - Streams affected MSZ LC 10 HH-ENZ

### CODE REVIEW

**Review by gva6500 — APPROVED** [review]

**Comment by mnaguit** [comment]
Just a thought: should we update the LH* streams as well?

MSZ_LH

**Comment by gva6500** [comment]
> Just a thought: should we update the LH* streams as well?
> 
@mnaguit  this was just a Seismometer swap, so as far as I know there should be no changes to streams....  but I could very well be wrong 😬

**Comment by mnaguit** [comment]
> > Just a thought: should we update the LH* streams as well?
> 
> @mnaguit this was just a Seismometer swap, so as far as I know there should be no changes to streams.... but I could very well be wrong 😬

Most of the time you are very right @gva6500 😄 
Not sure where I got the idea, probably just Friday blues. I thought there was a discussion in the recent past, to close all LH*. Looks like I am very wrong. 😆 

... Approving this now, in a few seconds

**Review by mnaguit — APPROVED** [review]
Thanks @Thomas-Benson 😄

**Comment by CBurton90** [comment]
@mnaguit Were you thinking of LN* streams for SM? I think those were the streams we were closing off in delta (doubt there are any actually running in the network). LH* broadband streams are here to stay though : ).

**Comment by mnaguit** [comment]
Hahaha, thanks for that @CBurton90 ! I knew there's something about the 1hz streams! 🤣

**Pull request merged**
