### PR TITLE
MSMC recorder swap

### PR DESCRIPTION
**Pull request by mnaguit**
- from CUSP 3D SN42043 to EQR120 SN46537
- firmware recorded for EQR120: m001.03.08
- for LC 20 with HN-12Z (axial components)

### CODE REVIEW

**Comment by mnaguit** [comment]
Hi @CBurton90 .
I used the same azimuth as per old recorder (CUSP3D) which was 29.
Does this apply to the new recorder (EQR120)?

**Review by CBurton90 — DISMISSED** [review]

**Review by salichon — DISMISSED** [review]
All good to me  
also 
@mnaguit 
Do you want to add ib this PR   the start of the 200Hz continuous ? 
for this station it is 09/02/2020

**Comment by mnaguit** [comment]
Thanks @salichon 

I have modified the closing of 200hz triggered & opening of 200hz continuous.
Can you please do another quick review, before I merge this PR? Thanks.

**Review by salichon — APPROVED** [review]
ya!

**Pull request merged**
