### PR TITLE
MUGZ datalogger swap

### PR DESCRIPTION
**Pull request by mnaguit**
- from Q330/3 (2349) to Centaur (9729)
- for LC 10 (EH-ENZ) streams
- Centaur firmware v4.5.20

### CODE REVIEW

**Review by salichon — APPROVED** [review]
yup

**Comment by mnaguit** [comment]
Aye @moorematthew , are you happy to review this while @CBurton90  is on leave? 😉

**Review by moorematthew — APPROVED** [review]
looks amazing to me

**Comment by mnaguit** [comment]
Many thanks @moorematthew 👍

**Pull request merged**
