### PR TITLE
CHST Tsunami Gauge swapping Q330 for Centaur

### PR DESCRIPTION
**Pull request by megankortink**

### CODE REVIEW

**Review by mnaguit — CHANGES_REQUESTED** [review]
All good with the changes @megankortink 
Just add the Centaur in the firmware tracking (`install/firmware.csv`)

**Comment by megankortink** [comment]
Thanks @mnaguit install/firmware was done :) should be three files changed

**Review by mnaguit — APPROVED** [review]
Thank you @megankortink

**Review by salichon — APPROVED** [review]
legit

**Review by CBurton90 — APPROVED** [review]

**Pull request merged**
