### PR TITLE
remove GeoNet asset for GNS asset

### PR DESCRIPTION
**Pull request by merijnthornton**
removed Kinemetrics Inc.,Q330S/6,6894 asset number as it is a GNS asset

### CODE REVIEW

**Comment by samgeonet** [comment]
This will require a GNS asset number which @tanjapetersen will need to source. Please don't merge until we have added a GNS number

**Comment by tanjapetersen** [comment]
Can you help me with these details please (as you have done it for the 10 others?):

- [ ] PORD #
- [ ] Serial #
- [ ] Supplier details.
- [ ] Warranty details.
- [ ] Product specifications if relevant.

**Comment by tanjapetersen** [comment]
Status: waiting for maintenance@gns to issue an asset number

**Comment by salichon** [comment]
@samgeonet Someone should merge this asset befor it s been used  .. :)
I m updating the branch 
Who s  privilege to merge this into delta ? 
Hmm it seems that this review should be  discontinued before correction - I ll proceed to the review then

**Comment by ozym** [comment]
@salichon it's not 100% required that the asset have an asset number assigned, this is primarily used as a visual check, and an indication that it is GNS/GeoNet hardware.

It can be added later once a number has been assigned.

**Comment by tanjapetersen** [comment]
Here it comes: The asset number is EQ014407 (fresh out of the press from GNS Finance)

**Comment by salichon** [comment]
@samgeonet @merijnthornton  Sorry for this ticket that went through a crack (mine)!
Can you check if it s still relevant ? 

I updated the branch ->  nothing is broken and I approved it

**Pull request merged**
