### PR TITLE
fix: update HBRB/TDFB/STSB xyz channel labelling

### PR DESCRIPTION
**Pull request by mnaguit**
- 1st batch for structural array sites needing axial flag update to XYZ (noting there should be no 12Z streams in the archive)

### CODE REVIEW

**Comment by mnaguit** [comment]
Hi @ozym and @salichon , I'm doing this in stages (like 3 arrays per set) dealing with arrays with XYZ components only in the archive. 
@ozym is there a need to update another file or jus the `streams.csv`? I assumed that the change in `collection.go` (as per trial run in WQAB) was applicable to all arrays?
@salichon this step fixes the issue in channel labelling (e.g., miniseed data has XYZ, but response expects 12Z channel labels). It has been tested for one array - WQAB (thanks to Mark!), and it worked!

**Comment by mnaguit** [comment]
Hi @ozym & @salichon , following up on this PR --can you please review and approve if you are happy with the changes?

**Comment by salichon** [comment]
Hi  there ! 
I reckon this needs to check the output in the form of a response file for instance :)

**Comment by mnaguit** [comment]
hi @salichon. Yes, please see the main ticket (https://github.com/GeoNet/tickets/issues/15278#issuecomment-2036140628). We tried in for one array (WQAB), and response file is now accessible despite the data in XYZ flag.

**Comment by salichon** [comment]
tested creation of station cml file for HBRB 
all good (Y is 2 and X is 1 equivallent)
thanks @mnaguit

**Review by salichon — APPROVED** [review]
all good to me thanks !

**Pull request merged**
