### PR TITLE
Update seismic site code naming conventions to include details on sei…

### PR DESCRIPTION
**Pull request by staylorofford**
…smic site code naming conventions

### CODE REVIEW

**Review by rumachan — DISMISSED** [review]
The statement "regional networks being mostly composed of short period seismometers" does not apply so clearly to the VZ regional network (Tongariro volcanoes) but I guess overall its a fair comment.

**Comment by staylorofford** [comment]
I have updated the PR to include the SM convention Dan Whitaker has brought up about sites ending in an 'S', and added a parenthesis section about the volcano network composition as per your comment @rumachan. Please re-review.

**Review by rumachan — APPROVED** [review]
Thanks, now accurately reflects volcano networks.

**Review by salichon — COMMENTED** [review]
Hello @staylorofford 
this is looking good to me 
note in the ticket related - i ll put a reference to  the ISC "registration" 
they seem now to endorse most of our stations (used in location of events)

**Pull request merged**
