### PR TITLE
MQZ strong Recorder Orientation

### PR DESCRIPTION
**Pull request by salichon**
MQZ Strong motion is ENZ and Azimuth is 0 now.

### CODE REVIEW

**Review by mnaguit — DISMISSED** [review]
Looks good.
Note: I wasn't aware the closing-starting time can be the same (or only for the same equipment?)
👍

**Comment by salichon** [comment]
@mnaguit actually i might have to check that! you re right !

**Comment by salichon** [comment]
@mnaguit it is working but i reckon it s better to "mark" it with a little 1s break :)
I modified the PR accordingly ..

**Review by mnaguit — COMMENTED** [review]
Switch the closing-opening time? @salichon

**Comment by salichon** [comment]
@mnaguit  done ...
that s what  happens  when you  make  at the same of a  meeting .. been naughty !

**Review by mnaguit — APPROVED** [review]
All good Sir @salichon 
Thanks!

**Pull request merged**
