### PR TITLE
fix Gamit station info output filename

### PR DESCRIPTION
**Pull request by elidana**
Hi @ozym ,

a user pointed out that we were using a different name for the Gamit station.info output (thanks @megankortink !).

We were previously using `station.info.geonet` (as this metadata file is only containing geonet station, and people will have to merge it with other station.info file to also use international sites from IGS etc). When we updated the codes the output file name changed to `station.info`

Can we restore the previous name ?
I hope the changes in this pr cover the full "food chain" to get the file created, saved, and synced to the GeoNet ftp.

user request (from @megankortink )
> one of the links on the geodetic geonet page (https://www.geonet.org.nz/data/types/geodetic) is (I think) dead. The two "GeoNet ftp site" links take you to different places and only the top one (under station metadata) takes you to the right place ftp://ftp.geonet.org.nz/gps/sitelogs/, the other one takes you to ftp://ftp.geonet.org.nz/gps/sitelogs/station.info.geonet (which is a blank page). What should be the right link and who do you think would be best to contact about this?

### CODE REVIEW

**Review by megankortink — DISMISSED** [review]
Lgtm!

**Review by ozym — COMMENTED** [review]
Looks like the update in the label needs to match the option. In any case this alone will not solve the problem.

**Review by ozym — CHANGES_REQUESTED** [review]
I would like to see output file name matching that in the header.

**Comment by elidana** [comment]
Thanks @ozym!! 

not sure I fully get the change that are needed.
I have locally tested this change, and output filename and header (of the station.info.geonet file) both looks good to me.
What am I missing here?

```
[elidana@hutl16534 siteinfo]$ head station.info.geonet 
*     GAMIT/GLOBK station.info.geonet
* 
*     Generated by GeoNet on 2021-02-02 02:30 UTC
*     Send questions, comments or concerns to info@geonet.org.nz
*
*SITE  Station Name      Session Start      Session Stop       Ant Ht   HtCod  Ant N    Ant E    Receiver Type         Vers                  SwVer  Receiver SN           Antenna Type     Dome   Antenna SN
 2406  C KAIAPO TLP      2012 044 00 38 01  2015 068 00 50 00   0.0550  DHARP   0.0000   0.0000  TRIMBLE NETR9         4.42                   4.42  5117K75357            TRM57971.00      NONE   1441028123
 2406  C KAIAPO TLP      2015 068 00 50 01  2016 117 23 17 43   0.0550  DHARP   0.0000   0.0000  TRIMBLE NETR9         4.85                   4.85  5117K75357            TRM57971.00      NONE   1441028123
 2406  C KAIAPO TLP      2016 117 23 17 44  2016 218 03 08 00   0.0550  DHARP   0.0000   0.0000  TRIMBLE NETR9         5.10                   5.10  5117K75357            TRM57971.00      NONE   1441028123
 2406  C KAIAPO TLP      2016 218 03 08 01  2016 354 20 58 24   0.0550  DHARP   0.0000   0.0000  TRIMBLE NETR9         5.14                   5.14  5117K75357            TRM57971.00      NONE   1441028123
[elidana@hutl16534 siteinfo]$ ./siteinfo -h

Build a GAMIT station info file from delta meta information

Usage:

  ./siteinfo [options]

Options:

  -base string
    	base delta directory (default "../..")
  -output string
    	output info file (default "station.info.geonet")
```

**Comment by ozym** [comment]
here's my suggestion.

main.go

```diff
diff --git a/tools/siteinfo/main.go b/tools/siteinfo/main.go
index 0459c7a..8529011 100644
--- a/tools/siteinfo/main.go
+++ b/tools/siteinfo/main.go
@@ -30,7 +30,7 @@ func main() {
        }

        var output string
-       flag.StringVar(&output, "output", "station.info", "output info file")
+       flag.StringVar(&output, "output", "station.info.geonet", "output info file")

        var base string
        flag.StringVar(&base, "base", "../..", "base delta directory")
@@ -287,7 +287,7 @@ func main() {
        }
        defer file.Close()

-       if err := encodeInfo(file, update, list...); err != nil {
+       if err := encodeInfo(file, update, filepath.Base(output), list...); err != nil {
                log.Fatal(err)
        }
 }
```

and info.go

```diff
diff --git a/tools/siteinfo/info.go b/tools/siteinfo/info.go
index cc81b8e..26122c6 100644
--- a/tools/siteinfo/info.go
+++ b/tools/siteinfo/info.go
@@ -6,7 +6,7 @@ import (
        "time"
 )

-var infoTemplate string = `*     GAMIT/GLOBK station.info
+var infoTemplate string = `*     GAMIT/GLOBK {{name}}
 *
 *     Generated by GeoNet on {{update}}
 *     Send questions, comments or concerns to info@geonet.org.nz
@@ -111,9 +111,12 @@ func squashInfo(info ...Info) []Info {
 }

 // encode stream information in the "info" format.
-func encodeInfo(wr io.Writer, update time.Time, info ...Info) error {
+func encodeInfo(wr io.Writer, update time.Time, name string, info ...Info) error {

        var funcMap template.FuncMap = template.FuncMap{
+               "name": func() string {
+                       return name
+               },
                "update": func() string {
                        return update.UTC().Format("2006-01-02 15:04 MST")
                },
```

**Comment by ozym** [comment]
relates to GeoNet/tickets#8167

**Review by ozym — APPROVED** [review]

**Pull request merged**
