### PR TITLE
TRAB update metadata

### PR DESCRIPTION
**Pull request by mnaguit**
Update the metadata for LC 24, LC 26 and LC 28, aligned with the recorder swaps

All opening-closing dates from the PR are based on the information in the main ticket.

### CODE REVIEW

**Comment by salichon** [comment]
@mnaguit 
1- check Travis error messages :


>  test ./tests
--- FAIL: TestAssets (0.03s)
    --- FAIL: TestAssets/check_for_duplicate_asset_numbers (0.00s)
        assets_test.go:20: duplicate asset number CSI CUSP-Me [3De20703]: 15581 [CSI CUSP-Me [3DE-20703]]
        assets_test.go:20: duplicate asset number CSI CUSP-Me [3De20704]: 15582 [CSI CUSP-Me [3DE-20704]]
        assets_test.go:20: duplicate asset number CSI CUSP-Me [3De20705]: 15583 [CSI CUSP-Me [3DE-20705]]
        assets_test.go:20: duplicate asset number CSI CUSP-Me [3De20709]: 15587 [CSI CUSP-Me [3DE-20709]

2- check assets :

> CSI,CUSP-Me,3De20703,15581,
and 
> CSI,CUSP-Me,3DE-20703,15581,

for instance 

---> hickhock 

3- solve for duplicate assets

should be sorted



cheers

**Comment by mnaguit** [comment]
Hmmm. I already checked the duplications. After editing, it looks like those existing serial numbers are already open in another array. I'll add @jygns so he can provide further details. I used the details in the ticket as main input in this PR.

**Comment by mnaguit** [comment]
Okey. I don't have any other ideas anymore. It would be great to hear from you guys on how to satisfy Travis for the changes in this PR.

**Comment by salichon** [comment]
@mnaguit 
--> remove from the assets.csv 
:)

**Comment by mnaguit** [comment]
> @mnaguit
> --> remove from the assets.csv
> :)

Even if the recorder `3De-20750` is not on the register?

**Comment by CBurton90** [comment]
@mnaguit I think the serial numbers in recorders.csv need to be in alphanumeric order. This is what Travis expects.
```
     	        "CSI,CUSP-Me,CUSP-Me,3DE-20749,TROB,28,247,,90,0,2013-08-02T00:00:00Z,2014-07-01T00:00:00Z",
              	"CSI,CUSP-Me,CUSP-Me,3DE-20749,STSB,22,325,,0,0.353,2014-07-01T00:00:03Z,9999-01-01T00:00:00Z",
            + 	"CSI,CUSP-Me,CUSP-Me,3DE-20750,TRAB,24,278,,0,0,2014-05-01T01:00:00Z,2016-07-24T00:00:00Z",
              	"CSI,CUSP-Me,CUSP-Me,3De-20752e,STSB,29,325,,0,-18.56,2014-07-01T00:00:03Z,9999-01-01T00:00:00Z",
              	"CSI,CUSP-Me,CUSP-Me,3De-20753e,STSB,2A,325,,0,-18.56,2014-07-01T00:00:03Z,9999-01-01T00:00:00Z",
              	... // 33 identical lines
              	"CSI,CUSP-Me,CUSP-Me,3De-20814e,CJHB,2E,32,,0,-30.665,2019-07-19T00:00:00Z,9999-01-01T00:00:00Z",
              	"CSI,CUSP-Me,CUSP-Me,3De-20815e,CJHB,2F,32,,0,-42.395,2019-07-19T00:00:00Z,9999-01-01T00:00:00Z",
            + 	"CSI,CUSP-Me,CUSP-Me,3De20703,TRAB,24,278,,0,0,2016-07-24T01:00:00Z,9999-01-01T00:00:00Z",
            + 	"CSI,CUSP-Me,CUSP-Me,3De20704,TRAB,26,278,,0,0,2016-07-24T01:00:00Z,9999-01-01T00:00:00Z",
            + 	"CSI,CUSP-Me,CUSP-Me,3De20705,TRAB,28,278,,0,0,2016-07-24T01:00:00Z,2021-05-19T00:00:00Z",
              	"CSI,CUSP-Me,CUSP-Me,3De20708,CBLB,2G,32,,0,0,2016-08-28T12:00:00Z,9999-01-01T00:00:00Z",
            + 	"CSI,CUSP-Me,CUSP-Me,3De20709,TRAB,28,278,,0,0,2021-05-19T01:00:00Z,9999-01-01T00:00:00Z",
              	"CSI,CUSP-Me,CUSP-Me,3De20875,CJHB,2G,32,,0,0.35,2019-07-19T00:00:00Z,9999-01-01T00:00:00Z",
              	"CSI,CUSP-Me,CUSP-Me,3De20909,CBLB,21,32,,0,3.58,2016-08-28T12:00:00Z,9999-01-01T00:00:00Z",
```

**Comment by mnaguit** [comment]
Will try that suggestion. Thanks @CBurton90

**Comment by mnaguit** [comment]
Yahoo. Finally. I can have my super delayed lunch now. =)
Thank you @CBurton90 & @salichon 👍 👍

**Review by salichon — APPROVED** [review]

**Review by CBurton90 — APPROVED** [review]

**Pull request merged**
