### PR TITLE
CTZ sensor & logger/s swap

### PR DESCRIPTION
**Pull request by mnaguit**
_From_: Q330HR/6 (SN2258) & STS-2 (SN60732)
_To_:      Centaur (SN7969) + Obsidian 4X (SN373) and Trillium Horizon (SN809)

at LC 10 & LC 20
for HH(ENZ) & HN(ENZ) continuous streams 

Firmware version 4.5.20 for Centaur

### CODE REVIEW

**Comment by mnaguit** [comment]
Hello @ozym @CBurton90 @salichon 

Travis says there is a place overlap for the Obsidian datalogger. Was it because of the two entries for the same logger (Kokohu --already closed + Wharekauri --newly opened) or two loggers at the same site (Obsidian + Centaur)? 

Any idea/s how to resolve Travis? Thanks

**Review by salichon — COMMENTED** [review]
- Sensor Orientaiotn to be confirmed 
- first HN continuous 2020.047 `2020.02.16 at 00:00:00` is more relevant in  streams.csv`CTZ,20,200,false,false,true,2007-12-15T07:00:00Z,2021-11-23T03:00:00Z
CTZ,20,200,false,false,false,2021-11-24T19:37:00Z,9999-01-01T00:00:00`

**Comment by salichon** [comment]
`Kinemetrics,Obsidian 4X Datalogger,373,Wharekauri,,2021-11-24T19:37:00Z,9999-01-01T00:00:00Z`
 Should be most likely  : 
  `Kinemetrics,Obsidian 4X Datalogger,373,Wharekauri,strong motion,2021-11-24T19:37:00Z,9999-01-01T00:00:00Z`
  as the other ones 
the technical explanation to be checked with @ozym

**Comment by mnaguit** [comment]
> @mnaguit `Kinemetrics,Obsidian 4X Datalogger,373,Wharekauri,,2021-11-24T19:37:00Z,9999-01-01T00:00:00Z` Should be most likely : `Kinemetrics,Obsidian 4X Datalogger,373,Wharekauri,strong motion,2021-11-24T19:37:00Z,9999-01-01T00:00:00Z` as the other ones the technical explanation to be checked with @ozym

Thanks @salichon 
I think that's my first entry...but Travis still is not happy

**Review by salichon — CHANGES_REQUESTED** [review]
You can t have a sensor opened  without a datalogger I reckon 

> kinemetrics Inc. | FBA-ES-T | 1438 | CTZ | 20 | 0 |   | 0 | 0 | 0 | 0 | 0 | 0 | 2008-11-25T02:01:00Z | 9999-01-01T00:00:00Z


tml>

**Comment by ozym** [comment]
In the dataloggers table (csv) you can't have two dataloggers at the same place with the same role. The role is usually empty, but in this case you could use "Broadband" and "Strong Motion" say. These need to match values in connections (csv).

**Comment by mnaguit** [comment]
> In the dataloggers table (csv) you can't have two dataloggers at the same place with the same role. The role is usually empty, but in this case you could use "Broadband" and "Strong Motion" say. These need to match values in connections (csv).

Yahoo!! Travis is now happy :)
Thanks @ozym 👍 👍

**Review by salichon — APPROVED** [review]
great!

**Comment by mnaguit** [comment]
Hi guys @ozym @CBurton90  
Are you happy with this PR?

**Review by CBurton90 — APPROVED** [review]

**Review by ozym — APPROVED** [review]

**Comment by mnaguit** [comment]
Thanks @salichon @CBurton90 @ozym 
Now ready to 'squash & merge' this PR =)

**Pull request merged**
