### PR TITLE
GORS LC change

### PR DESCRIPTION
**Pull request by mnaguit**
use same recorder (CUSP3D SN 42222), close LC 20 and open LC 21

### CODE REVIEW

**Comment by CBurton90** [comment]
Converting the internal gps receiver coords of the CUSP to decimal degrees gives the below, so as long as these agree with @timjmcdougall all good. 
```
168.940961111 | -46.102655556
```
I would have though the height should have been closer to the previous location (85m), the internal gps of the CUSP ranges between 70/80m due to accuracy, although 57m could have been measured at some point

**Comment by mnaguit** [comment]
Kindly let me know which would be the final coordinates and elevation, so that I can update this PR accordingly. Thanks.
@CBurton90 @timjmcdougall

**Comment by timjmcdougall** [comment]
Go with Conrads @mnaguit mine were from a phone GPS so could be a bit out.

**Comment by mnaguit** [comment]
I already updated the coordinates and elevation (use 70) as per @CBurton90 suggestion.

**Review by CBurton90 — APPROVED** [review]
Looks good! Cheers.

**Review by salichon — APPROVED** [review]

**Comment by mnaguit** [comment]
Hi @ozym 
I was about to merge this PR after being reviewed, however I encounter this error with Travis:
`The command "curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.18.0" failed and exited with 1 during .`

Any idea would be much appreciated. Thank you.

**Pull request merged**
