### PR TITLE
BOWS -  new EQR120 recorder CUSP 

### PR DESCRIPTION
**Pull request by salichon**
- EQR120  tags the datalogger and the sensor
- First real life deploy of new CSI
- will validate future ones

- Please check the azimuth of the components - ;) ta!

### CODE REVIEW

**Review by CBurton90 — CHANGES_REQUESTED** [review]
I thought the orientation with respect to Y was 9 deg for the EQR120? 280 may indeed be correct for the old CUSP but as the sensor may have been housed with a 90deg offset (see the ticket) : )

**Review by mnaguit — CHANGES_REQUESTED** [review]
Thanks @salichon .
While the orientation is getting sorted, in streams.csv --should it be that another entry is introduced to separate the triggered 200hz from the continuous 200hz?

**Comment by salichon** [comment]
Orientation  Change made @mnaguit @CBurton90

**Comment by salichon** [comment]
@mnaguit once travis is done would you review this a last time
thanks!

**Review by mnaguit — APPROVED** [review]
Many thanks @salichon . 👍

**Pull request merged**
