### PR TITLE
update manufacturer (Make) General Electric

### PR DESCRIPTION
**Pull request by elidana**
another manufacturer update

@ozym , not 100% sure what "GESystems" was used for and if the update here is correct

### CODE REVIEW

**Review by ozym — COMMENTED** [review]
again, maybe the Sensor needs to remove Druck now (as it's in the Make name now).

**Comment by elidana** [comment]
thanks @ozym ! will update sensor name accordingly

**Comment by CBurton90** [comment]
@elidana @ozym What about just:

`General Electric,Druck PTX-1830,10236617,,`

**Comment by elidana** [comment]
please just suggest a preferred name and I'll update accordingly!

**Comment by ozym** [comment]
Only comment is around the use of Description, i.e. it will be made up of Maker + Model so should go together without duplicate parts (e.g.   GE Druck  Druck PX-...).

**Comment by elidana** [comment]
cool, that helps. didn't realised that Description was going to be composed by Make+Model.

Will go with @CBurton90 suggestion then...update in the making :)

**Comment by elidana** [comment]
done. @ozym or @CBurton90 , can I have another (hopefully short) round of review on this one please?

**Review by CBurton90 — APPROVED** [review]

**Review by ozym — APPROVED** [review]

**Pull request merged**
