### PR TITLE
MBAZ sensor install

### PR DESCRIPTION
**Pull request by Thomas-Benson**
- Installing Trillium Compact 120PH-2 (9284) at new location 11
- Sensor orientation N (0), depth 0.5m
- Location 11 coordinates same as location 10
- Set connections as channels 0-2 for loc 10, 3-5 for loc 11

### CODE REVIEW

**Review by mnaguit — DISMISSED** [review]
Looks good @Thomas-Benson , it may not really matter but probably tweaking the coordinates of `LC 11` to distinguish from `LC 10` is good? what do you think?

**Comment by Thomas-Benson** [comment]
@mnaguit No problem, any suggestions for updated coordinates?

**Comment by mnaguit** [comment]
@Thomas-Benson `-36.7688,174.8979`

**Review by CBurton90 — APPROVED** [review]

**Comment by Thomas-Benson** [comment]
Coordinates updated

**Review by mnaguit — APPROVED** [review]
👍

**Review by CBurton90 — APPROVED** [review]

**Pull request merged**
