### PR TITLE
Add information for a new GNSS site - TGHM

### PR DESCRIPTION
**Pull request by aleks-spes**
Add information for a new GNSS site on the Horomatangi Reef platform - TGHM

### CODE REVIEW

**Comment by elidana** [comment]
thanks @aleks-spes ! just ping me again when ready to review :)

**Review by CBurton90 — DISMISSED** [review]
Looks good (once @jacksonshanks confirms it was the same antenna used, which I'm pretty sure it was).

**Comment by jacksonshanks** [comment]
@elidana @CBurton90 can confirm that the same zephyr was used. 

upgrade incoming next month

**Comment by jacksonshanks** [comment]
@aleks-spes ^^

**Comment by aleks-spes** [comment]
Hey @elidana !
Could you please have a look at the PR? It is ready for review.

**Comment by jacksonshanks** [comment]
@aleks-spes thanks, will this allow the data to be seen by the volcano monitoring group they were askign about the site this morning.

**Review by elidana — CHANGES_REQUESTED** [review]
Hi @aleks-spes , this looks good but closing time of TGHO (as well as equipment uninstall) need to match.

When is the last data from TGHO? We can use that as closing timestamp in the `install` folder, and end of that same day as closing time in `network` folder

**Comment by aleks-spes** [comment]
Thanks @elidana ! In this case, I will wait for the old receiver with the latest data to check the exact timestamp.
Hopefully will update it tomorrow.

**Comment by aleks-spes** [comment]
Hey @jacksonshanks!
Yes, after merging the data will be available in the archive very soon. But I need to get the old receiver first.

**Comment by elidana** [comment]
thanks @aleks-spes ! Sounds good. We can also use an indicative date (and then refine closing timestamps) if @jacksonshanks can confirm the receiver was undeployed on the same day TGHM was built.
In that case, we can use for everything the second before TGHM started recording, and tidy up things later on

**Comment by aleks-spes** [comment]
Hey @elidana !
Could you please have a look at the Travis output because I can't understand what is a problem. Travis is saying there are an identical lines in the visibility.csv, but I can't see this in the file.

**Review by elidana — DISMISSED** [review]
looks good! thanks heaps @aleks-spes !

**Review by elidana — DISMISSED** [review]
nice!

**Review by elidana — APPROVED** [review]

**Pull request merged**
