### PR TITLE
add geomag APIM metadata into delta

### PR DESCRIPTION
**Pull request by elidana**
add APIM (Apia) geomag metadata.

For the sensor calibration, I have not used the -38000 absolute correction used for geomag stations installed in Antarctica.
Is that correct?

### CODE REVIEW

**Review by merijnthornton — APPROVED** [review]
Looks good to me.

**Comment by elidana** [comment]
thanks for reviewing @merijnthornton ! Let me know if you would like me to produce the stationXML response file to have a look at the results

**Review by merijnthornton — COMMENTED** [review]
The observatory grade proton is a gsm-90. Gsm-19 magnetometers are used in the absolutes hut, but are not part of the network. We may want to differentiate between gsm-90 and gsm-90F. The F indicates fast sampling (1sec). The non F model has been used in the past (5 sec sampling).

**Comment by merijnthornton** [comment]
Hi Elisabetta, 

Thats correct, the Z Bias switch is just for higher latitudes:

Since the adjustable BIAS-circuit compensates the magnetic field components in 255 steps of 150 nT, it is
necessary to add a fixed bias (38000 nT) at higher fields like the Z-field at mid and high latitude.
This is done using the two switches on the circuit board (one for X and one for Z)
At high latitude (Z>38000) the Z-switch must be ON.
At lower latitude (Z<38000) the Z-switch must be OFF.

**Comment by elidana** [comment]
message from @merijnthornton :
The proton was replaced in Apia (~8 May 2019). Old GSM90F1 was   8012579)

**Comment by elidana** [comment]
@merijnthornton , all metadata should now be correctly included here (I hope!)

can you please have another look?

**Review by ozym — COMMENTED** [review]
not sure this is the right model for apia Q330S/6

**Comment by elidana** [comment]
thanks @ozym ! I was just about to update that bit.
I have two serial numbers for the two q330 installs: 3869 and 3781
would the model be Q330/6 then?

**Comment by elidana** [comment]
that's the only pic I could find 
image
(from 2022)

**Comment by elidana** [comment]
changed datalogger model to be Q330/6 and added the two install that I know about

**Review by tanjapetersen — DISMISSED** [review]
looks good to me

**Comment by elidana** [comment]
@tanjapetersen , this one had some conflicts to resolve once the SBAM pr was merged.
Can i please have another quick approval from you so that I can merge?

@ozym , hope that's ok for you but please if something looks odd let me know !

**Review by tanjapetersen — APPROVED** [review]

**Pull request merged**
