### PR TITLE
WHSZ recorder swap

### PR DESCRIPTION
**Pull request by mnaguit**
- from Basalt 494 to TitanSMA 001713
- for LC20 with HN(ENZ) streams
- TitanSMA firmware version: 4.5.22

### CODE REVIEW

**Comment by mnaguit** [comment]
@moorematthew Happy to update the firmware version, as needed. Just let me know. 😃

**Review by salichon — DISMISSED** [review]
yup

**Comment by mnaguit** [comment]
Are you happy with this PR Sir @moorematthew ? 😃

**Comment by moorematthew** [comment]
@mnaguit apologies this sensor was mistakenly installed with the older firmware 4.3.28 so that will need to be amended. We will look at upgrading this when we get a chance and will let you know once it has been changed

**Review by moorematthew — CHANGES_REQUESTED** [review]
Firmware change to 4.3.28 please

**Comment by mnaguit** [comment]
Firmware version edited. 
Another round of review gentlemen? Thanks!
@moorematthew @salichon

**Comment by mnaguit** [comment]
Thank you Sir @salichon 👍

**Review by moorematthew — APPROVED** [review]
Can't believe how efficient @salichon is today. Good work!

**Pull request merged**
