### PR TITLE
EpiSensor+Centau CTR Auto.go script output from PR#1132

### PR DESCRIPTION
**Pull request by salichon**
Go Script output for new combo 
Bound to https://github.com/GeoNet/delta/pull/1132

### CODE REVIEW

**Review by CBurton90 — COMMENTED** [review]
Hmm it this entry behaving as though it is a strong motion recorder?

Tried to hunt down a Quanterra datalogger Connected to Strong Motion Sensor (so I can compare Q330 to FBA-ES-T) but I cant see an entry as such for that either.

**Comment by salichon** [comment]
@CBurton90 i ll go through the stationxml creation to check that the full response is created.
thanks for pointing this :)

**Comment by ozym** [comment]
That doesn't look right, I'd say the original yaml files are bad.

**Review by ozym — CHANGES_REQUESTED** [review]
need to fix underlying yaml problems first.

**Comment by CBurton90** [comment]
yaml file fixed in the other PR, may need to run this again @salichon

**Comment by salichon** [comment]
@ozym @CBurton90  auto.go (re) generated as per #1132 PR corrections

- stationxml  generated  OK --> BSWZ  has FBA Sensor coupled with CTR4-6S (checked on HNZ
 20) 
 this is looking good (to me ; - you ll have the last word )

**Review by ozym — APPROVED** [review]

**Review by CBurton90 — APPROVED** [review]
yup looks legit!

**Pull request merged**
