### PR TITLE
GLOS strong motion  components are ENZ

### PR DESCRIPTION
**Pull request by salichon**
streams csv --> GLOS components are ENZ

### CODE REVIEW

**Review by mnaguit — COMMENTED** [review]
Hi @salichon .
Should we wait first for the archive correction before we modify the metadata?

**Comment by salichon** [comment]
nahh  i d prefrer 
first the delta fix 
correcting the archive may take  aaaaaages :) 
and 
so far the response for GLOS is unavalaible on FDSN so   .... first things first 
@mnaguit

**Comment by mnaguit** [comment]
Noted Sir Jerome. I'll approve this PR then.

**Review by mnaguit — APPROVED** [review]
Archive correction for data will follow.

**Pull request merged**
