### PR TITLE
feat: bnc skeleton files format change

### PR DESCRIPTION
**Pull request by junghao**
As requested in https://github.com/GeoNet/tickets/issues/16984.

File `testdata/AVLN00NZL.SKL`, `testdata/WGTN00ZNL.SKL`, and `testdata/AVLN-generic.SKL` are output examples.

### CODE REVIEW

**Comment by junghao** [comment]
@aleks-spes Could you please verify  example output files in this PR (AVLN00NZL.SKL, WGTN00NZL.SKL, and AVLN-generic.SKL)? Thanks.

**Review by aleks-spes — DISMISSED** [review]
SKL files look good.

**Review by wilsonjord — APPROVED** [review]
Surely there's some sort of templating that can help here, all these string literals seem kinda brittle.

**Review by wilsonjord — APPROVED** [review]

**Comment by jajera** [comment]
SKL files updated

production

```bash
[johna@avdas11 ~]$ sudo ls /var/lib/containers/storage/volumes/bnc-volume/_data/bnc/rnx/ -la | grep SKL
-rw-r--r--+ 1 root root    1981 Nov  5 14:53 240600NZL.SKL
-rw-r--r--+ 1 root root    1981 Nov  5 14:53 ARTA00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:53 AUCK00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:53 AUKT00NZL.SKL
-rw-r--r--+ 1 root root    1981 Nov  5 14:53 AVLN00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:53 BLUF00NZL.SKL
-rw-r--r--+ 1 root root    1981 Nov  5 14:53 BTHL00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:53 CHTI00NZL.SKL
-rw-r--r--+ 1 root root    1981 Nov  5 14:53 CLRR00NZL.SKL
-rw-r--r--+ 1 root root    1981 Nov  5 14:53 CMBL00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:53 CORM00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:53 DNVK00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:53 DUND00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:53 DUNT00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:53 GISB00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:53 GLDB00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:53 HAAS00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:53 HAMT00NZL.SKL
-rw-r--r--+ 1 root root    1981 Nov  5 14:53 HANM00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:53 HAST00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:53 HIKB00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:53 HOKI00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:53 KAIK00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:53 KTIA00NZL.SKL
-rw-r--r--+ 1 root root    1981 Nov  5 14:53 LEVN00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:53 LEXA00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:53 LKTA00NZL.SKL
-rw-r--r--+ 1 root root    2049 Nov  5 14:53 LY2T00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:53 MAHO00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:53 MAVL00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:53 METH00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:53 MQZG00NZL.SKL
-rw-r--r--+ 1 root root    1981 Nov  5 14:53 MRBL00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:53 MTJO00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:53 NLSN00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:53 NPLY00NZL.SKL
-rw-r--r--+ 1 root root    2049 Nov  5 14:53 NSFT00NZL.SKL
-rw-r--r--+ 1 root root    2055 Nov  5 14:53 PAEK00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:53 PYGR00NZL.SKL
-rw-r--r--+ 1 root root    1981 Nov  5 14:53 RGAR00NZL.SKL
-rw-r--r--+ 1 root root    1981 Nov  5 14:53 RGUT00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:53 SCTB00ATA.SKL
-rw-r--r--+ 1 root root    2049 Nov  5 14:53 SSFT00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:53 TAUP00NZL.SKL
-rw-r--r--+ 1 root root    1981 Nov  5 14:53 TKHL00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:53 TRNG00NZL.SKL
-rw-r--r--+ 1 root root    1981 Nov  5 14:53 TRWH00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:53 VGMT00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:53 WAIM00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:53 WANG00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:53 WARK00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:53 WEST00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:53 WGTN00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:53 WGTT00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:53 WHKT00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:53 WHNG00NZL.SKL
-rw-r--r--+ 1 root root    1981 Nov  5 14:53 WRAU00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:53 WRPA00NZL.SKL
-rw-r--r--+ 1 root root    1981 Nov  5 14:53 YALD00NZL.SKL
```

staging

```bash
[johna@kpdas11 ~]$ sudo ls /var/lib/containers/storage/volumes/bnc-volume/_data/bnc/rnx/ -la | grep SKL
[sudo] password for johna:
-rw-r--r--+ 1 root root    1981 Nov  5 14:55 240600NZL.SKL
-rw-r--r--+ 1 root root    1981 Nov  5 14:55 ARTA00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:55 AUCK00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:55 AUKT00NZL.SKL
-rw-r--r--+ 1 root root    1981 Nov  5 14:55 AVLN00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:55 BLUF00NZL.SKL
-rw-r--r--+ 1 root root    1981 Nov  5 14:55 BTHL00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:55 CHTI00NZL.SKL
-rw-r--r--+ 1 root root    1981 Nov  5 14:55 CLRR00NZL.SKL
-rw-r--r--+ 1 root root    1981 Nov  5 14:55 CMBL00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:55 CORM00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:55 DNVK00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:55 DUND00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:55 DUNT00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:55 GISB00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:55 GLDB00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:55 HAAS00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:55 HAMT00NZL.SKL
-rw-r--r--+ 1 root root    1981 Nov  5 14:55 HANM00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:55 HAST00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:55 HIKB00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:55 HOKI00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:55 KAIK00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:55 KTIA00NZL.SKL
-rw-r--r--+ 1 root root    1981 Nov  5 14:55 LEVN00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:55 LEXA00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:55 LKTA00NZL.SKL
-rw-r--r--+ 1 root root    2049 Nov  5 14:55 LY2T00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:55 MAHO00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:55 MAVL00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:55 METH00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:55 MQZG00NZL.SKL
-rw-r--r--+ 1 root root    1981 Nov  5 14:55 MRBL00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:55 MTJO00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:55 NLSN00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:55 NPLY00NZL.SKL
-rw-r--r--+ 1 root root    2055 Nov  5 14:55 PAEK00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:55 PYGR00NZL.SKL
-rw-r--r--+ 1 root root    1981 Nov  5 14:55 RGAR00NZL.SKL
-rw-r--r--+ 1 root root    1981 Nov  5 14:55 RGUT00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:55 SCTB00ATA.SKL
-rw-r--r--+ 1 root root    2211 Sep 16 09:45 SCTB00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:55 TAUP00NZL.SKL
-rw-r--r--+ 1 root root    1981 Nov  5 14:55 TKHL00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:55 TRNG00NZL.SKL
-rw-r--r--+ 1 root root    1981 Nov  5 14:55 TRWH00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:55 VGMT00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:55 WAIM00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:55 WANG00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:55 WARK00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:55 WEST00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:55 WGTN00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:55 WGTT00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:55 WHKT00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:55 WHNG00NZL.SKL
-rw-r--r--+ 1 root root    1981 Nov  5 14:55 WRAU00NZL.SKL
-rw-r--r--+ 1 root root    2123 Nov  5 14:55 WRPA00NZL.SKL
-rw-r--r--+ 1 root root    1981 Nov  5 14:55 YALD00NZL.SKL
```

**Pull request merged**
