### PR TITLE
Update cameras.csv

### PR DESCRIPTION
**Pull request by Camasher**

### CODE REVIEW

**Comment by Camasher** [comment]
May have issues with the camera install times equalling the view opening times, may need to add one second on the the view times

**Comment by ozym** [comment]
```
consistency_test.go:18: unable to load list file ../install/cameras.csv: parsing time "9999-01-1T00:00:00Z" as "2006-01-02T15:04:05Z": cannot parse "1T00:00:00Z"
```

**Comment by Camasher** [comment]
I forgot a zero on the 9999 time. Seems to be fixed now.

**Comment by ozym** [comment]
This needs a bit more of a description,  from this I see that (a) the camera was upgraded, and (b) it was repointed back to where it was viewing between 2012 and 2017.

**Comment by Camasher** [comment]
@ozym this is a tidyup from https://github.com/GeoNet/tickets/issues/7734 in which the delta/network/views.csv was updated, but the delta/installs/cameras.csv wasn't.

New M16 was installed to replace aging M12. The view of the new camera matched that of view KAKA.01, so this view was reoccupied.

**Review by rumachan — DISMISSED** [review]

**Comment by staylorofford** [comment]
Had to correct conflicts from a PR I merged elsewhere. @rumachan can you please review again then we can merge if all is well.

**Review by staylorofford — APPROVED** [review]
No difference to what @rumachan approved before

**Pull request merged**
