### PR TITLE
Dart Deploy meta update

### PR DESCRIPTION
**Pull request by salichon**
DRAFT PR 
Match the data service to deliver meters from ~2years deployment
Continuous data set (raw=Pressure) to be converted into meters
- Removed commit  ~Gain is to convert Psia pressure to Meters  (from a miniseed  Pressure source)~ 
- Sort end 2021 NZA,NZC,NZE  recovered deployments 40  Observations Start/Stop  

Attempt to check if it fits for purposes.

### CODE REVIEW

**Comment by ozym** [comment]
I'll leave @meganmadley to look at the dates, i'll kick in with the response details in a follow up PR.

**Comment by meganmadley** [comment]
Thanks @ozym, @salichon where are you getting these new date values from/why the change?

**Comment by salichon** [comment]
hello @meganmadley :) 
 from the BPR raw miniseed as in https://github.com/GeoNet/tickets/issues/10134#issuecomment-1042411515

**Comment by salichon** [comment]
> `Data starts 21 Dec 2019 at 17:00 ends 17 Dec 2021 at 00:59`
> Do we want NZA to close at `2021-12-17T00:59:00Z` instead of `2021-12-17T01:00:00Z`

Hello @meganmadley 
sorry ha, 
 i did not put the seconds ( that are shown in the listing). 
 The miniseed data is ending/cut at `00:59:45` 
So 2021-12-17T01:00:00Z is kinda legit  to me ;) - 
unless  i put the exact end  to the second.

**Review by meganmadley — APPROVED** [review]
LGTM then, thanks for the explanation @salichon

**Pull request merged**
