### PR TITLE
Adding Firmware upgrades for Tuesday 18

### PR DESCRIPTION
**Pull request by meganmadley**
PAWA - 5944R40038 - 2022-10-17T19:36:21

### CODE REVIEW

**Comment by meganmadley** [comment]
RCHD - 5921R40118 - 2022-10-17T20:28:05

**Comment by aleks-spes** [comment]
RAUL - 5946R40017 - 2022-10-17T20:39:52

**Comment by meganmadley** [comment]
WAHU - 5946R40027 - 2022-10-17T21:27:25

**Comment by aleks-spes** [comment]
TRAV - 5940R40044 - 2022-10-17T21:31:26

**Comment by aleks-spes** [comment]
WHVR - 5940R40053 - 2022-10-17T22:31:17

**Review by aleks-spes — APPROVED** [review]
Everything looks good!

**Comment by meganmadley** [comment]
@aleks-spes, LGTM!

**Pull request merged**
