### PR TITLE
KHZ sensor-logger-recorder swap

### PR DESCRIPTION
**Pull request by mnaguit**
I incorporated all changes for this station in one PR, as follows:
_Sensor_:   From STS-2 SN 120955 to TH120-1 Horizon 803 (for LC 10)
_Logger_:  From Q330HR/6 SN 4004 to Centaur SN 8002 (for LC 10)
_Recorder_: from FBA-ES-T 1436 to TitanSMA 001256 (from LC 20 to LC 21)

For firmwave: Centaur version 4.5.20

### CODE REVIEW

**Review by salichon — APPROVED** [review]
The strong m otion looks good and the Weak motion  too ;))

@mnaguit I leave you deciding perhaps for the sake of the LN  channel (strong 1 Hz),  closing them by the date of 15/06/2020 ~10h00 when the configuration/collection stopped 
(LN are not eallly useful  so far)

**Review by CBurton90 — COMMENTED** [review]
`KHZ,20,Kahutara,,2003-08-06T00:00:00Z,2021-05-27T02:03:00Z`

Should connections.csv be 21? Or does that not matter?

**Review by CBurton90 — APPROVED** [review]

**Comment by CBurton90** [comment]
connections only needed for sensor to datalogger silly me

**Comment by mnaguit** [comment]
Hi @ozym .
Are you happy with these changes for KHZ? Thanks.

**Review by ozym — APPROVED** [review]

**Comment by mnaguit** [comment]
Many thanks @ozym @CBurton90 @salichon

**Pull request merged**
