### PR TITLE
Trillium 360 and Centaur combination

### PR DESCRIPTION
**Pull request by CBurton90**

### CODE REVIEW

**Review by ozym — APPROVED** [review]
Looks good from what I can see.

**Comment by CBurton90** [comment]
@ozym @salichon please merge when your happy (I cant)

**Review by salichon — COMMENTED** [review]
This is lokking goog, though question 
Are we doing `ZNE` component only with the Trillium 360 ? 
Is it taken care of later  on ?

**Comment by ozym** [comment]
@salichon the ZNE part is a little misleading, what's really saying is the channels that would notionally be Z N E are in that order (the downstream code will map Z 1 2 to Z N E and then do the response lookup).

This is indicate things like the strong motion which might be  XYZ  or ENZ etc.  (possibly could have used 012 but that may be even more confusing).

**Review by salichon — APPROVED** [review]

**Pull request merged**
