### PR TITLE
Update install file FOXLRDLP.csv

### PR DESCRIPTION
**Pull request by jacksonshanks**

### CODE REVIEW

**Review by rumachan — CHANGES_REQUESTED** [review]
Sorry this has taken so long.
There are some small differences in start time between SIT repo and these values. I assume they are not significant but noted here so you can check
- install/dataloggers.csv FOXRB 2021-08-04 vs 2021-08-03
- install/sensors.csv Sisgeo FOXVF 2021-11-24 vs 2021-11-22
- install/sensors.csv Visala FOXKP 2021-08-04 vs 2021-08-03, FOXRB 2021-11-24 vs 2021-08-03, FOXVF 2021-11-24 vs 2021-11-21

install/sensors.csv Hyquest FOXKP and FOXVV, install time overlaps pull out time (they are exactly the same). Move one of them by one second so no overlap

Your errors.
Unable to find sensor asset caused by Hyquest TB3 0.2 mm #21-31 and #21-33 not being in assets/sensors.csv find. Need to add
Unbale to find sites for station. ??? no idea what caused this.

**Comment by jacksonshanks** [comment]
for review @rumachan 

https://github.com/GeoNet/sit/pull/3569 
https://github.com/GeoNet/delta/pull/1443

**Review by rumachan — COMMENTED** [review]
This failed automatic checks and I can't see what the problem is. Failure is listed at https://app.travis-ci.com/github/GeoNet/delta/builds/255426403

No matter what my review, this can't be merged while it's failing checks. My solution to failed checks is to always run checks locally after each part of the change before creating the PR. Then it's not a matter of trying to find what causes the failure among several changes you've made. Can you do that?

**Comment by jacksonshanks** [comment]
@rumachan yipo i can do that this week

**Comment by rumachan** [comment]
Yes, please send me an invite and we'll make it happen

**Pull request closed without merging**
