### PR TITLE
MQZ change in location code

### PR DESCRIPTION
**Pull request by mnaguit**
from LC 20 to 21

### CODE REVIEW

**Comment by mnaguit** [comment]
Hi @samgeonet 
Kindly let me know if you would like to update '_sites.csv_' by changing the 'unknown' entry into something more apt with the way the new coordinates were derived. Thanks.

**Comment by samgeonet** [comment]
It will be internal gps clock

**Comment by mnaguit** [comment]
Revision made @samgeonet 
Waiting for review from 3 teams. Thanks.

**Comment by mnaguit** [comment]
HI @salichon @jristau & @brianf3rris 
Can anyone please review this? Thanks.

**Comment by mnaguit** [comment]
Hi @salichon @jristau & @brianf3rris . Waiting for your review on this. Thanks.

**Pull request merged**
