### PR TITLE
add geomag sensors metadata in delta

### PR DESCRIPTION
**Pull request by elidana**
this is a draft pull request to finalize the addition of all sensor metadata in delta, currently excluding "gains and bias" factors, that will be added in a second phase.

Still need to complete the following:
- [x] AHAM info in `network/stations.csv` (coordinates, confirm name)
- [x] add/check recorders (proton) make, model and serial numbers in `install/recorders.csv` (all except EYWM)
- [x] add/check sensors (fluxgate) make, model and serial numbers in `install/seonsors.csv` (all except EYWM)
- [x] add/check dataloggers make, model and serial numbers in `install/dataloggers.csv` (all except EYWM)
- [x] add calibration files for missing fluxgates in `calibrations/fluxgate/` folder
- [ ] add all SMHS info
- [x] think a way to add fluxgate drivers metadata
- - [x] EYWM driver `S0308, 3/12/2013 0500 UTC`
- - [x] SBAM driver `E0299, 15/01/2006` 
- - [x] AHAM driver, `E0564, 2022-03-19`
- - [x] APIM driver, `E0397, 23/11/2011`
- [x] do we need to add all equipment to assets as well?

### CODE REVIEW

**Comment by ozym** [comment]
see https://github.com/GeoNet/delta/pull/1662 for a rebuilt example.

**Comment by elidana** [comment]
this one will be split into individual pr by station, more manageable, and closed once this is done.

Fluxgate calibration pr: https://github.com/GeoNet/delta/pull/1674

**Comment by elidana** [comment]
AHAM: https://github.com/GeoNet/delta/pull/1675

**Comment by elidana** [comment]
SMHS: https://github.com/GeoNet/delta/pull/1747, https://github.com/GeoNet/delta/pull/2046

all captured, closing this one as it is now obsolete

**Pull request closed without merging**
