### PR TITLE
add horizon 120

### PR DESCRIPTION
**Pull request by ozym**
Makes the assumption that the horizon assets will be called "Trillium Horizon TH120-1"

A first go, need to check the sensor values agree with what the centaur says ...

### CODE REVIEW

**Review by CBurton90 — DISMISSED** [review]
Looks good, I will add the stationXML directly from the box to the sub-ticket for Horizon metadata.

**Comment by ozym** [comment]
@CBurton90 just a rebase as the previous merge injected a conflict.

**Review by CBurton90 — APPROVED** [review]

**Review by salichon — COMMENTED** [review]
Hi there in order to "Clarify" the nanometrics sensor types:
image removed)
  - ~What is the serial of our Horizon model?~  Likely does not apply -  looks related to the Trillium 120 only (not the "Horizon120")

- From IRIS (nrl) (http://ds.iris.edu/NRL/sensors/nanometrics/nanometrics_trillium_sensors.htm)
 the Horizon "comments" related to the sensor response that  we are choosing   are shown as such `TH120-2,TH120-2-XC,TH120-2-M,T120-SPH2,T120-SPH2-XC`
 
    - We are labelling the Sensor in delta  as `... TH120-1`     (as shown by Mark s evidence (on the sensor...)  
     ..and check as commented that we are good as

**Review by salichon — COMMENTED** [review]
@ozym 
the inspection of the Ps and Zs of the Sensor built-in "stationxml" 
shown
 ```
<Zero>
<Real>-350.0</Real>
```

in place of (-340) Line 132 (resp/responses/sensors/nanometrics.yaml

shall we stck to the in-built info ?

**Comment by CBurton90** [comment]
> Hi there in order to "Clarify" the nanometrics sensor types:
> _(image removed)_
> 
> * ~What is the serial of our Horizon model?~  _Likely does not apply -  looks related to the Trillium 120 only (not the "Horizon120").._
> * From IRIS (nrl) (http://ds.iris.edu/NRL/sensors/nanometrics/nanometrics_trillium_sensors.htm)
>   the Horizon "comments" related to the sensor response that  we are choosing   are shown as such `TH120-2,TH120-2-XC,TH120-2-M,T120-SPH2,T120-SPH2-XC`
>   
>   * We are labelling the Sensor in delta  as `... TH120-1`     (as shown by Mark s evidence (on the sensor...)
>     ..and check as commented that we are good as

@salichon 

http://ds.iris.edu/NRL/sensors/nanometrics/RESP.XX.NS690..BHZ.TrilliumHorizon120.120.1203

Will be the most comparable RESP file available from IRIS.

**Comment by ozym** [comment]
@salichon switched -340 to -350.

**Review by salichon — APPROVED** [review]

**Review by CBurton90 — DISMISSED** [review]

**Comment by CBurton90** [comment]
Another nice check for our sanity 

image

**Comment by ozym** [comment]
@salichon @CBurton90 could you have another look at the FIR filters.

**Review by CBurton90 — APPROVED** [review]
I have checked the top 10 and bottom 10 values for each filter stage (for all 100Hz,10Hz, and 1Hz) and they match exactly as per directly from the StationXML off the box. Good stuff @ozym I'm not sure how your eyes survive 🤣

**Review by salichon — APPROVED** [review]
cool i had a look at the filters used "in the box" yesterday
naming of the filters makes sense

**Pull request merged**
