### PR TITLE
NRRD NetR9 swap

### PR DESCRIPTION
**Pull request by staylorofford**

### CODE REVIEW

**Comment by samgeonet** [comment]
Good point I will get Brendon to add the details of the antenna to the change ticket

**Comment by samgeonet** [comment]
@staylorofford antenna details are in the change ticket now

**Comment by staylorofford** [comment]
updated

**Comment by elidana** [comment]
looks good, antenna sn. verified against Dropbox photo, receiver sn. and timestamp verified on receiver web interface

**Pull request merged**
