### PR TITLE
GNSS site 2004 information

### PR DESCRIPTION
**Pull request by aleks-spes**
Hey @meganmadley! Could you please review it?

### CODE REVIEW

**Review by meganmadley — COMMENTED** [review]
Might need the asset/antennas file?

**Comment by meganmadley** [comment]
Also where did you get the start date of the site from? This one `2000-06-19T00:00:00Z`

**Comment by aleks-spes** [comment]
I got this from the first official coordinates for this site: https://www.geodesy.linz.govt.nz/gdb/index.cgi?mode=gmap&nextform=histcrd&code=2004&sessionid=101605488236031666753078&histcoordsys=NZGD2000

**Comment by meganmadley** [comment]
Perfect, @aleks-spes that date looks good to me!

**Review by meganmadley — APPROVED** [review]
Looks good to me!

**Review by meganmadley — APPROVED** [review]

**Review by CBurton90 — APPROVED** [review]

**Pull request merged**
