### PR TITLE
ODZ change in location code

### PR DESCRIPTION
**Pull request by mnaguit**
from LC 20 to LC 21

### CODE REVIEW

**Comment by mnaguit** [comment]
Revised as per @salichon comments.
For another round of review. Thanks!

**Comment by mnaguit** [comment]
Hello @ozym . Can you please review this one too? Thank you.

**Comment by mnaguit** [comment]
Hi @ozym . A follow up on this PR. Do the changes look fine for you? Thanks.

**Comment by brianf3rris** [comment]
Obsidean 823 location code changed from LC 20 to LC 21 at 1:48 pm. on 1/11/2019, recorder location -45.04, 170.64, alt. 264 m. Looks ok.

**Pull request merged**
