### PR TITLE
CMHS strong motion station closure

### PR DESCRIPTION
**Pull request by salichon**
as per https://github.com/GeoNet/tickets/issues/1744

### CODE REVIEW

**Comment by elidana** [comment]
@salichon who do you want me to add here?

**Comment by salichon** [comment]
@elidana @samgeonet 
here comes the CMHS PR
I still have no authorization .. :)

**Comment by ozym** [comment]
@salichon you probably shouldn't reference private repo issues from public repos. Best to go to the private repo and reference back to this pull request, and add a short description.

**Comment by elidana** [comment]
ha ha good to know @ozym, thanks ! I've probably done that several times in my delta pr.

**Pull request merged**
