### PR TITLE
CULC recorder swap

### PR DESCRIPTION
**Pull request by mnaguit**
from CUSP3D SN 42263 to EQR120 SN 46501

### CODE REVIEW

**Review by salichon — CHANGES_REQUESTED** [review]
Morena @mnaguit 
The change time is not the one and certainly related to something else (GPS or else)
The trace are showing a clear gap later on consistent with Conrad s time in the ticket: stop at UTC 2030 |  start at  2130 on the 14 Dec I  reckon.
cheers

**Comment by mnaguit** [comment]
Thanks @salichon . Checking it now and will revise the PR soon.

**Comment by mnaguit** [comment]
Changes made. FYI @salichon @CBurton90

**Review by salichon — APPROVED** [review]
Provided the orientation is the same,
cheers
jerome

**Review by CBurton90 — APPROVED** [review]
All good. Orientation may need an update later if merged now. To save writing it here is the link. 

https://github.com/GeoNet/delta/pull/973#pullrequestreview-553049414

**Pull request merged**
