### PR TITLE
LM35 temperature sensor with Nanometrics Centaur response configuration

### PR DESCRIPTION
**Pull request by CBurton90**
With the trip to Raoul in Oct (18th) a Centaur will be installed at GLKZ in place of the failed Q330. Looking at the existing configurations it seems like the `Trillium 120QA` and `Druck PTX-1830-LAND` have already been added (please let me know if that is not the case), therefore the last combination at this site that does not yet exist with a Centaur is the LM35 temperature sensor (two running on LC 80/81 to Marker Bay Pool and Green Lake). So here it is!

### CODE REVIEW

**Review by ozym — APPROVED** [review]
looks good.

**Review by salichon — APPROVED** [review]
sounds legit .
what s `CW` standing for @CBurton90 Contiunous wave or something ? 
cheers

**Comment by CBurton90** [comment]
> sounds legit .
> what s `CW` standing for @CBurton90 Contiunous wave or something ?
> cheers

@salichon actually not sure, seismic seems to be `CG`. @ozym care to enlighten us 🤣 ?

**Comment by ozym** [comment]
C - Continuous
W - Weather or environmental data

Old school settings.

**Comment by salichon** [comment]
No on was assigned :) - i m taking over ...
Is all good as @CBurton90

**Comment by salichon** [comment]
merged! FYI @rumachan GLKZ green lake should have an updated response with the Centaur now :)

**Pull request merged**
