### PR TITLE
MKAZ serialcorrection

### PR DESCRIPTION
**Pull request by mnaguit**
modify the serial number: from 6136 to 6142

### CODE REVIEW

**Comment by mnaguit** [comment]
https://github.com/GeoNet/delta/pull/341

merged: MKAZ new pull request for serial correction

**Comment by salichon** [comment]
@mnaguit did  you get peannut s review before merging ? - just checking :)

**Comment by peanutty** [comment]
@salichon she did, it was my bad, i thought i had remembered which one was which, but i hadnt...

**Comment by mnaguit** [comment]
@peanutty and @salichon 👍

**Pull request merged**
