### PR TITLE
GNSS TGHM Antenna swap

### PR DESCRIPTION
**Pull request by EvanCGNS**
Added in the new Sepchoke B3E6 antenna into assets/antennas.csv and install/antennas.csv for TGHM Antenna swap.

Closed the previous TGHM antenna.

### CODE REVIEW

**Review by elidana — CHANGES_REQUESTED** [review]
Hi @EvanCGNS , 

thanks for that!

a few comments from me:
- can you please check if antenna height needs changing for this swap? The update will need to go in the `network/marks.csv` file if that's the case. @aleks-spes should be able to help you


I am proposing in the detailed comments a slight modification in antenna make and model names. 

Everything else looks good, though would be good for either me or @aleks-spes to also check the serial number (using a photo from the field, if available).

Thanks!

Elisabetta

**Review by aleks-spes — CHANGES_REQUESTED** [review]
Hey @EvanCGNS !
This antenna also has a radome, so you need to include this information in the `install/radomes.csv`.
Happy to provide extra details if you need it.

**Review by aleks-spes — CHANGES_REQUESTED** [review]
Hey @EvanCGNS ! Could you please update the start time stamp to `2024-04-07T23:48:00Z` and the end time accordingly? The first epoch after the swap can be seen from the RINEX file see: 
```
 24  4  7 23 16 30.0000000  0 22G12G25R08R09R23R15G10G08R21R22G18G24
 24  4  7 23 17  0.0000000  0 22G12G25R08R09R23R15G10G08R21R22G18G24
 24  4  7 23 48  0.0000000  0  8R09G28G23G32G10G21G02G31
 24  4  7 23 48 30.0000000  0 15R22R21R09G28G23G32G10G21R06G02G08G25
```

**Comment by aleks-spes** [comment]
Hey @elidana ! Should we wait to merge this PR until this https://github.com/GeoNet/delta/pull/2057 isn't merged into `main`?
FYI @EvanCGNS

**Comment by elidana** [comment]
so the plan is:
1. merge https://github.com/GeoNet/delta/pull/2058
2. merge https://github.com/GeoNet/delta/pull/2057
3. merge this one

we need someone from sysdev or platform to approve 2058 and 2057 otherwise it can't be merged :(


-

**Review by aleks-spes — APPROVED** [review]
Looks good!
Now we have to wait until 2 other PRs will be merged.

**Review by CBurton90 — APPROVED** [review]

**Review by elidana — APPROVED** [review]
looks good, thanks

**Pull request merged**
