### PR TITLE
add dart tidal constituents

### PR DESCRIPTION
**Pull request by ozym**
A straight copy, other than conversion from meters to centimeters.

### CODE REVIEW

**Review by megankortink — DISMISSED** [review]
LGTM

**Comment by salichon** [comment]
Thanks @ozym 
as a reminder these are the NIWA work output  right? 
and we re not assuming large dart site  distance difference in the near future.

**Review by salichon — APPROVED** [review]
Add a really brief look at niwa email content for one BPR - i had 
looks legit :) 

Edit ... ** besides the `autogo-test` to be remade i suppose :)

**Comment by ozym** [comment]
@salichon @megankortink needed to add the sites to the gauges file (to pass the tests). But this also adds some details about the latitude that was used in the processing so it's good (just it doesn't quite fit with the LINZ/tide gauge bias).

**Comment by salichon** [comment]
Thanks @ozym 
The `Analysis Longitude`  is the same for the "BPR" in gauge.csv  i guess it s a default value latitude being the important one.
Are we required to fill up with the DART CREX tag in complement  ?

**Comment by ozym** [comment]
@salichon yes the value is what was used and is a default I assume.  We don't need to document the CREX as this is done outside of our systems and is done as part of a bulletin rather than individually as per the tide gauges.

**Review by salichon — APPROVED** [review]

**Pull request merged**
