### PR TITLE
DART NZF BPR replace

### PR DESCRIPTION
**Pull request by salichon**
Deploy nr 02 DART Buoy
Site change Only

### CODE REVIEW

**Review by ozym — COMMENTED** [review]
Do we actually that level of precision, i.e. -29.68346667 is down in the mm range?

**Comment by JonoHanson** [comment]
I'd imagine 4 decimal places is more than enough, and as honestly accurate as these measurements can be (assuming GPS measurements, though I guess boats could be pretty accurate)

**Review by JonoHanson — CHANGES_REQUESTED** [review]
Please only include 4 decimal points of precision

**Comment by CBurton90** [comment]
I agree with the above 😉 both lat/long should have a similar level of precision (as Jono suggested 4 decimal places) and consistency. I.e. NZF had previously latitude precision to 6 decimals places and longitude to 4 decimal places and now it has both lat/long to 8 decimal places.

**Comment by salichon** [comment]
Fair enough i went back to my xkcd precision  chart - will  do so sure

**Review by ozym — APPROVED** [review]

**Review by CBurton90 — APPROVED** [review]

**Review by JonoHanson — APPROVED** [review]

**Pull request merged**
