### PR TITLE
VRZ  strong motion 20 to 21 2014-2021 and small time window fix    

### PR DESCRIPTION
**Pull request by salichon**
PR solves
- for the VRZ location code legacy 20 to 21 (2014-2021) in delta 
Go **side by side with a VRZ 20 to 21 VRZ GeoNet archive change** 
 
- for a small time window related to "Old delta" config management  (and no data were recorded at that time)

### CODE REVIEW

**Review by mnaguit — CHANGES_REQUESTED** [review]
I think if relevant date/time for LC 21 will be changed, there is also a need to update `network/sites.csv`? I just wonder why there is no Travis error?

**Comment by salichon** [comment]
@mnaguit yeap that s the plan first merging the Axial PR and then  main site correction.
we ll do this when set for the change in one go for VRZ I reckon when ready :)

**Comment by salichon** [comment]
Hello @mnaguit 
 - Are you happy with the plan above  (2 Pr for VRZ strong  ?)
- Delta:   #1151 and #1152 
or is there any itchy bit ?

**Comment by mnaguit** [comment]
> or is there any itchy bit ?

Hahaha. No itchy bit at all Sir Jerome. 
Approving the PR now ;)

**Review by mnaguit — APPROVED** [review]
Note: Updated version of `streams.csv `, provided in another PR.

**Pull request merged**
