### PR TITLE
FOXxx connect and stream

### PR DESCRIPTION
**Pull request by rumachan**
connections.csv and streams.csv for 
FOXKP
FOXRB
FOXVV
FOXVV

start/end times same as sites.csv

### CODE REVIEW

**Review by jacksonshanks — APPROVED** [review]
looks good to me steve

**Comment by elidana** [comment]
hi @rumachan , this one was forgotten back in oct 2022. can you please review, resolve conflicts and re-request a review? happy to be the reviewer.

**Comment by rumachan** [comment]
@elidana I have same issue here. I don't understand how to resolve conflicts. FOXKP is now closed, and other sites have had additional sensors added since this PR. I don't know the original ticket, but it looks like it was simply adding entries to files that had been missed (by me).

FOXRB, FOXVV, and FOXVF need connections added, but I don't know if this PR is up to date. To me it'd be far easier to start from scratch.

**Comment by elidana** [comment]
makes perfect sense @rumachan !
totally agree, let's just restart from scratch and do a new pr

**Comment by elidana** [comment]
closing without merge, has now been replaced by https://github.com/GeoNet/delta/pull/2003/files

**Pull request closed without merging**
