### PR TITLE
Adding Firmware upgrade details

### PR DESCRIPTION
**Pull request by meganmadley**
NRSW - 5953R40012 - 2022-10-16T20:27:14

### CODE REVIEW

**Comment by aleks-spes** [comment]
QUAR - 6131R40073 - 2022-10-16T20:56:18

**Comment by meganmadley** [comment]
RAHI - 6015R40029 - 2022-10-16T22:14:12
TKAR - 6017R40018 - 2022-10-16T22:41:39

**Comment by aleks-spes** [comment]
RGHL - 5946R40026 - 2022-10-16T23:30:00

**Comment by aleks-spes** [comment]
VGTM - 5921R40189 - 2022-10-17T00:50:26

**Comment by meganmadley** [comment]
Your times look good to me @aleks-spes!

**Review by aleks-spes — APPROVED** [review]
Looks good!

**Pull request merged**
