### PR TITLE
GNSS: fix elevation mask of old sessions

### PR DESCRIPTION
**Pull request by elidana**
GNSS receiver session of BM8A, BNET and CAST were note correctly recorded in delta.

BM8A and BNET had a wrong elevation cutoff value, and CAST had a wrong timestamp.
This pull request fix it. Correct values have been verified against data (for additional details on how see also https://github.com/GeoNet/delta/pull/881).

### BM8A
wrong elevation mask in delta record for this session
```
$> teqc +qc +mask +set_mask 0 -bins 180 -nav brdc1130.13n bm8a1130.13o
```

the resulting TEQC QC output summary report number of observation per elevation will show
```
$> tail -20 bm8a1130.13S 
  9 - 10    129   3.449   20.605 ##||||||||
  8 -  9    124   3.163   20.663 ##||||||||
  8 -  8    127   3.067   20.640 ##||||||||
  8 -  8    134   3.063   19.789 ##||||||||
  7 -  8    138   2.909   19.661 #|||||||||
  6 -  7    134   2.902   19.254 #|||||||||
  6 -  6    126   3.106   19.099 ##||||||||
  6 -  6    126   3.185   19.099 ##||||||||
  5 -  6    115   2.855   18.615 #||||||||
  4 -  5    101   2.821   18.710 #||||||||
  4 -  4     94   3.320   19.497 ##||||||||
  4 -  4      3  11.293   12.833 ######
  3 -  4      0   0.000    0.000 
  2 -  3      0   0.000    0.000 
  2 -  2      0   0.000    0.000 
  2 -  2      0   0.000    0.000 
  1 -  2      0   0.000    0.000 
  0 -  1      0   0.000    0.000 
  0 -  0      0   0.000    0.000 
```

### BNET
wrong elevation mask in delta record for this session
```
[elidana@hutl16534 yald]$ tail -15 bnet1000.18S
  6 -  7     44   3.512   17.386 ##|||||||
  6 -  6     34   3.928   17.309 ##|||||||
  6 -  6     22   4.430   16.705 ##||||||
  5 -  6      8   6.846   16.562 ###|||||
  4 -  5      3  11.492   13.250 ######|
  4 -  4      0   0.000    0.000 
  4 -  4      0   0.000    0.000 
  3 -  4      0   0.000    0.000 
  2 -  3      0   0.000    0.000 
  2 -  2      0   0.000    0.000 
  2 -  2      0   0.000    0.000 
  1 -  2      0   0.000    0.000 
  0 -  1      0   0.000    0.000 
  0 -  0      0   0.000    0.000 
```

### CAST
cutoff change with receiver firmware upgrade
```
[elidana@hutl16534 elcut]$ tail cast0950.16S 
  4 -  4    265   1.886   17.373 #||||||||
  4 -  4    327   1.795   17.421 #||||||||
  3 -  4    286   1.755   17.388 #||||||||
  2 -  3     21   4.070   16.419 ##||||||
  2 -  2      0   0.000    0.000 
  2 -  2      0   0.000    0.000 
  1 -  2      0   0.000    0.000 
  0 -  1      0   0.000    0.000 
  0 -  0      0   0.000    0.000 
```

### CODE REVIEW

**Comment by elidana** [comment]
CAST as well
```
[elidana@hutl16534 elcut]$ tail cast0950.16S 
  4 -  4    265   1.886   17.373 #||||||||
  4 -  4    327   1.795   17.421 #||||||||
  3 -  4    286   1.755   17.388 #||||||||
  2 -  3     21   4.070   16.419 ##||||||
  2 -  2      0   0.000    0.000 
  2 -  2      0   0.000    0.000 
  1 -  2      0   0.000    0.000 
  0 -  1      0   0.000    0.000 
  0 -  0      0   0.000    0.000 
```

**Review by staylorofford — COMMENTED** [review]
Looks good, but just to check, CAST change is due to the 3 degree elevation angle cutoff persisting longer than the metadata has it? The data you show in this ticket confirm the 3 degree cutoff, but not the change time.

**Comment by elidana** [comment]
thanks @staylorofford ,

yes for CAST I have only checked that the 3 degrees cutoff was set later on. The timestamp use coincide with a firmware upgrade for that site.

**Review by staylorofford — DISMISSED** [review]

**Comment by elidana** [comment]
good catch on BM8A @staylorofford thanks. This should have now been reintroduced

**Review by staylorofford — APPROVED** [review]

**Pull request merged**
