### PR TITLE
GNSS receiver firmware upgrades

### PR DESCRIPTION
**Pull request by elidana**
Another bunch of firmware upgrades to v5.45 on the following GNSS sites: 
ARTA
CLRR
FRTN
HANA
HANM
HORN
KAPT
LEVN
MAKO
MCNL
MKNO
MNHR
MRBL
PAEK
PARW
PAWA
RAKW
RAUL
RCHD
RGAR
RGHD
RGMT
RGRR
RGUT
TGRI
TGTK
TKHL
TRAV
TRWH
VGTM
WAHU
WHVR
WRAU
YALD

### CODE REVIEW

**Comment by elidana** [comment]
Hi @staylorofford , this is the last batch of firmware upgrades. Can you please review this pr? Thanks!

**Review by CBurton90 — APPROVED** [review]
All looks good!

**Comment by staylorofford** [comment]
Sorry Betta, Conrad got there first. Do I still need to review?

**Comment by elidana** [comment]
@staylorofford no need for you to review, Conrad offered and did it this morning but thanks!

**Pull request merged**
