### PR TITLE
CRSZ sensor swap

### PR DESCRIPTION
**Pull request by mnaguit**
from Lennartz LE-3Dlite (SN: S-0985) to Lennartz LE-3DliteMKIII (SN: G-0563)
for LC 10 EH(ENZ)

### CODE REVIEW

**Review by salichon — CHANGES_REQUESTED** [review]
thanks @mnaguit 
It s all good,
can we add:
_CRSZ,XX,Clarence River Middle Hill,-42.14457,173.8154,930.3,,WGS84,2015-11-15T05:25:00Z,9999-01-01T00:00:00Z_

to be **SI** instead of **XX** ? as part of the permanent regional network 
thanks

**Comment by salichon** [comment]
Heya! 
since it s a "new" permanent station (`XX` to subnetwork  as `SI`) perhaps worth it to be approved by @ozym 
(mostly for a FYI and perhaps other mechanisms)

**Comment by mnaguit** [comment]
> Heya!
> since it s a "new" permanent station (`XX` to subnetwork as `SI`) perhaps worth it to be approved by @ozym
> (mostly for a FYI and perhaps other mechanisms)

@salichon Changes made on the network code & I have added @ozym to review
Thanks.

**Review by salichon — APPROVED** [review]
looks good to  me :)

**Review by ozym — APPROVED** [review]

**Review by CBurton90 — APPROVED** [review]

**Pull request merged**
