### PR TITLE
NZF correcting start and end dates

### PR DESCRIPTION
**Pull request by meganmadley**
Buoy start and close dates for NZF from beta-data readme:
NZF | 2019-12-16 | 2020-03-25 | -29.6843 | -175.0126
NZF | 2020-08-31 | 2020-09-25 | -29.6823 | -175.0124
NZF | 2021-07-20 | - | -29.6823 | -175.0124
Can see that it had the same BPR for the last two entries (same poisiton), so is currently on 2nd BPR. In delta only tracking BPR's, question for this ticket is if we want to change the end time of NZF 40 to be `2020-03-24T13:57:15Z` or something similar before all of the 15s trigger values which must have happened when they picked the buoy/bpr up.

### CODE REVIEW

**Comment by ozym** [comment]
Can we perhaps add a new streams entry to exclude the "odd" data time period:

```
NZF 2020-09-26T07:30:00Z 5058810
NZF 2020-09-26T07:45:00Z 5058792
NZF 2020-09-26T08:00:00Z 5058782
NZF 2021-07-20T02:15:00Z 5990003 **
NZF 2021-07-20T02:30:00Z 6010003 **
NZF 2021-07-20T02:45:00Z 6000003 **
NZF 2021-07-20T03:00:00Z 6020003 **
NZF 2021-07-20T23:15:00Z 5058672
NZF 2021-07-20T23:30:00Z 5058715
NZF 2021-07-20T23:45:00Z 5058764
NZF 2021-07-21T00:00:00Z 5058816
NZF 2021-07-21T00:15:00Z 5058872
NZF 2021-07-21T00:30:00Z 5058931
```

**Comment by ozym** [comment]
```
NZF,41,-15,false,false,false,2020-08-31T23:15:00Z,9999-01-01T00:00:00Z
```
vs
```
NZF,41,-15,false,false,false,2020-08-31T23:15:00Z,2020-09-26T09:00:00Z
NZF,41,-15,false,false,false,2021-07-20T23:15:00Z,9999-01-01T00:00:00Z
```

**Comment by ozym** [comment]
I think the best step here to slice in a streams change to avoid the bad bit of data (part of operational connections?).

That is the existing stream ends just after NZF 2020-09-26T08:00:00Z 5058782
and a new one begins at 2021-07-20T23:15:00Z and continues.

**Comment by meganmadley** [comment]
What do you think @ozym, just changed it to the split stream, keeping it as '41' makes sense right? @salichon keen to hear your thoughts as well

**Comment by ozym** [comment]
That's what I had in mind, we'll let @salichon tick this (or not).

**Comment by salichon** [comment]
hi There @meganmadley 
that makes sense! 
with regards to https://github.com/GeoNet/tickets/issues/7319#issuecomment-771184416

-site 41 `Buoy comms replaced - BPR on site1`  
that means once that BPR is  recovered we ll have  the  high rate continuous that will span these periods.
this is about like backfilling a seismic sensor after real time comms ceased.
so
 recorder opened all the time  |  streams closed as the Buoy systems is On/Off  
 sounds good. 

and now i remember that  
- site 40 BPR is lost at sea

**Review by salichon — APPROVED** [review]
- tick soundfs good

**Review by ozym — APPROVED** [review]

**Pull request merged**
