### PR TITLE
create a separate file to list stations for manually collected data

### PR DESCRIPTION
**Pull request by elidana**
How does this look?
I've used "samples" as file name (using the GeoNet data glossary of terms as inspiration, https://doi.org/10.21420/XQS0-0Z48) but happy to change to a better name if there are different opinions.

### CODE REVIEW

**Review by rumachan — APPROVED** [review]
I'm quite happy with that. Happy to use any filename that works. 

This will have downstream consequences for Tilde meta-data I assume, so you'll want to let that team (Callum especially?) know.

**Comment by ozym** [comment]
@elidana looking good, could I get you to restore the stations.csv file to the original state. This should allow the current code to work and tests passing downstream etc.  I can then look at adding the backend support.

**Comment by elidana** [comment]
How about now? not sure if you wanted the `samples.csv` to also include the data, but if not I can update that file too and remove the MC records for now

**Review by ozym — APPROVED** [review]
Looks good, there will be some follow up PRs

**Comment by elidana** [comment]
nice! thanks!!

**Pull request merged**
