### PR TITLE
DART Add streams,recorder to NZA

### PR DESCRIPTION
**Pull request by salichon**
DART into Delta 
 - Instrument are recorders
 - streams are water height convention 

NB: might have an issue with `test.sh`  and  `consistency_test.go` (local branch)

### CODE REVIEW

**Comment by salichon** [comment]
This can be related to Serial (informed) vs Number (not informed) in assets

**Review by megankortink — COMMENTED** [review]
I think you may have the wrong year for the deploy date, I thought it was "2019-12-22". This is the date from the wiki page, and the beta-data readme

**Comment by salichon** [comment]
thanks a lot @megankortink 
I pushed the correction

**Review by megankortink — APPROVED** [review]
LGTM

**Review by ozym — APPROVED** [review]
looks good to me.

**Comment by salichon** [comment]
Thanks

Locally created station XML gives  a reasonable output
[NZAcheck.xml.txt](https://github.com/GeoNet/delta/files/6613421/NZAcheck.xml.txt)

**Pull request merged**
