### PR TITLE
CWHB metadata update

### PR DESCRIPTION
**Pull request by mnaguit**
update entries for LC 21 to 29 & 2A to 2D

### CODE REVIEW

**Comment by mnaguit** [comment]
So atm @ozym it's ok to include both 50 and 200 hz in the metadata, and modify it later as needed? Thanks @ozym 👍

**Comment by mnaguit** [comment]
Hi @ozym . I removed all entries for 50hz in streams.csv.
Kindly do another round of review @salichon @samgeonet @brianf3rris @ozym @jristau 
Thanks.

**Comment by salichon** [comment]
@mnaguit 
i ve been here: https://ceraarchive.dpmc.govt.nz/sites/default/files/Documents/christchurch-hospital-acute-services-building-design.pdf

i haven t seen undegronud floors.

**Comment by mnaguit** [comment]
Thanks @salichon . Will check elevation details from John & update accordingly.

**Comment by salichon** [comment]
Aaaall, 
right the site elevation in delta for the building array is by convention the elevation above the sea level (positive upward)
The recorders depth are negative upward.
For CWHB the site elevation reference is 5 meters as per John young. 
--> modify the sites.csv accordingly. 
FYI @mnaguit  (:) )

**Comment by mnaguit** [comment]
Noted with super thanks @salichon 
Will modify the .csv accordingly.

**Comment by mnaguit** [comment]
Hi @salichon . Changes on elevation have been made (on sites.csv). One final review from you and I'll merge this PR. Thanks.

**Comment by mnaguit** [comment]
Great. Thanks @salichon 
Will merge this PR now.

**Pull request merged**
