### PR TITLE
Adding new DART BPR start and end dates to B,F,G,H,I

### PR DESCRIPTION
**Pull request by meganmadley**
Values from BPR in AWS

BPR .txt files in AWS Start (ignoring the 0 files) and End dates
NZB 2020-09-18T19:53:30Z,2022-08-14T22:59:45Z
NZF 2020-08-31T20:49:00Z,2022-08-10T00:59:45Z
NZG 2020-09-10T20:50:00Z,2022-07-29T19:59:45Z
NZH 2020-09-03T19:53:30Z,2022-08-01T01:59:45Z
NZI 2020-09-08T00:24:15Z,2022-08-02T21:59:45Z

### CODE REVIEW

**Comment by meganmadley** [comment]
May need to change some of these times

**Comment by meganmadley** [comment]
@ozym have just updated this with the dates that I posted in slack

**Review by salichon — COMMENTED** [review]
Is it ready to get reviewed ?

**Comment by meganmadley** [comment]
@salichon yes please, here are some details on how I chose the start and end times from the BPR data:
BPR .txt files in AWS Start (going for the first place where the depth is consistent) and End dates
NZB - 2-190706 - 2020-09-18T21:12:30Z,2022-08-14T22:59:45Z
2020-09-18T19:00:00Z - first time in file
2020-09-18T19:53:30Z - started sinking
2020-09-18T21:12:30Z - at the appropriate depth
2022-08-14T22:59:45Z - last time in file still at depth

NZF - 200117-16 - 2020-08-31T23:10:15Z,2022-08-10T00:59:45Z
2020-08-31T20:00:00Z - first time in file
2020-08-31T20:49:00Z - started sinking
2020-08-31T23:10:15Z - at depth
2022-08-10T00:59:45Z - last file and still at appropriate depth

NZG - 190726 - 2020-09-10T22:57:30Z,2022-07-29T18:02:45Z
2020-09-10T20:00:00Z - first time in file
2020-09-10T20:50:00Z - started sinking
2020-09-10T22:57:30Z - at depth
2022-07-29T18:02:45Z - last time at depth
2022-07-29T19:59:45Z - last time in file - rising (not quite at the surface)

NZH - 190724 - 2020-09-03T22:24:30Z,2022-08-01T00:12:30Z
2020-09-03T19:00:00Z - first time in file
2020-09-03T19:53:30Z - started sinking
2020-09-03T22:24:30Z - at depth
2022-08-01T00:12:30Z - last time at depth
2022-08-01T01:59:45Z - last time in file - rising (not quite at the surface)

NZI - 191002-9 - 2020-09-08T03:15:45Z,2022-08-02T21:59:30Z
2020-09-08T00:00:00Z - first time in file
2020-09-08T00:24:15Z - started sinking
2020-09-08T03:15:45Z - at depth
2022-08-02T21:59:30Z - last time at depth
2022-08-02T21:59:45Z - last time in file - rising a little bit

**Review by salichon — APPROVED** [review]
This is looking good and consistent to me :) 
so a few prior deployments starting dates change  and  settting the stopping dates based upon the observation depths  based on received messages. 
thnaks !

**Review by ozym — APPROVED** [review]

**Pull request merged**
