### PR TITLE
URZ - matahivalley - orientation update 

### PR DESCRIPTION
**Pull request by CBurton90**

### CODE REVIEW

**Comment by CBurton90** [comment]
https://github.com/GeoNet/tickets/issues/8615#issuecomment-871761473

**Review by staylorofford — APPROVED** [review]
LGTM King

**Comment by CBurton90** [comment]
@staylorofford @salichon one of the the SOD boys will have to merge 😉

**Comment by salichon** [comment]
@CBurton90  I know it s negligible what made the difference between 215.7 to 217 as staetd in your event scan ?
cheers:)

**Comment by salichon** [comment]
see https://github.com/GeoNet/delta/pull/1130

**Pull request merged**
