### PR TITLE
Garming clock upgrades

### PR DESCRIPTION
**Pull request by elidana**
Hi, 
this is capturing garmin clocks upgrades on Strong motion sites performed between March and end of May.

Would be nice to have it reviewed by @CBurton90 and either @mnaguit or @salichon from our team.

Thanks!

### CODE REVIEW

**Review by salichon — DISMISSED** [review]
sounds sensible :)

**Review by CBurton90 — APPROVED** [review]
L:ooks fine. I noticed the other ones in the notes were

`Fix GPS week number rollover`

I dont mind if it's that or `Fix GPS timing error` but should we stick to one?

**Comment by elidana** [comment]
good catch conrad! that's my bad, as I've probably used a wrong script. I'll modify the comment, thanks!

**Comment by elidana** [comment]
@CBurton90 now done, can I please ask another thumbsup from you or @salichon ?

**Review by CBurton90 — APPROVED** [review]

**Review by salichon — COMMENTED** [review]
:+1

**Comment by elidana** [comment]
thanks!!

**Pull request merged**
