### PR TITLE
HADES Temp network are CLOSED - Closure dates are Set  OK - spans 2009 up to 2019 

### PR DESCRIPTION
**Pull request by salichon**
Untill  further detailed information on their older actual closure
-->> HADES stations are closed on 2021.01.01 and not let opened

### CODE REVIEW

**Review by staylorofford — APPROVED** [review]

**Comment by salichon** [comment]
@JonoHanson Are you happy with this first step on sorting these metadata for the users  ?

**Comment by JonoHanson** [comment]
no problem, but did we check with Cam about whether we actually can have closure dates? he is managing the hades deploy, so this is probably one where we don't need to close arbitrarily.

**Comment by salichon** [comment]
in process @JonoHanson 
see https://github.com/GeoNet/tickets/issues/6266#issuecomment-864619781

**Comment by salichon** [comment]
On hold till  @Camasher  caomes out with sensible closing dates :) FYI @JonoHanson  (sometime in july 2021)

**Comment by salichon** [comment]
Heelo @Camasher Any comments about the HADES closure experiment ?
thanks

**Comment by Camasher** [comment]
Stations.csv and dataloggers.csv are complete, including adding the additional sites that weren't in Delta (I'd rather all the info in here or none, rather than a middle ground of incomplete data). Will start on sensors and connections

**Comment by Camasher** [comment]
Connections done, sensors time

**Comment by Camasher** [comment]
Cleaning up merge errors

**Comment by Camasher** [comment]
omg finally, all checks have passed. @salichon over to you

**Comment by salichon** [comment]
Thanks a lot @Camasher 
that s great
I shall  go through and polish  a few related information (as in the `streams.csv`)

**Comment by salichon** [comment]
Hello @Camasher  a little bit more digging in the past. sorry!
Do  you have info about HD04 first deploy  ended in 2012) the site is still opened - 
by default i ll close it at `2013-01-01 00:00:00`   since `HD02`  is being the oldest closed of this set at `2012-11-03T...`

**Comment by salichon** [comment]
@staylorofford @Camasher 
i finally added the streams and picked up  HD11 and HD04 for correction and closure. 
this is a chunk of change omg ... 
checking this is as hard as doing the change   ... 
FYI @JonoHanson

**Comment by salichon** [comment]
Hello @staylorofford 
Any updates about this branch review.
 thanks!

**Comment by salichon** [comment]
`blink-blink` @staylorofford - for review commens :)

**Comment by staylorofford** [comment]
Fine I will do it.

**Comment by staylorofford** [comment]
Table collating all HADES metadata in this PR:

[HADES_metadata.csv](https://github.com/GeoNet/delta/files/7811102/HADES_metadata.csv)

**Comment by staylorofford** [comment]
I have made comparisons for all the details a) within each installation and b) across installations within a deployment (site code). I have not made comparisons across deployments and have trusted delta's checks to ensure this is all correct.

Where I make no comment, assume all is well.

General comments:
- network/stations.csv Name and install/connections.csv Place are all the same except HD11, which has White road under stations.csv and HADES 11 under connections.csv
- HD61 has 1 sf more in latitude and longitude for network/sites.csv, otherwise they are the same for all sites across both network files
- No depth under stations and sites CSVs - is it needed?
- Timings are generally sloppy with various minor discrepencies in start and end times across tables where it seems to me that there should not be. I am not familiar with seismic conventions and there is no data to compare these to for accuracy, but it is pervasive and worthy of note. In particular, streams.csv start times are regularly before even those of the network CSVs. It would be worth reviewing all these times for consistency. They can be found clearly in my attached XLSX document.
- Most of the Taurus do not have asset numbers. As above, this is pervasive so I make no specific notes of it.

Specific comments:
- HD11: Start time in network csvs is in 2010 but other start times are in 2018 - you sure?
- HD50: there are two equipment installations over the deployment period. The Taurus #2583 is wrongly associated with the TC-120 #619 installation period in one case. This Taurus belongs with LE-3DliteMkII #F-0369 installation period.
- HD50: install/streams.csv start time is only minutes before the first datalogger installation period ends and is seconds behind the start of the LE-3D installation but seconds after the end of the TC-120 installation - something is wrong here.
- HD55: datalogger start/end times are exactly the same - does a 1 second difference need to exist?
- HD57: last sensor install ends 6 months before the rest of the installation/deployment?
- HD61: Is it necessary to have a 1 second installation of T120 #531 followed by a 3 year installation starting a day later?
- HD63: Installation depth for all entries is 30 cm above ground?
- HD64: Installation depth for all entries is also 30 cm above ground?
- HD65: One installation depth is 30 cm, others are at 0?
- HD71: Sensor does not have an asset #

Closing notes:
- I regret agreeing to incorporate this metadata in delta.
- I wrote a script to compile all the installation details to make reviewing easier. It was not an easy task, but was probably still faster than doing it manually. Expect to see it in `datax` soon and hit me up for a lesson; hopefully it will help with other metadata efforts.
- Once we have all this tidied up, let's work out that alignment table to go with this metadata. Hopefully it will be a cakewalk by comparison.

**Comment by salichon** [comment]
- will amend HD11 place to "HADES 11" instead of allen road
- HD11 site and station were opened in 2010 only known equipment is from 2018, no info if occupied or not and by what) 
let s keep as this.
- will round HD61 coords this comes out of the instrument i guess and is not relevant
-  No depth is good for the surface portable - elevation matters somehow
- The time sloppiness comes from former approaches (old delta) and from amending each of the HD multiple to a close date value.
will make it more consistent and to more relevant dates for new delta  
- Asset Numbers may be not a priority there since less likely yo be used.
Although this could be added for the sake of it. 

...TBC

**Comment by salichon** [comment]
- HD50 i think it s all right (btw something is weird in the comment :)) 
it looks like a bit of datlogger fiddling having the `Taurus,0554` fir a couple of days ...
- will provide some rounding timing consistency  around the HD50 equipment swap ...
-HD55/61 yeah old ways -t his can be changed (the 1 second was apparently for old delta DB to digest) - we don 't need this anymore. but it is common legacy in Delta :) 
- HD57 sensor install  data looks  allright - the connection part is not accounting for the equipment before 2015-12-10T00:11:01Z. `connections.csv` to be amended
- HD 63 to 65 indicating a buried portable (too) precisely -  sensor.csv can be amended to prevent sensors from floating in the air ...

Will porceed to updated PR ...

i like your closing remarks @staylorofford  ha. Feeling the pita pain of temp set ups! 
we ll prevail.

**Comment by salichon** [comment]
@staylorofford  I ve updated the PR  for you to have a look at ... tedious aye ...
sorted and cleaned to be relevant to completed metadata 

(HADES 01-39  (z8 network)  there  https://ds.iris.edu/gmap/#network=Z8&starttime=2009-01-01T00:00:00&endtime=2011-12-31T23:59:59&planet=earth ) 
Cheers

**Comment by salichon** [comment]
@JonoHanson FYI  we re getting there with the HADES (part 1 reckon) 
FYI the sizing of doing this carefully is relatively large, 
requires patience, time and loads of educated calls and fixes.
There are a few bunches of these to go ....

**Review by staylorofford — APPROVED** [review]
It is my pleasure to announce: in the name of the SOD team I approve these changes.

You may want to correct the last digital of the site lat/lon for HD61 to agree with that of the station lat/lon (or vice versa). However given that this level of precision is unrealistic anyway, I am not sure it matters.

Nice work! Let's finish this beast.

**Comment by salichon** [comment]
It has taken the dust 
I ll polish  HD61 for consistency 

thanks @staylorofford a lotV ! 

btw 

thats how  i feel SOD team is on that case ... cerberus ..
image

**Comment by salichon** [comment]
not yet out of hell ...
 1. Will correct for HD61  **1 second**!!  sensor  lifetime  - Relally this should not be ...  ever :) 
>> " Nanometrics Inc.,Trillium Compact 120,531,HD61,10,0,,0,0,0,0,0,0,2016-11-30T22:07:04Z,2016-11-30T22:07:05Z"
this is clearly a mistake (somewhere during the install )  - this contaminates the metadata volume wiht non really releavnt information in addtion ...
2. Location of HD61  is extremely overkilled precise - in any case i make it consistent.

- sorry will need one "Yeah" more after PR  correction soon  @staylorofford

**Comment by staylorofford** [comment]
Hmm and I thought that 1 second might have been important! Will trust your judgement to remove it

**Comment by salichon** [comment]
@staylorofford  i the old delta maybe - now it s more a nuisance..
branch refreshed and PR done for HD61

**Review by staylorofford — APPROVED** [review]
Make it so

**Comment by salichon** [comment]
can t believe we nailed it  :) 11 months and 10 days delta PR 
will squash and merge NoW 
thanks a lot @Camasher @staylorofford et al.! 


_We re back from it!, Orpheus_

**Pull request merged**
