### PR TITLE
Station XML: No more  secondary HN in scp.xml ?  - Metadata selection to be  changed in SC3

### PR DESCRIPTION
**Pull request by salichon**
In order to solve for the / lack of / missing/ display of secondary streams (strong motion) in the GUI 
the station xml selector for seiscomp3 is changed to select only continuous BN 50Hz 
until the HN are streamed continuously instead

https://github.com/GeoNet/tickets/issues/4292
https://github.com/GeoNet/tickets/issues/4171

- [x] Testing on systems is required (this is a metadata update process)
 --> used a test scp xml form a delta repo - Conversion done - stationxml to sc3 xml still needs to turn m/s to M/S units

Cheers
Jerome

### CODE REVIEW

**Comment by salichon** [comment]
@quiffman @ardrigh @ozym 
Hello G'ming,
refreshing this ticket, i d like to have your thoughts/approval about this fix to display all available secondary  BN streams and avoiding the  missing display of secondary streams in the  sc3 GUI s
Cheers
jerome

**Comment by salichon** [comment]
@ardrigh 
In terms of display this Delta PR is something i would consider while updating the Network.
--> limitating secondary streams to an actual  single one ...

**Comment by salichon** [comment]
A choice to be made to display secondary streams in Seiscomp3
or at least agreement :). 

- [ ] Amend station  xml and ignoring secondary HN -  stay onBN  for the moment (2019-2020)
- [ ] Switch to secondary  streams  HN (continuous/and triggered)  only (Future)

**Comment by ardrigh** [comment]
> A choice to be made to display secondary streams in Seiscomp3
> or at least agreement :).
> 
>     * [ ]  Amend station  xml and ignoring secondary HN -  stay onBN  for the moment (2019-2020)
> 
>     * [ ]  Switch to secondary  streams  HN (continuous/and triggered)  only (Future)

@salichon @ozym I think we should discuss this at the meeting on Friday.

**Comment by salichon** [comment]
No  more that relevant

**Comment by salichon** [comment]
This will be resolved by 
 https://github.com/GeoNet/tickets/issues/5966

**Pull request closed without merging**
