### PR TITLE
TCW Episensor to Fortis, Q330 to Centaur SM Sensor + datalogger swap

### PR DESCRIPTION
**Pull request by Thomas-Benson**
- Removing Kinemetrics FBA-ES-T Episensor (996) from `TCW LC 20`
- Replacing with Guralp Fortis (TF-1116) at same location
- Removing Q330/6 from `Tory Channel`
- Replacing with Centaur (9921) at same place
- Using latest Centaur firmware version 4.8.5
- Streams affected TCW Locations 10 & 20

### CODE REVIEW

**Comment by gva6500** [comment]
> Hi @Thomas-Benson , thanks for this. We have to wait for the LC check. Ticket says Fortis should be streaming at LC 21. FYI @CBurton90 @gva6500

@mnaguit  yes you are correct, strong motion moved from vault to cabinet. Ticket is correct but datalogger not. I will correct it (I take it and archive correction will also happen...)

**Review by CBurton90 — APPROVED** [review]

**Comment by CBurton90** [comment]
@Thomas-Benson Sorry for breaking your PR, connections.csv also needs an update (from 20 to 21) but probably easier if you update on your branch : )

**Comment by Thomas-Benson** [comment]
Updated SM to LC 21 in `sensors.csv`, `connections.csv`, `streams.csv` and `sites.csv`
Also, as far as I can tell the SM has been continuous since `2016-12-02`, So I have included that in `streams.csv`

**Review by mnaguit — APPROVED** [review]
Thank you @Thomas-Benson 👍

**Review by CBurton90 — APPROVED** [review]

**Pull request merged**
