### PR TITLE
add metadata notes imported from RT ticket

### PR DESCRIPTION
**Pull request by elidana**
Hi,
with this pr I'm updating some metadata that were recorded in our old ticketing system and didn't have a place in the old Oracle-Delta.

### CODE REVIEW

**Comment by elidana** [comment]
Hi @peanutty , can you please check that pr when you have time? Thanks!

**Comment by elidana** [comment]
@peanutty , thanks for your review!

as you say, I can't find evidences of the 4m tall mast from photos and multipath values/time series residuals are not showing an impact of any test installation.
The reference to KAPT temporary comms mast installation has hence  been removed.

**Comment by elidana** [comment]
Hi @peanutty, I've modified the KAPT entry as per your suggestion. Can I have your tick please so that I can merge this pr?
Thanks!

**Comment by peanutty** [comment]
@elidana stop gitting and enjoy ROMA!

**Pull request merged**
