### PR TITLE
auto go changes for Barometer and Infrasound with Centaur 

### PR DESCRIPTION
**Pull request by CBurton90**
Re-ordering was a bit strange but I believe it is all there @ozym 

Happy to delete and start again if not.

### CODE REVIEW

**Review by salichon — APPROVED** [review]
reproduced that file ok  with the previous PR on Centaur barometer and microphone combo 
all good to me @CBurton90  :+1:

**Comment by salichon** [comment]
@CBurton90 is there already Centaur + pressure meters combo on the field yet ? 
thanks 
(wanted to check on actual  responses)

**Comment by CBurton90** [comment]
@salichon No this configuration has not been deployed yet. There was a chance it may happen at WSRZ but we are preferring to use a Q330S+ there (with the Centaur as backup) and it may or may not even go ahead anyway. In the future I'd say this combination will happen though so good to get ahead of the curve 😉 .

**Comment by salichon** [comment]
no Woz @CBurton90 
i generated a ghost one  the station XML loooks allright
unless @ozym wants to review further , has a veto or some complements to me it s ll fine 
  
Me or Mark  to merge into delta :) 
  cheers

**Pull request merged**
