### PR TITLE
Q330->Q330s+ +  2 druck sensors replacement

### PR DESCRIPTION
**Pull request by jristau**
GBIT datalogger and sensor change

### CODE REVIEW

**Comment by samgeonet** [comment]
@ozym I will check but I'm pretty sure we copied what was on the packet

**Comment by salichon** [comment]
@jristau  we have to amend and correct that branch after the typo correction

**Comment by salichon** [comment]
@jristau  we have to amend and correct that branch after the typo correction

 Thank you Travis and @ozym  :) 

> > -- FAIL: TestSensors (0.06s)
>     --- FAIL: TestSensors/check_for_missing_sensors (0.00s)
>     	sensors_test.go:21: unable to find sensor: General Electric Industrial Sensing Druck PTX-1830 [102200190]
>     --- FAIL: TestSensors/check_for_missing_sensor_assets (0.02s)
>     	sensors_test.go:168: unable to find sensor asset: Druck PTX-1830 [102200190]
> FAIL
> FAIL	github.com/GeoNet/delta/tests	0.555s
> ++error_handler
> ++echo 'Trapped error - Unknown Error'
> Trapped error - Unknown Error

**Comment by salichon** [comment]
@jristau I made a try:
Trying to correct directly the typo in the branch using the github (just to see how it works)
I updated directly the branch - it seems to work - travis on the way 
cc/ @ozym @samgeonet

**Comment by salichon** [comment]
NB: first correction and commit wihtout sorting the serial number of the sensor: Travis failed apparently - or perhaps it s related to the  following change to sort the serial number 

> FAIL
> FAIL	github.com/GeoNet/delta/tests	0.551s
> ++error_handler
> ++echo 'Trapped error - Unknown Error'
> Trapped error - Unknown Error
> ++((  errcount++  ))
>

**Comment by ozym** [comment]
@salichon See my comment way up,  you need to have the serial numbers sorted in "alphabetical" order (not numerical).

The actual error reported is:
```
 --- FAIL: TestConsistency/check_file_consistency:_sensors (0.01s)
    	consistency_test.go:63: ../install/sensors.csv: **** csv file mismatch **** : 
    	consistency_test.go:87: *** ../install/sensors.csv	2018-02-01 22:18:43.560776628 +0000
    		--- /tmp/tst792725430	2018-02-01 22:18:55.348999994 +0000
    		***************
    		*** 56,62 ****
    		--- 56,64 ----
    		  GNS Science (Wairakei),Temperature sensor (K-type),Inferno1,INFR,81,0,0,0,0,0,0,0,2013-05-21T00:00:00Z,9999-01-01T00:00:00Z
    		  GNS Science (Wairakei),Temperature sensor (K-type),TC20121206,INFR,82,0,0,0,0,0,0,0,2013-05-21T00:00:00Z,9999-01-01T00:00:00Z
    		  General Electric Industrial Sensing,Druck PDCR-1830,2427881,WLGT,41,0,90,0,0,0,1.03,0,2007-03-06T00:00:02Z,2007-05-22T23:30:00Z
    		+ General Electric Industrial Sensing,Druck PTX-1830,10220190,GBIT,40,0,0,0,0,0,1.03,0,2017-12-12T02:45:00Z,9999-01-01T00:00:00Z
    		  General Electric Industrial Sensing,Druck PTX-1830,10236615,CPIT,40,0,90,0,0,0,1.03,0,2017-05-10T02:25:21Z,9999-01-01T00:00:00Z
    		+ General Electric Industrial Sensing,Druck PTX-1830,10515689,GBIT,41,0,0,0,0,0,1.03,0,2017-12-12T02:45:00Z,9999-01-01T00:00:00Z
    		  General Electric Industrial Sensing,Druck PTX-1830,10515690,CPIT,41,0,90,0,0,0,1.03,0,2017-05-10T02:25:21Z,9999-01-01T00:00:00Z
    		  General Electric Industrial Sensing,Druck PTX-1830,2504328,WLGT,40,0,90,0,0,0,1.03,0,2007-03-06T00:00:02Z,2012-05-29T22:55:00Z
    		  General Electric Industrial Sensing,Druck PTX-1830,2574749,NAPT,40,0,90,2,0,0,1.03,0,2007-09-12T00:00:00Z,2010-12-14T23:00:00Z
    		***************
    		*** 114,121 ****
    		  General Electric Industrial Sensing,Druck PTX-1830,3562513,WLGT,40,0,90,0,0,0,1.03,0,2012-05-30T00:00:00Z,9999-01-01T00:00:00Z
    		  General Electric Industrial Sensing,Druck PTX-1830,3964175,CHST,41,0,90,0,0,0,1.03,0,2015-06-24T00:00:00Z,9999-01-01T00:00:00Z
    		  General Electric Industrial Sensing,Druck PTX-1830,3964188,CHST,40,0,90,0,0,0,1.03,0,2015-06-24T00:00:00Z,9999-01-01T00:00:00Z
    		- General Electric Industrial Sensing,Druck PTX-1830,10220190,GBIT,40,0,0,0,0,0,1.03,0,2017-12-12T02:45:00Z,9999-01-01T00:00:00Z
    		- General Electric Industrial Sensing,Druck PTX-1830,10515689,GBIT,41,0,0,0,0,0,1.03,0,2017-12-12T02:45:00Z,9999-01-01T00:00:00Z
    		  General Electric Industrial Sensing,Druck PTX-1830-LAND,2722283,EDAS,49,0,0,9.2,0,0,1,0,2008-06-11T01:00:00Z,9999-01-01T00:00:00Z
    		  General Electric Industrial Sensing,Druck PTX-1830-LAND,2933712L,GLKZ,40,0,0,0,0,0,1,0,2009-05-19T00:00:00Z,9999-01-01T00:00:00Z
    		  Geospace Technologies Corporation,GS-11D seismometer,001,KQ01,10,0,0,0,0,0,0,0,2008-06-04T00:00:01Z,9999-01-01T00:00:00Z
    		--- 116,121 ----
```

**Comment by salichon** [comment]
hmm getting some inconsitencies in the sensor.csv @ozym :
Sorry 

> --- FAIL: TestConsistency (0.10s)
>     --- FAIL: TestConsistency/check_file_consistency:_sensors (0.01s)
>     	consistency_test.go:63: ../install/sensors.csv: **** csv file mismatch **** : 
>     	consistency_test.go:87: *** ../install/sensors.csv	2018-02-01 22:18:43.560776628 +0000
>     		--- /tmp/tst792725430	2018-02-01 22:18:55.348999994 +0000

**Comment by salichon** [comment]
@ozym OK!  thanks 
will do so :)

**Pull request merged**
