### PR TITLE
CHIT - Owenga -  Tsunami gauge datalogger change

### PR DESCRIPTION
**Pull request by salichon**
datalogger change

### CODE REVIEW

**Review by CBurton90 — APPROVED** [review]

**Review by mnaguit — CHANGES_REQUESTED** [review]
include firmware details for Centaur? @salichon

**Comment by salichon** [comment]
tghankis a lot! - somethin forgotten to be added  @mnaguit 
will do soon

**Comment by salichon** [comment]
Hello!
 @mnaguit @megankortink @CBurton90  - this should be complteet now
cheers

**Comment by mnaguit** [comment]
Hi @salichon 
Travis not happy because of the Reftek entry in `dataloggers.csv` ?

**Review by mnaguit — APPROVED** [review]

**Comment by salichon** [comment]
glitch  should be solved for @mnaguit  :)

**Comment by salichon** [comment]
Poke @CBurton90  :)

**Review by CBurton90 — APPROVED** [review]

**Review by megankortink — APPROVED** [review]
LGTM

**Pull request merged**
