### PR TITLE
MNKT tsunami sensors change

### PR DESCRIPTION
**Pull request by mnaguit**
from Druck PTX-1835 Serial Numbers: 10895481 & 10895484
to Druck PTX-1835 (registered as PTX-1830) Serial Numbers: 11847702 (for LC 40) & 11847701 (for LC 40)

### CODE REVIEW

**Comment by CBurton90** [comment]
The closing time seems rather recent to me? According to the ticket @ozym disabled both 40 and 41 streams on the 6th of April after erroneous data. 

https://github.com/GeoNet/tickets/issues/8160

**Comment by mnaguit** [comment]
I didn't know the history (e.g. that there is 8160 ticket). I only used the details provided in Equipment Change ticket.
Nevertheless, is there a closing time that you can suggest? @CBurton90

**Comment by mnaguit** [comment]
Based on archive check, BT* streams are available up to 2021.068. Would you like me to modify the closing to 09.March.2021?

```
"Key": "miniseed/2021/2021.068/MNKT.NZ/2021.068.MNKT.01-ACE.NZ.D"
 "Key": "miniseed/2021/2021.068/MNKT.NZ/2021.068.MNKT.01-LCQ.NZ.D"
 "Key": "miniseed/2021/2021.068/MNKT.NZ/2021.068.MNKT.01-LOG.NZ.D"
 "Key": "miniseed/2021/2021.068/MNKT.NZ/2021.068.MNKT.01-VEC.NZ.D"
 "Key": "miniseed/2021/2021.068/MNKT.NZ/2021.068.MNKT.01-VEM.NZ.D"
 "Key": "miniseed/2021/2021.068/MNKT.NZ/2021.068.MNKT.01-VEP.NZ.D"
 "Key": "miniseed/2021/2021.068/MNKT.NZ/2021.068.MNKT.01-VKI.NZ.D"
 "Key": "miniseed/2021/2021.068/MNKT.NZ/2021.068.MNKT.40-BTH.NZ.D"
 "Key": "miniseed/2021/2021.068/MNKT.NZ/2021.068.MNKT.40-BTL.NZ.D"
 "Key": "miniseed/2021/2021.068/MNKT.NZ/2021.068.MNKT.40-BTT.NZ.D"
 "Key": "miniseed/2021/2021.068/MNKT.NZ/2021.068.MNKT.40-BTZ.NZ.D"
 "Key": "miniseed/2021/2021.068/MNKT.NZ/2021.068.MNKT.40-CRX.NZ.D"
 "Key": "miniseed/2021/2021.068/MNKT.NZ/2021.068.MNKT.40-LTH.NZ.D"
 "Key": "miniseed/2021/2021.068/MNKT.NZ/2021.068.MNKT.40-LTT.NZ.D"
 "Key": "miniseed/2021/2021.068/MNKT.NZ/2021.068.MNKT.40-LTZ.NZ.D"
 "Key": "miniseed/2021/2021.068/MNKT.NZ/2021.068.MNKT.41-BTH.NZ.D"
 "Key": "miniseed/2021/2021.068/MNKT.NZ/2021.068.MNKT.41-BTL.NZ.D"
 "Key": "miniseed/2021/2021.068/MNKT.NZ/2021.068.MNKT.41-BTT.NZ.D"
 "Key": "miniseed/2021/2021.068/MNKT.NZ/2021.068.MNKT.41-BTZ.NZ.D"
 "Key": "miniseed/2021/2021.068/MNKT.NZ/2021.068.MNKT.41-CRX.NZ.D"
 "Key": "miniseed/2021/2021.068/MNKT.NZ/2021.068.MNKT.41-LTH.NZ.D"
 "Key": "miniseed/2021/2021.068/MNKT.NZ/2021.068.MNKT.41-LTT.NZ.D"
 "Key": "miniseed/2021/2021.068/MNKT.NZ/2021.068.MNKT.41-LTZ.NZ.D"
```

I'll change the closing time to this, based on the last data received from BT*:
**March 9, 2021/ 08:30UTC**

```
4 Trace(s) in Stream:
NZ.MNKT.41.BTH | 2021-03-08T23:59:13.771800Z - 2021-03-09T08:29:14.971800Z | 10.0 Hz, 306013 samples
NZ.MNKT.41.BTL | 2021-03-08T23:59:13.771800Z - 2021-03-09T08:29:14.971800Z | 10.0 Hz, 306013 samples
NZ.MNKT.41.BTT | 2021-03-08T23:59:13.771800Z - 2021-03-09T08:29:14.971800Z | 10.0 Hz, 306013 samples
NZ.MNKT.41.BTZ | 2021-03-08T23:59:13.771862Z - 2021-03-09T08:29:14.971862Z | 10.0 Hz, 306013 samples
```
MNKT_41_BT

**Comment by mnaguit** [comment]
Kindly review again. Thanks. @CBurton90 
FYI @megankortink @salichon

**Comment by CBurton90** [comment]
That would line up better with the sensor fault. I get 2021-03-07T06:00 UTC for the timestamp when the BT* stream was turned off. Looks like LT* was not turned off? 

Fedora-2021-04-27-13-49-52

**Review by CBurton90 — APPROVED** [review]

**Comment by mnaguit** [comment]
Noted with thanks @CBurton90 . 
On the other hand, we have to finalize the closing/opening time in the original equipment change next time. =)

**Review by salichon — CHANGES_REQUESTED** [review]
Seee https://github.com/GeoNet/tickets/issues/8433#issuecomment-827270650
to me we have data between March 2021 and April 2021 
 closing time  in March does not make sense to me :)

**Review by megankortink — APPROVED** [review]

**Comment by mnaguit** [comment]
Hi @salichon .
From the delta meeting,  I guess the opening & closing times are good in this PR? Thanks.

**Review by salichon — APPROVED** [review]
Hai

**Pull request merged**
