### PR TITLE
MKBS 20HN12Z to new loc 21HNEZ

### PR DESCRIPTION
**Pull request by salichon**
MKBS strong motion recorder moved from  bunker

### CODE REVIEW

**Review by mnaguit — CHANGES_REQUESTED** [review]
LC 21 has non-axial streams?

**Comment by CBurton90** [comment]
> LC 21 has non-axial streams?

yes it's outside in a cabinet now = can be oriented north @mnaguit

**Comment by mnaguit** [comment]
Yeah, that's all good @CBurton90 .
But for the metadata in streams.csv, LC 21 has no be non-axial. FYI @salichon .

**Comment by salichon** [comment]
thanks miss @mnaguit ! 
correction done :)

**Review by mnaguit — APPROVED** [review]

**Review by CBurton90 — APPROVED** [review]
🎉 🎉

**Pull request merged**
