### PR TITLE
HALS Strong Motion Cusp Reopened

### PR DESCRIPTION
**Pull request by salichon**
Strorng motion site 20 HN/BN reopened

### CODE REVIEW

**Comment by samgeonet** [comment]
looks like it doesn't like the zero at the end of the lat/longs

**Comment by salichon** [comment]
@samgeonet Sorry there is an issue related to the site coordinates. I ll check this - and correct

**Comment by salichon** [comment]
@ozym I think  travis doesn't like zeroes in coordinates :)
like -43.590820 Vs  -43.59082

**Comment by salichon** [comment]
hmm  i didn t mean to dismiss your review!

**Comment by salichon** [comment]
And then i ll proceed.
thanks

**Pull request merged**
