### PR TITLE
MBAZ changedatalogger

### PR DESCRIPTION
**Pull request by mnaguit**
change logger from Q330 to Q330S/6

### CODE REVIEW

**Comment by salichon** [comment]
- Reorder and sort  these lines

-  Remove the "<<<<<<"  :">>>>>"

- Resolve the conflict

> MBAZ_changedatalogger
> Kinemetrics,Q330S/6,6137,Motutapu Island,Borehole,2018-07-05T22:20:00Z,9999-01-01T00:00:00Z =======
>  Kinemetrics,Q330S/6,6136,Moumoukai,,2018-07-05T01:00:00Z,9999-01-01T00:00:00Z
> master

**Comment by mnaguit** [comment]
Hi @salichon and @peanutty 
I did resolved the conflict with the dataloggers.csv, by following @salichon 's advice.
Can both of you kindly review it again? Many thanks!

**Comment by salichon** [comment]
@peanut  - maybe  we ll talk about next thursday - but in case of resolved conflict - one reviewer  could be enough - Although this should be discussed with the Github Gurus :)

**Comment by mnaguit** [comment]
many thanks @salichon 👍

**Pull request merged**
