### PR TITLE
Sitelogs tweaks

### PR DESCRIPTION
**Pull request by elidana**
Hi Mark,

my minor tweaks included here, hope that was the clean way you were looking for.

### CODE REVIEW

**Comment by ozym** [comment]
@elidana can you pull in the changes to the sitelogs-remote branch into this PR. Some linting issues have been fixed/updated.

**Comment by elidana** [comment]
@ozym done...hopefully

**Comment by ozym** [comment]
@elidana could you do another pull just to cleanup another couple of linting issues and remove some old unrelated comments.

**Comment by elidana** [comment]
@ozym done, I've been waiting to see if travis build was passing now but it is still in progress

**Review by ozym — APPROVED** [review]

**Pull request merged**
