### PR TITLE
GNSS SCTY receiver and antenna swap

### PR DESCRIPTION
**Pull request by megankortink**
Waiting for antenna photos to complete this @CBurton90

### CODE REVIEW

**Review by CBurton90 — APPROVED** [review]
Unfortunately there is no clear photo of the Zephyr II serial number taken by the techs. I can confirm though that since we have a photo of the Zephyr II at RLTN then the antenna serial in the ticket for SCTY will definitely be the installed one : ).

**Review by elidana — APPROVED** [review]
lgtm!!!

**Comment by elidana** [comment]
@CBurton90 can you please review again? Antenna info are now added

**Review by CBurton90 — APPROVED** [review]
LGTM!

**Review by elidana — APPROVED** [review]

**Pull request merged**
