### PR TITLE
TitanSMA firmware updated

### PR DESCRIPTION
**Pull request by salichon**
As per identified Titan SMA deployed on the field
Version number assumed:  4.5.22
Cheers!

### CODE REVIEW

**Comment by salichon** [comment]
need to link the serial to the firmware version ...

**Comment by salichon** [comment]
Need to check is several version are present .. and when ..  damn  ...

**Comment by salichon** [comment]
- [ ] on hold until soft update completion

**Comment by salichon** [comment]
This should  do :) 
ready for review @CBurton90  you preferentially ;) 
@mnaguit guit (FYI mosly or saring an eye with Conrad ... )

**Review by CBurton90 — APPROVED** [review]
good stuff!

**Review by mnaguit — APPROVED** [review]
Thanks @salichon . I guess firmware.csv is not so sensitive with the closing-starting time unlike other .csv in delta (e.g. at least a difference of a minute or few seconds from closing to starting a new entry). 

Approving this now. I have full confidence in you and Conrad :blush:

**Pull request merged**
