### PR TITLE
Samgeonet alloy zephyr3

### PR DESCRIPTION
**Pull request by samgeonet**

### CODE REVIEW

**Comment by samgeonet** [comment]
Re-ordered as requested @elidana

**Comment by elidana** [comment]
looks good now, thanks! One last thing. Do you know how to squash all these commits into one?

**Comment by samgeonet** [comment]
As far as I'm aware you can't in branches

**Comment by staylorofford** [comment]
@elidana @samgeonet , we should be able to squash the commits before merge in GitHub - it is one of our merge powers.

**Comment by samgeonet** [comment]
Rebase away now

**Pull request closed without merging**
