### PR TITLE
DART Adding BPR metadata to delta for NZB, NZC, NZE, NZF, NZG, NZH, NZI

### PR DESCRIPTION
**Pull request by megankortink**
- Assumed the firmware was 02.07 for all BPR's (could check this with N$9 in the future). 
- Have only used an end date for the first NZF BPR as assuming that the BPR's associated with NZF (2nd deploy), NZH, and NZI are still operational - otherwise can change the end date for these to 9999-01-01
- start and end times from beta-geonet
- used the serial numbers that are reported on in the wiki https://wiki.geonet.org.nz/display/dmcops/DART+information+for+metadata (this could also be checked in the future using N$9 messages)

### CODE REVIEW

**Comment by ozym** [comment]
@megankortink looks like the serial numbers need to be in sort order (assume alphabetical not numerical), in the firmware.csv file and the recorders.csv file.


```
... // 274 identical lines
              	"Nanometrics,Centaur CTR4-6S,8003,4.5.20,2021-05-26T23:47:00Z,9999-01-01T00:00:00Z,",
              	"Nanometrics,Centaur CTR4-6S,8007,4.5.20,2021-05-21T04:36:00Z,9999-01-01T00:00:00Z,",
            + 	"Paroscientific,BPR Subsystem,141002,02.07,2019-12-16T00:00:00Z,2020-03-25T00:00:00Z,",
              	"Paroscientific,BPR Subsystem,141012,02.07,2019-12-22T00:00:00Z,9999-01-01T00:00:00Z,",
            - 	"Paroscientific,BPR Subsystem,2-190706,02.07,2020-09-18T00:00:00Z,9999-01-01T00:00:00Z,",
              	"Paroscientific,BPR Subsystem,141016,02.07,2019-12-13T00:00:00Z,9999-01-01T00:00:00Z,",
              	"Paroscientific,BPR Subsystem,141019,02.07,2019-12-19T00:00:00Z,9999-01-01T00:00:00Z,",
            - 	"Paroscientific,BPR Subsystem,141002,02.07,2019-12-16T00:00:00Z,2020-03-25T00:00:00Z,",
            - 	"Paroscientific,BPR Subsystem,200117-16,02.07,2020-08-31T00:00:00Z,9999-01-01T00:00:00Z,",
            + 	"Paroscientific,BPR Subsystem,190724,02.07,2020-09-04T00:00:00Z,9999-01-01T00:00:00Z,",
              	"Paroscientific,BPR Subsystem,190726,02.07,2020-09-10T00:00:00Z,9999-01-01T00:00:00Z,",
            - 	"Paroscientific,BPR Subsystem,190724,02.07,2020-09-04T00:00:00Z,9999-01-01T00:00:00Z,",
              	"Paroscientific,BPR Subsystem,191002-9,02.07,2020-09-08T00:00:00Z,9999-01-01T00:00:00Z,",
            + 	"Paroscientific,BPR Subsystem,2-190706,02.07,2020-09-18T00:00:00Z,9999-01-01T00:00:00Z,",
            + 	"Paroscientific,BPR Subsystem,200117-16,02.07,2020-08-31T00:00:00Z,9999-01-01T00:00:00Z,",
              	"Thales,ASHTECH MICROZ,ZR220021105,ZC00,2002-11-01T00:00:00Z,9999-01-01T00:00:00Z,",
              	"Thales,ASHTECH Z-XII3,LP00155,1E86,1996-05-23T00:00:00Z,1996-08-19T22:13:00Z,",
              	... // 1870 identical lines
```

**Comment by megankortink** [comment]
Ahhh thanks @ozym!! Elisabetta and I were just looking into it and wondering if it was a serial number thing, I'll probably change it tomorrow.

**Review by ozym — APPROVED** [review]
Looks good.

**Review by salichon — APPROVED** [review]
Swett thankx all good to me 👍

**Pull request merged**
