### PR TITLE
fix: update fge bias for EY2M

### PR DESCRIPTION
**Pull request by ozym**
Appears the offsets were in the wrong order, i.e. xyz -> zyx

Tested and the values come much closer, and the two sets at West Melton look closer in offsets as well.

### CODE REVIEW

**Comment by tanjapetersen** [comment]
Hi @ozym - the title says EYRM, but from what you mentioned before issue with the offsets is in the EY2M data??

**Comment by ozym** [comment]
> Hi @ozym - the title says EYRM, but from what you mentioned before issue with the offsets is in the EY2M data??

good catch, have updated title.

**Review by elidana — APPROVED** [review]
oh good catch @ozym !!! 
did check against photos taken at time of installation and happy with that fix. Apologies if I missed that while reviewing https://github.com/GeoNet/delta/pull/2025

**Comment by tanjapetersen** [comment]
nT values should be the same for EYWM and EY2M after the change
EYMvsEY2M

**Comment by elidana** [comment]
once metadata have been updated, the change should be "deployed to tilde" and data potentially reprocessed before that to be visible on the plots?

**Comment by ozym** [comment]
this doesn't get "deployed" to tilde.

**Comment by tanjapetersen** [comment]
I just wanted to point out a quick way to check if calibration is correct. Both instruments should record the same magnetic field

**Comment by elidana** [comment]
ha ha cool, all good and thanks for the tip!

**Pull request merged**
