### PR TITLE
SWNC recorder swap to EQR120

### PR DESCRIPTION
**Pull request by salichon**
EQR swap

### CODE REVIEW

**Comment by mnaguit** [comment]
Thanks @salichon .
Shall we close the CUSP3D on 12.Nov.2020, 00:28UTC? That is the last data available prior to the recent incoming data which I presumed is from EQR120 (14.Dec.2020,02:00UTC).

**Review by mnaguit — CHANGES_REQUESTED** [review]
Perhaps change the closing time to 12.Nov.2020,00:28UTC, as per based on available data (plots shown in the main ticket). Cheers!

**Comment by salichon** [comment]
Hello @mnaguit 
we close it at a date as long as  the instrument was there I reckon 
event though no data would be ever recorded.

**Comment by mnaguit** [comment]
> Hello @mnaguit
> we close it at a date as long as the instrument was there I reckon
> event though no data would be ever recorded.

Thanks @salichon .
I'll let go of the closing time for this (I do close the sensor along with the last data coming from it).
On the other note, can you update `recorders.csv` to show EQR120 instead of CUSP3D in one of the new entries? I think that's the error that Travis is seeing. Cheers!

**Review by mnaguit — APPROVED** [review]
Thanks @salichon

**Review by CBurton90 — APPROVED** [review]

**Pull request merged**
