### PR TITLE
Add water depth to the network station and site tables.

### PR DESCRIPTION
**Pull request by ozym**
This is just a strawman to see what changes would be needed to add a water "depth" column for network stations and sites. It doesn't include any downstream changes that would be needed.

### CODE REVIEW

**Comment by ozym** [comment]
Have added some extra options to check whether the elevation or depth have been set. This means we can remove the "9999" from the elevation and simply us a blank value for unknown elevations or depths.

**Review by staylorofford — APPROVED** [review]
Looks good. Combining these depths with the depth in the install/sensors.csv (and similar files) should allow all currently conceivable installations.

**Comment by ozym** [comment]
This just adds a blank entry where the "depth" column should be and adds Depth in the title.

**Comment by salichon** [comment]
-->> Checked consistency of the Water branch delta input files
- 79 recorders are showing a "depth" - i m suspecting building arrays - For instance STSB 21 woudl have a depth of 2.853 meters 
- 77 sensors with a depth  (comprising boreholes, hydrophones, and tide gauges) Here as well some rounding will be necessary (millimeters unit at depth

- 739 stations  "9999" depth (mostly temporary XX,SX , Strong motion or old stations )
- 35  stations "0" depth  DART, tide gauges Temporary XX 

This is looking consistent information

**Comment by salichon** [comment]
- Test.sh  and stationxml  created 
- Metadata information provided with <Elevation> and <Depth>

Output data are consistent after the change 

FYI @ozym @staylorofford

**Review by salichon — APPROVED** [review]
looks good to me 
thanks

**Pull request merged**
