### PR TITLE
GNSS FW Upgrades

### PR DESCRIPTION
**Pull request by meganmadley**
MNHR - 5944R40020 - 2022-10-19T20:34:28

### CODE REVIEW

**Comment by meganmadley** [comment]
TGRI - 5940R40036 - 2022-10-19T21:32:34

**Comment by aleks-spes** [comment]
VEXA - 5944R40026 - 2022-10-20T01:59:23

**Review by aleks-spes — APPROVED** [review]
Looks good!

**Comment by meganmadley** [comment]
@aleks-spes LGTM!

**Pull request merged**
