### PR TITLE
add dart response

### PR DESCRIPTION
**Pull request by ozym**
This PR adds the response generation updates needed for the DART response generation.

It assumes a gain or 1000  (i.e. 1 count = 1/1000 meters).
It assumes  two streams WTZ -900 or  1 / 900 sec (15m) and UTZ -15  or (1 / 15) (15s).

This can be tested by adding a recorder line, e.g.

```
Paroscientific,BPR Subsystem,BPR Subsystem,141002,NZA,40,0,,0,0,2019-12-22T00:00:00Z,9999-01-01T00:00:00Z
```

and associated streams:

```
NZA,40,-900,false,false,false,1990-04-22T00:00:05Z,9999-01-01T00:00:00Z
NZA,40,-15,false,false,false,1990-04-22T00:00:05Z,9999-01-01T00:00:00Z
```

### CODE REVIEW

**Comment by ozym** [comment]
This results in

```
./stationxml -networks TD -stations NZA | xmllint --format -
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<FDSNStationXML xmlns="http://www.fdsn.org/xml/station/1" schemaVersion="1.0">
  <Source>GeoNet</Source>
  <Sender>WEL(GNS_Test)</Sender>
  <Module>Delta</Module>
  <Created>2021-06-04T08:29:01</Created>
  <Network code="NZ" startDate="2019-12-22T00:00:00" endDate="9999-01-01T00:00:00" restrictedStatus="open">
    <Description>New Zealand National Seismograph Network</Description>
    <SelectedNumberStations>1</SelectedNumberStations>
    <Station code="NZA" startDate="2019-12-22T00:00:00" endDate="9999-01-01T00:00:00" restrictedStatus="open">
      <Description>National tsunami deep ocean network</Description>
      <Comment id="1">
        <Value>Location is given in WGS84</Value>
      </Comment>
      <Latitude datum="WGS84">-42.371</Latitude>
      <Longitude datum="WGS84">176.914</Longitude>
      <Elevation>0</Elevation>
      <Site>
        <Name>Offshore Wellington Hikurangi</Name>
        <Description>190 km south-east of Masterton</Description>
      </Site>
      <CreationDate>2019-12-22T00:00:00</CreationDate>
      <Channel code="VTZ" startDate="2019-12-22T00:00:00" endDate="9999-01-01T00:00:00" restrictedStatus="open" locationCode="40">
        <Comment id="1">
          <Value>Location estimation method is unknown</Value>
        </Comment>
        <Comment id="2">
          <Value>Location is given in WGS84</Value>
        </Comment>
        <Comment id="3">
          <Value>Sensor orientation not known</Value>
        </Comment>
        <Latitude datum="WGS84">-42.3707</Latitude>
        <Longitude datum="WGS84">176.9109</Longitude>
        <Elevation>0</Elevation>
        <Depth>0</Depth>
        <Azimuth>0</Azimuth>
        <Dip>0</Dip>
        <Type>CONTINUOUS</Type>
        <Type>GEOPHYSICAL</Type>
        <SampleRate>0.06666666666666667</SampleRate>
        <SampleRateRatio>
          <NumberSamples>1</NumberSamples>
          <NumberSeconds>15</NumberSeconds>
        </SampleRateRatio>
        <StorageFormat>Steim2</StorageFormat>
        <ClockDrift>0.0001</ClockDrift>
        <Sensor resourceId="Sensor#BPR Subsystem:141002">
          <Type>Bottom Pressure Recorder</Type>
          <Description>DART 4G BPR</Description>
          <Manufacturer>SAIC</Manufacturer>
          <Model>BPR Subsystem</Model>
          <SerialNumber>141002</SerialNumber>
          <InstallationDate>2019-12-22T00:00:00</InstallationDate>
        </Sensor>
        <DataLogger resourceId="Datalogger#BPR Subsystem:">
          <Type>Bottom Pressure Recorder</Type>
          <Description>DART 4G BPR</Description>
          <Manufacturer>SAIC</Manufacturer>
          <Model>BPR Subsystem</Model>
          <InstallationDate>2019-12-22T00:00:00</InstallationDate>
        </DataLogger>
        <Response>
          <InstrumentSensitivity>
            <Value>1000</Value>
            <Frequency>1</Frequency>
            <InputUnits>
              <Name>m</Name>
            </InputUnits>
            <OutputUnits>
              <Name>count</Name>
            </OutputUnits>
          </InstrumentSensitivity>
          <Stage number="1">
            <Coefficients resourceId="Coefficients#Water Height 15s" name="NZA.40.VTZ.2019.356.stage_1">
              <InputUnits>
                <Name>m</Name>
              </InputUnits>
              <OutputUnits>
                <Name>count</Name>
              </OutputUnits>
              <CfTransferFunctionType>DIGITAL</CfTransferFunctionType>
            </Coefficients>
            <Decimation>
              <InputSampleRate>0.06666666666666667</InputSampleRate>
              <Factor>1</Factor>
              <Offset>0</Offset>
              <Delay>0</Delay>
              <Correction>0</Correction>
            </Decimation>
            <StageGain>
              <Value>1000</Value>
              <Frequency>1</Frequency>
            </StageGain>
          </Stage>
        </Response>
      </Channel>
      <Channel code="UTZ" startDate="2019-12-22T00:00:00" endDate="9999-01-01T00:00:00" restrictedStatus="open" locationCode="40">
        <Comment id="1">
          <Value>Location estimation method is unknown</Value>
        </Comment>
        <Comment id="2">
          <Value>Location is given in WGS84</Value>
        </Comment>
        <Comment id="3">
          <Value>Sensor orientation not known</Value>
        </Comment>
        <Latitude datum="WGS84">-42.3707</Latitude>
        <Longitude datum="WGS84">176.9109</Longitude>
        <Elevation>0</Elevation>
        <Depth>0</Depth>
        <Azimuth>0</Azimuth>
        <Dip>0</Dip>
        <Type>CONTINUOUS</Type>
        <Type>GEOPHYSICAL</Type>
        <SampleRate>0.0011111111111111111</SampleRate>
        <SampleRateRatio>
          <NumberSamples>1</NumberSamples>
          <NumberSeconds>900</NumberSeconds>
        </SampleRateRatio>
        <StorageFormat>Steim2</StorageFormat>
        <ClockDrift>0.0001</ClockDrift>
        <Sensor resourceId="Sensor#BPR Subsystem:141002">
          <Type>Bottom Pressure Recorder</Type>
          <Description>DART 4G BPR</Description>
          <Manufacturer>SAIC</Manufacturer>
          <Model>BPR Subsystem</Model>
          <SerialNumber>141002</SerialNumber>
          <InstallationDate>2019-12-22T00:00:00</InstallationDate>
        </Sensor>
        <DataLogger resourceId="Datalogger#BPR Subsystem:">
          <Type>Bottom Pressure Recorder</Type>
          <Description>DART 4G BPR</Description>
          <Manufacturer>SAIC</Manufacturer>
          <Model>BPR Subsystem</Model>
          <InstallationDate>2019-12-22T00:00:00</InstallationDate>
        </DataLogger>
        <Response>
          <InstrumentSensitivity>
            <Value>1000</Value>
            <Frequency>1</Frequency>
            <InputUnits>
              <Name>m</Name>
            </InputUnits>
            <OutputUnits>
              <Name>count</Name>
            </OutputUnits>
          </InstrumentSensitivity>
          <Stage number="1">
            <Coefficients resourceId="Coefficients#Water Height 15m" name="NZA.40.UTZ.2019.356.stage_1">
              <InputUnits>
                <Name>m</Name>
              </InputUnits>
              <OutputUnits>
                <Name>count</Name>
              </OutputUnits>
              <CfTransferFunctionType>DIGITAL</CfTransferFunctionType>
            </Coefficients>
            <Decimation>
              <InputSampleRate>0.0011111111111111111</InputSampleRate>
              <Factor>1</Factor>
              <Offset>0</Offset>
              <Delay>0</Delay>
              <Correction>0</Correction>
            </Decimation>
            <StageGain>
              <Value>1000</Value>
              <Frequency>1</Frequency>
            </StageGain>
          </Stage>
        </Response>
      </Channel>
    </Station>
  </Network>
</FDSNStationXML>
```

**Comment by salichon** [comment]
Thanks @ozym  
- The **Delta** convention for very low sampling rate is `-xxx` negative to signify `1/xxx` 
in teresting :) 
- The choice of the channel codes is from the mini-seed naming convention  

Shall we considered these streams 
  - `axial` (true)  _does not make too much sense though_
  - `triggered` (true) which makes sense I reckon

**Comment by ozym** [comment]
the `triggered` bit is sort of okay, but when (if) the data is returned it will in theory not be triggered. This is a hold over from SEED conventions converted into StationXML so not sure how important it is.

**Comment by salichon** [comment]
While inspecting the files 
Does "StorageFormat:  "Steim2"" implies these data format  set will  be a `miniseed` ouput ?

**Comment by salichon** [comment]
- `type: CG` is for continuous Geophysical as far as i remember  (kept like this, with regards to continuous long trime series,  and nnot having the data as  triggered )

With regards to the sample rates  and measure : 
`label: VT` and  `label: UT` are respectively correponding to the SEED  sampling (U,V) and measure type for "Tide" (T) (for us `Tsunami`)

**Comment by ozym** [comment]
> While inspecting the files
> Does "StorageFormat: "`Steim2`"" implies these data format set will be a `miniseed` ouput ?

This is just a SEED thing, this isn't used in the latest versions of StationXML (just historical).

**Review by salichon — APPROVED** [review]
great :)

**Review by salichon — COMMENTED** [review]
@ozym are we `V` or `W` as stated in the ticket ? 

`W` as Very Very  long  period instead  ? :) 


--->> Sorted now : https://github.com/GeoNet/delta/pull/1098#pullrequestreview-677960021

**Comment by ozym** [comment]
@salichon http://docs.fdsn.org/projects/source-identifiers/en/v1.0/channel-codes.html#band-code

**Comment by salichon** [comment]
From above:   i m a bit confused but not a big deal :) 



V | Very Long Period | &gt;= 0.1 to &lt; 1 | &nbsp;
-- | -- | -- | --
U | Ultra Long Period | &gt;= 0.01 to &lt; 0.1 | &nbsp;
W | Ultra-ultra Long Period | &gt;= 0.001 to &lt; 0.01

**Comment by elidana** [comment]
coming late to the party (and the experts are already on it), but we should save this conversation in our documentation

**Comment by salichon** [comment]
Example(s) test DART  to Delta:

- Adding  streams and recorders for NZA Requires 
  - [ ] Confirmed Asset Serial Number related to the NZA mount
  
  - [ ] recorder installation time and description  
  (consistent to delta and as in https://github.com/GeoNet/delta/pull/1093#issue-661197357  ) 
  - [ ] streams installation time and description  (consistent to delta)

**Comment by salichon** [comment]
PR  https://github.com/GeoNet/delta/pull/1098#pullrequestreview-677960021
 The convention are all good in delta now 
**UTZ | Ultra Long Period | &gt;= 0.01 to &lt; 0.1 | 1/15 Hz** 
**WTZ  | Ultra-ultra Long Period | &gt;= 0.001 to &lt; 0.01| 1/900 Hz**

**Comment by megankortink** [comment]
@elidana in regards to your above comment Sam has now got most of these details here https://github.com/GeoNet/delta/pull/1108/files

**Comment by elidana** [comment]
thanks @megankortink (and Sam :) )

**Pull request merged**
