### PR TITLE
Trillium Compact Posthole 20s (TC20-PH2) response

### PR DESCRIPTION
**Pull request by CBurton90**
Please see the below document for reference.

[TrilliumCompact_UserGuide_16889R10 (1).pdf](https://github.com/GeoNet/delta/files/8722850/TrilliumCompact_UserGuide_16889R10.1.pdf)

A Nanometrics broadband posthole sensor of 20s corner period. Similar in style to the 120s model but with different paz values for the first two entries and a sensitivity of 753.1 V/m/s.

Mistakenly deployed at WTAZ- waiatarua at location code 12 where a 120s model should have been used. Apologies for the inconvenience. This PR assume delta naming of `Trillium Compact 20PH-2` for future installs.

### CODE REVIEW

**Comment by CBurton90** [comment]
image

**Comment by salichon** [comment]
so it is a broadband with a smaller frequency range  in the lower end (0.05 Hz)  - if so this will do the same for the task.

**Review by salichon — APPROVED** [review]
this is looking legit to the docs :+1: 
thanks

**Comment by CBurton90** [comment]
> so it is a broadband with a smaller frequency range in the lower end (0.05 Hz) - if so this will do the same for the task.

@salichon yes correct

**Comment by CBurton90** [comment]
@ozym bump on this one please then we can merge the network PR : )

**Review by ozym — APPROVED** [review]

**Comment by CBurton90** [comment]
@salichon please merge ; )

**Comment by salichon** [comment]
i comply and submit 
 @CBurton90
  no  Pb 
  :+1

**Pull request merged**
