### PR TITLE
update from db

### PR DESCRIPTION
**Pull request by ozym**
Update from delta, a couple  datalogger time overlaps in the db have been adjusted by hand.

### CODE REVIEW

**Comment by ozym** [comment]
@elidana you may want to check delta legacy regarding RGOP. This is basically a dump of what's in there.

I'll have a look at the visited sites, it may just be related to the current request doing a join with an installed antenna etc.

**Comment by elidana** [comment]
Hi @ozym ,

I've check the "delta legacy" regarding RGOP.
It's weird, I'm not sure what is happening here and I might need a bit more knowledge on how the database extraction is done.
The Delta oracle database has the information for both sessions. Below the _DELTA_CGPS_SESSION_ table entry for the receiver ID n. 38, which corresponds to rec. sn ``

```
CGPS_SESSION_ID	ELEVATION_MASK	OBSERVATION_INTERVAL	POSITION_INTERVAL	SESSION_ID_STRING	START_TIME_STAMP	STOP_TIME_STAMP	INSTALLED_CGPS_ANT_ID	CGPS_NAME_FORMAT_ID	RINEX_HEAD_COMM_ID	OPERATOR_ID	INSTALLED_MET_SENSOR_ID	CGPS_RAW_DATA_FORMAT_ID	CGPS_RECEIVER_ID
30	4	30	300	a	20/04/2006 02:00:00	4/01/2007 02:00:00	69	2	2	1		4	38
31	4	1	300	b	20/04/2006 02:00:00	4/01/2007 02:00:00	69	2	2	1		4	38
538	4	30	300	a	14/06/2007 00:40:00	24/03/2017 02:28:28	132	2	2	1		4	38
539	4	1	300	b	14/06/2007 00:40:00	24/03/2017 02:28:28	132	2	2	1		4	38
```

I can't find anything wrong here (but I'm not excluding that I'm missing something!)

**Comment by ozym** [comment]
@elidana yes looks tricky. I suspect the query is getting tangled up due to the receiver overlap at RGOP:

```
> Date: 2007-06-13 23:00:01 to 2017-03-24 03:00:00 
> Equipment Info: Trimble  NetRS   4438238767   9905   EQC 
> Date: 2007-02-21 20:00:01 to 2007-06-14 03:00:00 
> Equipment Info: Trimble  NetRS   4445240302   10494   EQC 
```

**Comment by elidana** [comment]
oooh! Haven't noticed that error

From the archived _data_, the first epoch was logged on `2007-06-14T00:38:00` (see below)
I'll update the oracle database accordingly.

Thanks for spotting that!


/geonet/gps/raw/2007/165
```
[elidana@rally 165]% teqc -tr d RGOP_20070614_003800.dat | head -30
? Error ? translation of 'RGOP_20070614_003800.dat' may have started with GPS week 1942 rather than 1431
	(try using '-week 1431' option)
! Notice ! GPS week initially set= 1431
     2.11           OBSERVATION DATA    G (GPS)             RINEX VERSION / TYPE
teqc  2016Nov7                          20170331 01:39:05UTCPGM / RUN BY / DATE
Linux 2.4.21-27.ELsmp|Opteron|gcc -static|Linux x86_64|=+   COMMENT
BIT 2 OF LLI FLAGS DATA COLLECTED UNDER A/S CONDITION       COMMENT
CREF0001                                                    MARKER NAME
RGOP                                                        MARKER NUMBER
-Unknown-           -Unknown-                               OBSERVER / AGENCY
4438238767          TRIMBLE NETRS       1.1-5               REC # / TYPE / VERS
00000000            TRM41249.00     NONE                    ANT # / TYPE
 -5034042.3815   302933.5204 -3892109.7881                  APPROX POSITION XYZ
        0.0000        0.0000        0.0000                  ANTENNA: DELTA H/E/N
     1     1                                                WAVELENGTH FACT L1/2
     7    L1    L2    C1    P1    P2    S1    S2            # / TYPES OF OBSERV
    14                                                      LEAP SECONDS
 SNR is mapped to RINEX snr flag value [0-9]                COMMENT
  L1 & L2: min(max(int(snr_dBHz/6), 0), 9)                  COMMENT
  2007     6    14     0    38    0.0000000     GPS         TIME OF FIRST OBS
                                                            END OF HEADER
 07  6 14  0 38  0.0000000  0  3G09G17G20
    -43412.42257    -31158.19555  23063699.1484                   23063696.1054
        43.7504         31.5004
     55418.69558     28546.60956  20572033.8674                   20572029.9304
        50.5004         41.7504
     29533.35957     13258.21554  23563377.4224                   23563373.5984
        44.2504         25.0004
 07  6 14  0 38 30.0000000  0  3G09G17G20
    -69839.34447    -51750.60944  23058670.3134                   23058667.4384
        43.5004         29.5004
    102614.05548     65322.19146  20581015.0084                   20581011.0474
        50.7504         41.7504
```

**Comment by ozym** [comment]
@elidana Actually it may be due to a constraint that sessions less than 30s are ignored ...

**Comment by elidana** [comment]
I'm getting an headache here ! :-)

btw, fwiw, and looking again at the raw data/vs delta , the problem seems to be related to the place associated with the receiver sn `4445240302`

The last data recorded/archived at RGOP by this receiver is: 
/geonet/gps/raw/2007/160/RGOP_20070609_020000.dat

that ends at  `2007-06-09T02:59:30`

so we can probably modify this entry:
> Date: 2007-02-21 20:00:01 to 2007-06-14 03:00:00 
> Equipment Info: Trimble  NetRS   4445240302   10494   EQC 

into this:
> Date: 2007-02-21 20:00:01 to 2007-06-13 23:00:00 
> Equipment Info: Trimble  NetRS   4445240302   10494   EQC 

(the change is the "to" date)

**Pull request merged**
