### PR TITLE
add lrdcp pilot dataloggers to delta/install/dataloggers.csv - https://github.com/GeoNet/tickets/issues/8076

### PR DESCRIPTION
**Pull request by rumachan**
https://github.com/GeoNet/tickets/issues/8076

### CODE REVIEW

**Comment by ozym** [comment]
@rumachan the `Role` entry may not be needed unless you have multiple dataloggers at a site, so I think in this case you might have a role that says : "Water Level", and the "Gas Chemistry"  for two loggers (of the same type and model) at the same place (note it's the installed sensor  that is attached to a geographical location). The Role can then be used in the connections file to match the dataloggers with sensors  (a Role of "", is perfectly valid).

**Comment by rumachan** [comment]
Have changed role to be blank.

**Review by ricardojohansson — DISMISSED** [review]

**Comment by ozym** [comment]
@rumachan the dataloggers will need to be listed in alphabetical order, i.e. 3066 needs to come first.

Also there will need to be entries in the assets directory, this is often done at purchase, in the dataloggers.csv file there.  The asset number (if known) is only used as a cross reference rather than for any equipment tracking use.

**Comment by rumachan** [comment]
I do not understand why the Travis CI fails. Can you help? @ozym

**Comment by ozym** [comment]
@rumachan see above comments, this is the error message (first one is sort order, second missing assests).

```
--- FAIL: TestConsistency (0.07s)
    --- FAIL: TestConsistency/check_file_consistency:_dataloggers (0.00s)
        consistency_test.go:39: unexpected dataloggers.csv content -got/+exp
              strings.Join({
              	"Make,Model,Serial,Place,Role,Start Date,End Date",
            - 	"Campbell Scientific,CR6,4117,Upper Tama Lake,,2019-03-12T03:30:00Z,9999-01-01T00:00:00Z",
            - 	"Campbell Scientific,CR6,4115,Ruapehu Crater Lake,,2018-05-03T00:00:00Z,9999-01-01T00:00:00Z",
            - 	"Campbell Scientific,CR6,4111,Fox Glacier Alpine Gardens,,2019-02-06T00:00:00Z,9999-01-01T00:00:00Z",
            + 	"Campbell Scientific,CR6,3066,Lower Te Maari Fumarole 15,,2018-08-10T00:00:00Z,9999-01-01T00:00:00Z",
            + 	"Campbell Scientific,CR6,4109,White Island Fumarole 13,,2018-09-13T01:30:00Z,9999-01-01T00:00:00Z",
              	"Campbell Scientific,CR6,4110,Upper Te Maari Fumarole 6,,2018-08-28T00:00:00Z,9999-01-01T00:00:00Z",
            - 	"Campbell Scientific,CR6,4109,White Island Fumarole 13,,2018-09-13T01:30:00Z,9999-01-01T00:00:00Z",
            - 	"Campbell Scientific,CR6,3066,Lower Te Maari Fumarole 15,,2018-08-10T00:00:00Z,9999-01-01T00:00:00Z",
            + 	"Campbell Scientific,CR6,4111,Fox Glacier Alpine Gardens,,2019-02-06T00:00:00Z,9999-01-01T00:00:00Z",
            + 	"Campbell Scientific,CR6,4115,Ruapehu Crater Lake,,2018-05-03T00:00:00Z,9999-01-01T00:00:00Z",
              	"Campbell Scientific,CR6,4116,Waimangu Inferno Crater,,2017-11-07T00:00:00Z,9999-01-01T00:00:00Z",
            + 	"Campbell Scientific,CR6,4117,Upper Tama Lake,,2019-03-12T03:30:00Z,9999-01-01T00:00:00Z",
              	"GNS Science,EARSS/16,204,Taranaki Emergency Management Office,EARSS Network,1993-12-14T23:51:00Z,2002-09-18T21:00:00Z",
              	"GNS Science,EARSS/16,207,Chateau Observatory,EARSS Network,1993-11-12T03:00:00Z,1998-06-11T09:00:00Z",
              	... // 1286 identical lines
              }, "\n")
--- FAIL: TestDataloggers_Assets (0.01s)
    --- FAIL: TestDataloggers_Assets/check_for_missing_datalogger_assets (0.01s)
        dataloggers_test.go:96: unable to find datalogger asset: CR6 [3066]
        dataloggers_test.go:96: unable to find datalogger asset: CR6 [4109]
        dataloggers_test.go:96: unable to find datalogger asset: CR6 [4110]
        dataloggers_test.go:96: unable to find datalogger asset: CR6 [4111]
        dataloggers_test.go:96: unable to find datalogger asset: CR6 [4115]
        dataloggers_test.go:96: unable to find datalogger asset: CR6 [4116]
        dataloggers_test.go:96: unable to find datalogger asset: CR6 [4117]
FAIL
```

**Comment by rumachan** [comment]
@ozym Thanks that helps. 1. Didn't realise all entries had to be in exact alphabetical order, in effect order of serial number. 2. Didn't know assets were listed elsewhere. Will add the logger to assets before proceeding with dataloggers. Thank you.

**Comment by ozym** [comment]
The ordering is to help with git merges, and the assets is strictly not needed but it's used as a double check to try and avoid serial number mistakes. Can't install something if it doesn't exist.

**Comment by elidana** [comment]
Hi @rumachan , just noticed this pr. Is it still valid or did you manage to include the info with other pull requests?

**Comment by rumachan** [comment]
Thanks Elisabetta,

I had completely forgotten about that. Yes have it through other means. I closed the pull request.

SS
________________________________

**Pull request closed without merging**
