### PR TITLE
antenna clock firmware upgraded on 38 strong motion recorders

### PR DESCRIPTION
**Pull request by elidana**
Hi @mnaguit ,

this is to record another bunch of garmin antennas firmware upgrades on the CUSP3D strong motion recorders.

The firmware upgrades are fixing the antenna clocks.

Based on info from the field technicians, those are the stations and time when firmware was upgraded
```
ARPS , 2021/10/08 07:30 NZDT
BTWS , 2021/06/10 11:00 NZDT
FGPS , 2021/08/05 10:00 NZST
FJDS , 2021/08/03 10:00 NZST
GHHS , 2021/06/28 10:30 NZDT
GWTS , 2021/06/28 11:30 NZDT
HAFS , 2021/08/03 12:00 NZST
HMCS , 2021/08/05 15:00 NZST
KLDS , 2021/06/11 08:30 NZDT
KOKS , 2021/08/05 14:00 NZST
LIRS , 2021/06/02 11:30 NZDT
MKVS , 2021/06/02 13:40 NZDT
MGCS , 2021/06/11 14:30 NZDT
MCAS , 2021/10/07 16:00 NZDT
NCBS , 2021/06/10 09:00 NZDT
NELS , 2021/06/10 10:00 NZDT
NLMS , 2021/06/10 08:00 NZDT
ORCS , 2021/07/26 14:30 NZDT
OPSS , 2021/07/15 11:00 NZDT
PFAS , 2021/06/04 10:40 NZDT
POLS , 2021/06/04 11:00 NZDT
QCCS , 2021/06/11 12:30 NZDT
RDCS , 2021/10/07 13:00 NZDT
RPCS , 2021/07/29 14:30 NZDT
SEVS , 2021/06/02 10:30 NZDT
THHS , 2021/07/26 13:00 NZDT
TSFS , 2021/06/10 17:00 NZDT
NPCS , 2021/07/15 10:00 NZDT
TDHS , 2021/06/29 11:30 NZDT
TKHS , 2021/07/29 10:30 NZDT
TIRS , 2021/07/29 12:30 NZDT
TTHS , 2021/07/30 10:30 NZDT
TRTS , 2021/03/11 12:00 NZDT
VUWS , 2021/06/04 16:00 NZDT
WAIS , 2021/07/30 09:30 NZDT
WVFS , 2021/06/11 11:00 NZDT
WNPS , 2021/08/06 10:04 NZST
WBCS , 2021/10/05 15:00 NZDT
```

Can you please double check all entries are correct? 

/cc @CBurton90 @salichon

### CODE REVIEW

**Comment by mnaguit** [comment]
Thanks @elidana 
Quite a lengthy changes in there. Will do the review for closing dates and other add-ons.
I'll just finish PAU-related alignment on structural arrays.

**Comment by elidana** [comment]
no rush at all @mnaguit , feel free to review when is most convenient for you, this one can sit here for a while :)

**Review by mnaguit — COMMENTED** [review]
_1st round of review:_ 

These are only observations, no need to change anything from herein:

- firmware start-closing do not match the start-end times of the recorders as listed in `install/recorders.csv`
- We can further improve the procedure to track the changes, by consistently using the same metadata (e.g. recorder serial number instead of station name or site code in the main ticket) 

Here are the following observations that may need changes:
- random checking in start date in UTC
    - for MKVS (42020), should the start date in UTC be: 02.June.2021/01:40UTC ?
    - for VUWS (42271), start date should be: 04.June.2021/04:00UTC?
    - for TDHS (42017),  start date should be: 28.June.2021/23:30UTC?
    - for GHHS (42290), start date should be: 27.June.2021/22:30UTC?

NOTE: I'll give it a second review, as needed. Probably I have missed a lot of stuff in here as there are loads to read in the ticket & metadata to match with as well.

**Comment by elidana** [comment]
Hi @mnaguit , as far as I understand:
- those firmware upgrades are not necessarily matching with recorder upgrades. The firmware was upgraded on the GPS antenna that provides clock information to the recorder;
- I will update my code to also show recorder serial number , for easy of review.
- I will review the timestamp, agree that GHHS should be an hour later (the list I used as input was using NZDT instead of NZST, I'll check those)

Just as an example, this is a graph showing the improvement in timing for GHHS. The clock start to be more stable around 11am NZ time, which roughly match with what proposed in this pr. 
image


Nevertheless, those times are not precise, as I've used the info provided by field technicians. @ozym suggested that is also possible to double check directly from the data, I'll try have a look as well.

**Review by mnaguit — APPROVED** [review]
Thanks @elidana 
No need to change, using the approximate time of firmware upgrade based on what's provided in the main ticket.
Approving this PR now. Have cross checked the recorder serial number against the station code, as per summary in this PR. Looks like all stations are accounter for.

**Comment by elidana** [comment]
thanks @mnaguit 
I was just about to commit the updated timestamps, as there was an error in the list in terms of daylight saving times....a few minutes away :)

**Review by mnaguit — APPROVED** [review]
Ok. Will trust that the changes in start date/time for NZT match the corresponding UTC time.

**Comment by elidana** [comment]
update now pushed (sorry, was in a meeting).
those are the station - recorder serial number - UTC timestamp included in the pr

```
ARPS 42167 2021-10-07T18:30:00
BTWS 42266 2021-06-09T23:00:00
FGPS 42105 2021-08-04T22:00:00
FJDS 42153 2021-08-02T22:00:00
GHHS 42290 2021-06-27T22:30:00
GWTS 42036 2021-06-27T23:30:00
HAFS 42152 2021-08-03T00:00:00
HMCS 42165 2021-08-05T03:00:00
KLDS 42019 2021-06-10T20:30:00
KOKS 42170 2021-08-05T02:00:00
LIRS 42107 2021-06-01T23:30:00
MCAS 42272 2021-10-07T03:00:00
MGCS 42253 2021-06-11T02:30:00
MKVS 42020 2021-06-02T01:40:00
NCBS 42267 2021-06-09T21:00:00
NELS 42268 2021-06-09T22:00:00
NLMS 42041 2021-06-09T20:00:00
NPCS 42156 2021-07-14T22:00:00
OPSS 42038 2021-07-14T23:00:00
ORCS 42289 2021-07-26T02:30:00
PFAS 42228 2021-06-03T22:40:00
POLS 42229 2021-06-03T23:00:00
QCCS 42252 2021-06-11T00:30:00
RDCS 42261 2021-10-07T00:00:00
RPCS 42257 2021-07-29T02:30:00
SEVS 42269 2021-06-01T22:30:00
TDHS 42017 2021-06-28T23:30:00
THHS 42158 2021-07-26T01:00:00
TIRS 42276 2021-07-29T00:30:00
TKHS 42274 2021-07-28T22:30:00
TRTS 42154 2021-03-11T00:00:00
TSFS 42007 2021-06-10T05:00:00
TTHS 42277 2021-07-29T22:30:00
VUWS 42271 2021-06-04T04:00:00
WAIS 42275 2021-07-29T21:30:00
WBCS 42270 2021-10-05T02:00:00
WNPS 42040 2021-08-05T22:04:00
WVFS 42247 2021-06-10T23:00:00
```

/cc @salichon

**Comment by mnaguit** [comment]
No worries @elidana 
I have already matched the recorder serial number with the station code. 
Changes look good, as per my review approval.

**Pull request merged**
