### PR TITLE
HDWS20 New obsidian, New BN stream

### PR DESCRIPTION
**Pull request by salichon**
recorder replacement

### CODE REVIEW

**Comment by salichon** [comment]
see ticket https://github.com/GeoNet/tickets/issues/1790

**Comment by salichon** [comment]
Hello @ozym @jristau @peanutty 
Richard s fixed the conflict related to the new Triggerred field in the streams.csv file
This allows this branch to be merged, once your reviews are made 
CC/ FYI @nbalfour: new delta  field for triggered (or not) streams (esp. for 200HZ strong motion)  

Thanks
Cheers
jerome

**Comment by peanutty** [comment]
@nbalfour @ozym given the fact that we stopped retrieving data from the ETNA long ago, do we want to have it removed as of when we last collected from it?

**Comment by salichon** [comment]
I ll proceed today 
thanks for the review

**Pull request merged**
