### PR TITLE
TRWZ changedatalogger

### PR DESCRIPTION
**Pull request by mnaguit**
change from Q330/3 to Q330S/3

### CODE REVIEW

**Comment by ozym** [comment]
@mnaguit @salichon  I have recovered the initial data from the baler and uploaded to fdsn etc.

**Comment by mnaguit** [comment]
Thanks @ozym 👍

**Comment by mnaguit** [comment]
Hi @salichon 
Does a day plot like this helps in searching for data gaps?

dayplot_trwz

**Comment by salichon** [comment]
@mnaguit yup all good :)

**Pull request merged**
