### PR TITLE
New Nanometrics Titan Accelerometer TACCL-N1 (standalone) and Titan Borehole Accelerometer TACCL-BH1

### PR DESCRIPTION
**Pull request by CBurton90**
Planned for deployment at the Christchurch Botanical Gardens Borehole. I'll begin adding response information next week, should be the same paz as a TitanSMA minus the digitiser response.

### CODE REVIEW

**Review by salichon — CHANGES_REQUESTED** [review]
ola l @CBurton90 
- This needs a "," line 641  you re missing a field 
- i would swap  the 2 lines 

have a good WE

**Comment by CBurton90** [comment]
@salichon thanks, updated

**Review by mnaguit — APPROVED** [review]
Looks good. Thanks @CBurton90

**Review by ozym — CHANGES_REQUESTED** [review]
Can we drop the "Borehole" that's more a description rather than a model name/number unless it says that on the spec sheet of course.

**Comment by CBurton90** [comment]
> Can we drop the "Borehole" that's more a description rather than a model name/number unless it says that on the spec sheet of course.

@ozym done

**Review by mnaguit — APPROVED** [review]

**Review by ozym — APPROVED** [review]

**Review by salichon — APPROVED** [review]

**Comment by ozym** [comment]
For reference in the spec sheet.

```
AVAILABLE MODELS
TACCL-N1: Standard Model
TACCL-V1: Vertical Mount Model 
```

**Comment by ozym** [comment]
@CBurton90 think this can be merged now, this is just updating the assets which we have and will install at some point.

**Pull request merged**
