### PR TITLE
white_seismic_close

### PR DESCRIPTION
**Pull request by rumachan**
Closing White Island seismic stations and related files.

### CODE REVIEW

**Review by elidana — APPROVED** [review]
looks good, thanks @rumachan !
/cc @Thomas-Benson

**Comment by Thomas-Benson** [comment]
Hi @rumachan, Just checked this, and there are two open seismic dataloggers you may want to close too:
```
Kinemetrics,Q330S/6,5574,White Island - South Rim,,2014-07-04T00:00:01Z,9999-01-01T00:00:00Z
Kinemetrics,Q330S/6,6055,White Island - Summit,,2017-02-27T00:10:01Z,9999-01-01T00:00:00Z
```
(and one for the envirosensor at WI227 - White Island Fumarole, but that'll be a different PR)

**Comment by rumachan** [comment]
Bugger forgot those - thanks @Thomas-Benson

**Review by Thomas-Benson — APPROVED** [review]
LGTM!

**Pull request merged**
