### PR TITLE
MPSS EQR120 Firmware Upgrade

### PR DESCRIPTION
**Pull request by Thomas-Benson**
- Upgraded EQR120 (46505) to latest firmware version 2.3.2
 - Streams affected: MPSS LC 21 HN-12Z

### CODE REVIEW

**Review by mnaguit — DISMISSED** [review]

**Comment by CBurton90** [comment]
I assume the serial number will need an update here, I've asked Paul in the main ticket so maybe pause on this until we have that info. Cheers.

**Comment by Thomas-Benson** [comment]
My bad, I read your comment as just a firmware update sorry.

**Comment by CBurton90** [comment]
@Thomas-Benson Haha all good, there was no new SN in the ticket anyway : (, fyi fw updates from the m001... version to 2.3.2 always require swapping the unit out (SN change)!

**Comment by mnaguit** [comment]
Thanks @CBurton90 & @Thomas-Benson , will review this again once the new EQR120 (46534) is included

**Comment by Thomas-Benson** [comment]
Sorry for the misunderstanding, this should be ready to go now @CBurton90 @mnaguit

**Review by mnaguit — APPROVED** [review]
Thanks @Thomas-Benson 👍

**Review by CBurton90 — APPROVED** [review]

**Pull request merged**
