### PR TITLE
chore: add SEPCHOKE antenna model for GNSS sitelogs production

### PR DESCRIPTION
**Pull request by elidana**
Hi @ozym ,

we have a new antenna model now installed and need to update the GNSS sitelogs generation accordingly. 

The antenna graph has been copied from the official IGS file (link is also updated here, as the old IGS website was deprecated a while ago).

@aleks-spes can you also please double check the graph and that I picked the correct one for TGHM? 

@ozym , hope I added this in all the right places. There's a parallel pr to actually install the new antenna at the site

### CODE REVIEW

**Review by ozym — APPROVED** [review]
looks okay to me.

**Comment by aleks-spes** [comment]
Hey @elidana ! Thank you looking into this.
There is one thing which is unclear to me. This antenna has a dome, so should we use a diagram of antenna with dome or without in this config file?

**Comment by aleks-spes** [comment]
Something like:
```

SEPCHOKE_B3E6   SPKE

                            |                               <--  0.3977
                            |
                            |
                           | |
                           | |
                          |   |
                          |   |
                          |   |
                        ---------                           <--  0.2847
                       /         \
                      /           \
                     /             \
                    /               \
                   /                 \
                  /                   \
                 /                     \
                /                       \
               /                         \
              /                           \
             /                             \
            /                               \
           /                                 \
          /                                   \
         /                                     \
        /                                       \
       /                                         \
      /                                           \
     /                                             \
    /                                               \
   /                                                 \
  /                                                   \
 /                   ---------------                   \    <--  0.1550
/                  /                 \                  \   <--  0.128  
|                 |                   |                 |
|+-----------------------------------------------------+|   <--  0.1080  TCR
||                                                     ||
||                                                     ||
||                                                     ||
||                                                     ||
++-----------------+-----------------+-----------------++   <--  0.0480  BCR
                   |                 |
                   |                 |
                   |                 |
                   +--------x--------+                      <--  0.0000  BPA=ARP
                   <--    0.1210   -->
 <--                      0.3630                     -->
<---                      0.3734                     --->
```

**Comment by elidana** [comment]
oh thank you!! very good point. I could not find the diagram with radome in the IGS `antenna.gra` file linked here https://files.igs.org/pub/station/general/antenna.gra , but I'm going to add this one you copied.

**Comment by elidana** [comment]
diagram now updated to include antenna+radome.
@aleks-spes @ozym can I have another thumbsup please?

**Review by ozym — APPROVED** [review]
The code updates are okay, can't comment on the actual equipment diagram.

**Review by aleks-spes — APPROVED** [review]

**Comment by elidana** [comment]
ok, this will not fully work.

I have:
- added some mockup metadata to have this antenna+radome installed (added below)
- used the updated antenna graph that also include the radome information
- locally tested the generation of sitelogs.

If I use `SEPCHOKE_B3E6: |2+` as antenna name in the `config.yaml` the code works fine and I can generate a sitelog as expected

If I use `SEPCHOKE_B3E6   SPKE: |2+` as antenna name in the `config.yaml` the code is not able to find the antenna
```
2024/05/28 17:00:22 warning: missing antenna graph for: "SEPCHOKE_B3E6"
```

To work with `antenna + radome` pair, I think this bit https://github.com/GeoNet/delta/blob/main/tools/sitelogs/main.go#L590-L612 would need to be updated and also include the radome search, as the current code  would not search for the "Antenna + radome" model.

So we can either 
1. update the code so that the radome is also considered when selecting the correct antenna graph , and use `SEPCHOKE_B3E6   SPKE` in the config.yaml
  :dragon: (but in that case we will need to add "NONE" to each antenna model with no radome???
  OR
3. or use the "wrong" antenna model name `SEPCHOKE_B3E6` in the config.yaml file for this specific antenna and keep things as is. 

The antenna+radome info is correctly represented in the sitelog - "Antenna Type" field
```
4.2  Antenna Type             : SEPCHOKE_B3E6   SPKE
     Serial Number            : 5885
     Antenna Reference Point  : BAM
     Marker->ARP Up Ecc. (m)  : 0.0020  
     Marker->ARP North Ecc(m) : 0.0000  
```

**I'm inclined to take the shortcut and pick option two....but happy to change idea**


--------
 #### mock up metadata used for testing 

```diff
diff --git a/assets/antennas.csv b/assets/antennas.csv
index 1d725afa..f2de1e2b 100644
--- a/assets/antennas.csv
+++ b/assets/antennas.csv
@@ -440,3 +440,4 @@ Trimble Navigation Ltd.,TRM57971.00,5000115515,15312,
 Trimble Navigation Ltd.,TRM57971.00,5000115520,15310,
 Trimble Navigation Ltd.,TRM57971.00,5000115524,15313,
 Trimble Navigation Ltd.,TRM57971.00,6124411110,16359,
+Septentrio,SEPCHOKE_B3E6,5885,,
diff --git a/assets/radomes.csv b/assets/radomes.csv
index afcf0949..78f1f03e 100644
--- a/assets/radomes.csv
+++ b/assets/radomes.csv
@@ -22,3 +22,4 @@ Thales,SNOW,12477,,
 Thales,SNOW,12627,,
 Thales,SNOW,CR16098,,
 Thales,SNOW,CR620022305,,
+Septentrio,SPKE,123456,,
diff --git a/install/antennas.csv b/install/antennas.csv
index ea922131..2a8eafea 100644
--- a/install/antennas.csv
+++ b/install/antennas.csv
@@ -8,6 +8,7 @@ Leica Geosystems,LEIAT504,332,TAKL,0,0,0,0,2001-07-11T00:00:00Z,2007-07-05T03:44
 Leica Geosystems,LEIAT504,333,WGTT,0,0,0,0,2000-06-29T03:00:00Z,2000-08-17T23:59:59Z
 Leica Geosystems,LEIAT504,333,WGTT,0.0002,0,0,0,2000-08-18T00:00:05Z,9999-01-01T00:00:00Z
 Leica Geosystems,LEIAT504,405,LYTT,0.001,0,0,0,1999-11-15T00:00:03Z,9999-01-01T00:00:00Z
+Septentrio,SEPCHOKE_B3E6,5885,TGHM,0.002,0,0,0,2024-04-07T23:48:30Z,9999-01-01T00:00:00Z
 Thales,ASH700936B_M,11753,WGTN,0.0017,0,0,0,1996-05-23T00:00:00Z,1999-11-10T05:43:00Z
 Thales,ASH700936B_M,11753,WGTN,0.0017,0,0,0,1999-11-10T05:44:00Z,2005-03-21T01:59:59Z
 Thales,ASH700936C_M,12413,GRAC,0,0,0,0,1998-07-10T00:00:00Z,1999-12-28T00:00:00Z
@@ -182,7 +183,7 @@ Trimble Navigation Ltd.,TRM55971.00,30473528,MTQN,0.002,0,0,0,2010-02-09T00:00:1
 Trimble Navigation Ltd.,TRM55971.00,30473549,OHIN,0.002,0,0,0,2008-09-03T01:30:00Z,9999-01-01T00:00:00Z
 Trimble Navigation Ltd.,TRM55971.00,30473556,WHKT,0.002,0,0,0,2009-03-23T00:30:00Z,2019-10-21T23:16:55Z
 Trimble Navigation Ltd.,TRM55971.00,30473585,TGHO,0.002,0,0,0,2008-12-22T02:30:00Z,2023-05-24T21:06:00Z
-Trimble Navigation Ltd.,TRM55971.00,30473585,TGHM,0.002,0,0,0,2023-05-25T04:19:02Z,9999-01-01T00:00:00Z
+Trimble Navigation Ltd.,TRM55971.00,30473585,TGHM,0.002,0,0,0,2023-05-25T04:19:02Z,2024-04-07T23:48:29Z
 Trimble Navigation Ltd.,TRM55971.00,30473588,VGMT,0.055,0,0,0,2011-01-17T03:37:51Z,2020-02-25T23:13:01Z
 Trimble Navigation Ltd.,TRM55971.00,30473655,RDLV,0.002,0,0,0,2009-01-13T01:00:00Z,2018-05-14T22:25:47Z
 Trimble Navigation Ltd.,TRM55971.00,30473674,GRNG,0.002,0,0,0,2007-06-14T01:55:00Z,9999-01-01T00:00:00Z
diff --git a/install/radomes.csv b/install/radomes.csv
index d35474e2..30fadb1a 100644
--- a/install/radomes.csv
+++ b/install/radomes.csv
@@ -6,6 +6,7 @@ Leica Geosystems,LEIS,332,WGTT,1999-12-14T00:00:00Z,2000-06-29T02:59:59Z
 Leica Geosystems,LEIS,332,TAKL,2001-07-11T00:00:00Z,2007-07-05T03:44:00Z
 Leica Geosystems,LEIS,333,WGTT,2000-06-29T03:00:00Z,9999-01-01T00:00:00Z
 Leica Geosystems,LEIS,405,LYTT,1999-11-15T00:00:00Z,9999-01-01T00:00:00Z
+Septentrio,SPKE,123456,TGHM,2024-04-07T23:48:30Z,9999-01-01T00:00:00Z
 Thales,SCIS,0220063995,CNCL,2000-08-03T00:00:00Z,2016-02-29T20:26:00Z
 Thales,SCIS,0220066912,MTJO,2000-08-15T00:00:00Z,2011-02-07T22:33:00Z
 Thales,SCIS,0220067545,WAKA,2000-11-02T00:00:00Z,2001-12-13T00:00:00Z
```

#### to generate sitelogs locally 
```
$> cd ~/git/delta/tools/sitelogs
$> go generate
$> go build
$> mkdir logs xml
$> ./sitelogs
```

**Comment by ozym** [comment]
you may be able to use #2058 here. It also ignores the current antenna + radome setups if there is no matching graph.

**Comment by aleks-spes** [comment]
I agree with you @elidana, it is better minimize changes in the `config.yaml`. If we want to use just the antenna code `SEPCHOKE_B3E6`, I think we should use the diagram that you proposed first time (without radome). In this case there is no missmatch between the name and the picture.
```
SEPCHOKE_B3E6

                    ---------------                       <--  0.1550
                  /                 \
                 |                   |
+-----------------------------------------------------+   <--  0.1080  TCR
|                                                     |
|                                                     |
|                                                     |
|                                                     |
+-----------------+-----------------+-----------------+   <--  0.0480  BCR
                  |                 |
                  |                 |
                  |                 |
                  +--------x--------+                     <--  0.0000  BPA=ARP
                                                              (5/8" thread might
                                                               differ from BPA!)
                                                                       NOM=NRP
                  <--    0.1210   -->
<--                      0.3630                     -->
```

**Comment by elidana** [comment]
thanks @aleks-spes !
but super-@ozym has solved the issue and we now have an updated code that will handle antenna+radome if we do have both! 
so no shortcut needed. will test it locally (see comment from Mark above)

**Pull request merged**
