### PR TITLE
RBCT new sensors

### PR DESCRIPTION
**Pull request by salichon**
New PTX1830 - Like4like

### CODE REVIEW

**Comment by salichon** [comment]
@peanutty @john this shoudl be allright I resolved some git conflicts
Is all okay for that one ?
Cheers
jerome

**Comment by ozym** [comment]
@salichon probably not the john you we looking for ->>> ( @jristau )

**Comment by salichon** [comment]
@jristau @peanutty I ll need your review on this PR ..again since it was a long time pending review  and 
ended with some merging conflicts. 
I m going to fix this conflict and resubmit it for a review from you. (thanks !)

@ozym it s a conflict between LOTT and RBCT sensor update. -  and I obviously did not solved it right said Travis  , :( ... 
Is there a (simple) way to do - or  perhaps creating a new branch ?

**Comment by salichon** [comment]
FYI @ozym 
RBCT tide gauges - I pushed a "fresh" branch for RBCT - test have passed ;)

**Comment by salichon** [comment]
@jristau Hi
cCan you review this PR - in order to end it,
thanks a  lot :)
cheers
jerome

**Comment by salichon** [comment]
Thanks @jristau @peanutty 
I ll proceed .

**Pull request merged**
