### PR TITLE
HUKS HN | BN stream correction - 2016 legacy

### PR DESCRIPTION
**Pull request by salichon**
Change was not implemented for HUKS 20 BN streams in 2016
Archive| seedlink are okay
HN deemed stilll activated (last 2016.319) although no data since

Last tangible  date of visit on recorders is  HUKS,20 2016-08-17 (2016.230)

FYI @samgeonet @brianf3rris 
to resolve for: https://github.com/GeoNet/tickets/issues/4457

### CODE REVIEW

**Comment by salichon** [comment]
@samgeonet HUKS still configured for HN right ?

**Comment by samgeonet** [comment]
Looks like its configured for both. @ozym may need to jump in on this one

**Comment by ozym** [comment]
Has there been any strong motion to trigger an event?

**Comment by salichon** [comment]
Hello @ozym 
This is a Taranaki strong motion - I deem so not often looked at since no recent close or strong sources. - 
Last ever HN was in 2016.319 (Nov 14 -) so triggered after an upgrade visit. 
Perhaps the triggering treshold haven't been met since. 
Just checking config.- if all good.
thanks

**Comment by mnaguit** [comment]
Looks good for this station, with BN* streams at 50.0Hz.
Here's the data coming in on the specified opening date:

HUKS

**Comment by salichon** [comment]
thanks i ll proceed

**Comment by salichon** [comment]
FYI @brianf3rris 
This strong motion stream  will be available on the processing systems when network updated.
(Mai 2019 certainly)

**Pull request merged**
