### PR TITLE
add RU & TO scandoas to features

### PR DESCRIPTION
**Pull request by rumachan**
Additions to environment/features.csv for RU and TO scanDOAS sites. Required for those data to go into Tilde. Other Delta files required no changes.

### CODE REVIEW

**Review by ozym — APPROVED** [review]

**Review by elidana — APPROVED** [review]
looks good and agree with names discussed with scandoas subject matter experts

**Comment by rumachan** [comment]
@ozym this failed `govulncheck` after I updated the branch. Do you understand this? Thanks

**Comment by ozym** [comment]
Yes, there's a program called govulncheck which has a known list of security vulnerabilities (usually in libraries etc.) it gets updated fairly quickly after a vulnerability is announced. But, github actions is a little slow in updating it's releases, so it will be fixed the next time the actions is updated for a new go release version.  We can either skip this test, or wait.

**Comment by rumachan** [comment]
Thanks @ozym Are the actions likely to update before next week? If not, is it possible to skip in this case? It'd allow me progress things.

Though I'm happy with whatever you think is the most sensible approach.

**Pull request merged**
