### PR TITLE
APZ logger-sensor swap + new recorder

### PR DESCRIPTION
**Pull request by mnaguit**
- Logger: from Q330/6 to Centaur
- Sensor: from FBA-ES-T to Horizon
- Recorder: Titan SMA
- Firmware
   - Centaur v4.5.20 (ok)
   - TitanSMA v4.5.22 (updated)
- for LC 10 (HH-ENZ) and LC 21(HN-ENZ)

### CODE REVIEW

**Review by CBurton90 — CHANGES_REQUESTED** [review]
@mnaguit Shall we add Centaur fw too? (4.5.20)? Apologies if it's already in there!

**Comment by mnaguit** [comment]
> @mnaguit Shall we add Centaur fw too? (4.5.20)? Apologies if it's already in there!

Yup @CBurton90 Centaur fw (4.5.20) was already in the list before 😄

**Review by CBurton90 — APPROVED** [review]

**Review by salichon — APPROVED** [review]
this is looking allright Thanks @mnaguit

**Comment by mnaguit** [comment]
Thank you Sir @salichon and Sir @CBurton90 😄

**Pull request merged**
