### PR TITLE
DCZ datalogger/sensor-recorder swap

### PR DESCRIPTION
**Pull request by mnaguit**
From Obsidian4X/Episensor to TitanSMA
For LC 20, HN(ENZ) streams

### CODE REVIEW

**Review by CBurton90 — APPROVED** [review]

**Review by salichon — APPROVED** [review]
Sweet provided the same sensopr location  belew 1 meter

**Comment by mnaguit** [comment]
Hi @ozym . Just a quick follow up on this. For your review. Thanks!

**Comment by ozym** [comment]
@CBurton90 Is it my understanding from this that KUZ titan wasn't what we thought it was and what we thought it was is now installed at DCZ?

**Comment by CBurton90** [comment]
@ozym correct, KUZ TitanSMA had the incorrect serial, for your sanity:

https://github.com/GeoNet/tickets/issues/8910#issuecomment-895642868

**Review by ozym — APPROVED** [review]

**Pull request merged**
