### PR TITLE
Guralp Fortis new assets

### PR DESCRIPTION
**Pull request by CBurton90**

### CODE REVIEW

**Review by mnaguit — APPROVED** [review]
👍

**Review by ozym — APPROVED** [review]
looks good, haven't checked off boxes though.

**Comment by salichon** [comment]
on the shelves - ok : )

**Comment by CBurton90** [comment]
Could someone with permission please merge 🤣 (assuming we are happy)

**Comment by mnaguit** [comment]
> Could someone with permission please merge 🤣 (assuming we are happy)

I think we are all happy with this.
So cheers to 'squashing & merging' this 😆 
@CBurton90 @ozym @salichon

**Comment by mnaguit** [comment]
(and I hope, 'with permission' means being able to click the 'squash & merge' button 🤔

**Comment by CBurton90** [comment]
@mnaguit yup thank you!

**Pull request merged**
