### PR TITLE
PRPC open LC 21

### PR DESCRIPTION
**Pull request by mnaguit**
open LC 21 for CUSP3D SN 42230

### CODE REVIEW

**Comment by mnaguit** [comment]
Note: I'll update this PR once the final details on coordinates, elevation and azimuth are received.

**Comment by mnaguit** [comment]
Coordinates & elevation are now updated, details from @CBurton90 as posted in the ticket.

**Review by CBurton90 — APPROVED** [review]

**Comment by mnaguit** [comment]
As per @paulaic update on azimuth, new CUSP3D has the same orientation as the one currently installed on this site.

Thanks reviewing this PR @CBurton90 
Hope to receive your review soon. @salichon @ozym

**Review by salichon — CHANGES_REQUESTED** [review]
hmm  Hello there is a Location reference that is wrong here (at least) `43.525889,172.682722,7.8,WGS84,Topographic Map,`
and from the ticket  the reference is: 
```
From CUSP Internal GPS receiver:
Current latitude	  43º31'33.20" S
```

**Comment by CBurton90** [comment]
> hmm Hello there is a Location reference that is wrong here (at least) `43.525889,172.682722,7.8,WGS84,Topographic Map,`
> and from the ticket the reference is:
> 
> ```
> From CUSP Internal GPS receiver:
> Current latitude	  43º31'33.20" S
> ```

They need to be converted to decimal degrees
`172.682722222 | -43.525888889`
Is the conversion I get when converting from deg, min, sec in WGS84 @salichon

**Comment by mnaguit** [comment]
Hi @CBurton90 . Probably it's best if all coordinates (converted to decimal) comes from RIM.
I did the conversion for this station, using this website: https://www.fcc.gov/media/radio/dms-decimal

**Comment by CBurton90** [comment]
> Hi @CBurton90 . Probably it's best if all coordinates (converted to decimal) comes from RIM.
> I did the conversion for this station, using this website: https://www.fcc.gov/media/radio/dms-decimal

Whoops I think @salichon mean to correct `Topographic Map` to  `Internal GPS Clock`. Cheers!

**Comment by mnaguit** [comment]
Ah okey, I didn't even check that bit.
Let me know if it has to be changed to Internal GPS clock. @CBurton90 @salichon

**Comment by CBurton90** [comment]
> Ah okey, I didn't even check that bit.
> Let me know if it has to be changed to Internal GPS clock. @CBurton90 @salichon

Yeah I'd say it does 🤣 as that's where the coords are obtained from...sorry for the confusion

**Comment by mnaguit** [comment]
Changes made (e.g. topo map to gps clock).

**Review by CBurton90 — APPROVED** [review]

**Review by salichon — APPROVED** [review]

**Comment by mnaguit** [comment]
Quick follow up for @ozym review on this PR --this is one of the two stations that will be used for the flapping effect investigation. Thanks!

**Comment by mnaguit** [comment]
Hi @ozym . Do the changes in this PR look fine for you? Thanks.

**Review by ozym — APPROVED** [review]

**Pull request merged**
