### PR TITLE
Firmware upgrade for BOWS & 5 Chch stations

### PR DESCRIPTION
**Pull request by mnaguit**
- first delta PR to include firmware upgrade for EQR120 (and later for other seismic equipment)

Are you guys happy with the proposed changes? Kindly let me know if I have to modify the details.
Thanks!

### CODE REVIEW

**Review by CBurton90 — CHANGES_REQUESTED** [review]
I'm not sure if they need the notes of `Fix GPS timing 1 sec`  as it was a seedlink timestamping issue primarily. Also the firmware is `m001.03.06` , I would have thought that line could have been solely that rather than `EQR120+m 001.03.06` . 

I'll let @ozym confirm though as that's just how I see it.

**Comment by ozym** [comment]
Yup, no 1 second fix here. Just the first upgrade (fixes ping etc) but this doesn't need to be recorded.

**Comment by ozym** [comment]
Also, no need for the site codes. This should be obvious from the other files and is one more thing that could cause confusion (i.e. we don't test it).

**Comment by mnaguit** [comment]
Thanks @ozym & @CBurton90 .
I modified the notes (to indicate first upgrade) & version (to remove EQR120). For your review.

**Comment by ozym** [comment]
It actually doesn't need any comment (we abuse the notes column too much).

**Comment by mnaguit** [comment]
Hahaha. Will remove the comment now. =)

**Comment by mnaguit** [comment]
Another round of your review, as per changes made.
Thanks @ozym * @CBurton90

**Review by ozym — APPROVED** [review]
Looks fine, I'll leave it up to @CBurton90 to confirm what the firmware name is.

**Review by CBurton90 — APPROVED** [review]
Looks good!

**Comment by ozym** [comment]
Only other thought was attempting to add in the firmware version prior to this.

**Comment by mnaguit** [comment]
> Only other thought was attempting to add in the firmware version prior to this.

Add in the notes, before I merge? @ozym

**Comment by ozym** [comment]
No, merge away. There should be another PR to find original firmware if we can.

**Comment by CBurton90** [comment]
> No, merge away. There should be another PR to find original firmware if we can.

@ozym @mnaguit for reference previous fw was `m001.03.03` but I am unsure if this is consistent across all units recently purchased. In the RFP we tested `m001.03.01` I believe?

**Pull request merged**
