### PR TITLE
PAKZ new station

### PR DESCRIPTION
**Pull request by mnaguit**
- RCET station
- for LC 10 (LH/HH-ENZ)
- Centaur firmware v4.5.20

### CODE REVIEW

**Review by salichon — APPROVED** [review]
yes strangely enough for me the trailing zero\es :
PAKZ,10,-35.534660  for the latitude went through the tests 
all good

**Review by CBurton90 — APPROVED** [review]

**Comment by ozym** [comment]
> yes strangely enough for me the trailing zeroe : **PAKZ,10,-35.534660** for the latitude went through the tests but all good

This was a fix a while back, there's now two values that are loaded, (a) the actual floating point number, and (b) the string representation. This last one is the one that's used to check for the trailing zeros.

**Comment by mnaguit** [comment]
All good with this one Gentlemen? Thanks!

**Comment by mnaguit** [comment]
Merging this now & work on the next RCET station

**Pull request merged**
