### PR TITLE
COVZ TitanSMA SM Recorder Installation

### PR DESCRIPTION
**Pull request by Thomas-Benson**
- Installing TitanSMA (1257) at new site LC 20 for existing station COVZ
- Using most recent TitanSMA firmware version 4.5.22
- New site uses same coordinates as all other sites at this station.

### CODE REVIEW

**Review by mnaguit — COMMENTED** [review]
Hi. Double checking: was the instrument oriented to the north? If that is the case, the streams should be non-axial? @Thomas-Benson @CBurton90

**Comment by CBurton90** [comment]
@mnaguit I'd tend to agree. Chucked a comment in the ticket. We will need to update the instrument config if we go with non-axial (easily done).

**Comment by mnaguit** [comment]
> @mnaguit I'd tend to agree. Chucked a comment in the ticket. We will need to update the instrument config if we go with non-axial (easily done).

Thanks @CBurton90

**Comment by ozym** [comment]
I think this site is expected to become part of the national network (NZ) rather than the chateau network (CH).  That is, it has a strong motion oriented North/South and suitable comms upto national network specs.

**Comment by Thomas-Benson** [comment]
`streams.csv` updated to axial

**Review by mnaguit — APPROVED** [review]

**Review by CBurton90 — APPROVED** [review]

**Pull request merged**
