### PR TITLE
CCMB new structural array

### PR DESCRIPTION
**Pull request by mnaguit**
with LC 21 to 29 and 2A to 2G

### CODE REVIEW

**Comment by mnaguit** [comment]
Many thanks for your review @salichon & @brianf3rris 

For @salichon : per our delta meeting today, the channel convention for arrays has been discussed and clarified.
For @brianf3rris : Travis returns an error whenever there are trailing zeros in decimals.

**Comment by mnaguit** [comment]
Hi. Gentle follow up on the review of this PR. Many thanks.
@ozym @salichon @jristau @brianf3rris

**Comment by salichon** [comment]
CCMB looks like a uni building of engineers
  https://www.canterbury.ac.nz/engineering/schools/mechanical/contact-us/: they can use the data fromtheir office building ... nice

**Comment by mnaguit** [comment]
HI @ozym . Gentle reminder to review this PR. Since it's a new array (similar with what we do for new stations), it would be great to have it reviewed by representatives from 3 teams before I merge the PR. Thanks in advance.

**Pull request merged**
