### PR TITLE
Update cameras.csv

### PR DESCRIPTION
**Pull request by JonoHanson**
all installed cameras have more information

### CODE REVIEW

**Comment by danieldooley** [comment]
Added a commit to attempt fixing build issues

**Comment by mnaguit** [comment]
Hi @JonoHanson . I can do the review for this, if there's some background details available to compare the changes with?

**Comment by JonoHanson** [comment]
the information is pieced together from SIT, but mainly from Richard Johnson and this ticket
https://github.com/GeoNet/tickets/issues/576
with a slight update through personal communication.

additionally, this data makes up part of the this other ticket
https://github.com/GeoNet/tickets/issues/4475
but both the table in ticket 4475 and the change I want to make here come from me, so the data source is no more reliable.

**Comment by JonoHanson** [comment]
good catch @mnaguit . the extra info about the pole the camera is on should be stored in SIT. I've added a corresponding note in the places.csv

Update place.csv #1285

**Comment by mnaguit** [comment]
Noted @JonoHanson . Thanks.

**Pull request merged**
