### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by staylorofford**
Update README.md to reflect current understanding of metadata documentation

### CODE REVIEW

**Review by ozym — APPROVED** [review]

**Comment by staylorofford** [comment]
Hi @ozym , please can I get another review here

**Comment by staylorofford** [comment]
bump

**Comment by staylorofford** [comment]
Mark?

**Review by elidana — APPROVED** [review]
not Mark, but hopefully still ok as an approver for this one?

**Review by elidana — APPROVED** [review]
not Mark, but hopefully still ok as an approver for this one?

**Pull request merged**
