### PR TITLE
URZ sensor-datalogger swap

### PR DESCRIPTION
**Pull request by mnaguit**
_Sensor_: from Guralp SN T3969 to Trillium Borehole T120-BH1 SN 1073
_Datalogger_: from Q330HRS/6 SN5308 to Centaur SN 8003

For LC 10 HN(12Z)
Centaur firmware v4.5.20

### CODE REVIEW

**Review by CBurton90 — APPROVED** [review]
LGTM

**Review by salichon — APPROVED** [review]
sounds pretty legit 
thanks @mnaguit  et al.

**Comment by mnaguit** [comment]
Thanks @salichon @CBurton90 

Hi @ozym . Here to disturb you again with this PR. It involves the 1st Trillium borehole sensor deployed, so it would be great to receive a review from you. Thanks in advance.

**Comment by mnaguit** [comment]
Hi @ozym . Gentle follow up on the review of this PR. Thank you!

**Review by ozym — APPROVED** [review]

**Pull request merged**
