### PR TITLE
MSWZ eqchange

### PR DESCRIPTION
**Pull request by mnaguit**
change the sensor (from Sercel to Lennartz 3DliteMKIII)
update the logger (from Q330/3 to Q330S/3)

### CODE REVIEW

**Comment by mnaguit** [comment]
thanks @peanutty ... will modify it now =)

**Comment by peanutty** [comment]
cool @mnaguit most new loggers going in will be 6 Channel (even tho they'll only have one instrument attached)

**Comment by mnaguit** [comment]
Noted Sir Dan 👍 @peanutty 

and wow, this PR went super quick 👍 
thanks @salichon & @peanutty

**Comment by salichon** [comment]
Data verified MSWZ EH ZNE 
Gap: NZ.MSWZ.10.EHZ    2018-07-23T04:03:57.953137Z 2018-07-23T04:08:40.963138Z.
It looks like FDSN NRT does not provide all the data on this one .

**Pull request merged**
