### PR TITLE
KOWC recorder swap

### PR DESCRIPTION
**Pull request by mnaguit**
from CUSP3D 42052 to EQR120 46536
EQR120 firmware v.08

### CODE REVIEW

**Review by ozym — DISMISSED** [review]

**Review by salichon — CHANGES_REQUESTED** [review]
as per ticket :"_Azi should be same as existing instrument but @DWhitelaw says old CUSP had no y axis markings so he will update us with the EQR120 y axis orientation relative to the building just to be sure_"

Shall we wait for this update , the PR sets it up to 0  :) 

 cheers

**Comment by mnaguit** [comment]
Sure @salichon . Will follow it up in the main ticket.

**Review by CBurton90 — APPROVED** [review]

**Comment by CBurton90** [comment]
@salichon he said it is the same as the old CUSP so we will have to trust him

**Comment by mnaguit** [comment]
Many thanks @CBurton90 
Will merged this PR now, so that I can issue the next without issues.

**Comment by mnaguit** [comment]
Oooooopppps. Can you please review & approve Monsiuer @salichon

**Review by salichon — APPROVED** [review]
yup

**Review by salichon — CHANGES_REQUESTED** [review]
hello
@conrad mentionend the orientation to be 70  deg

**Comment by mnaguit** [comment]
> hello
> @conrad mentionend the orientation to be 70 deg

Noted. @CBurton90 approved the PR, so I assumed the 0 azimuth is good.
Nevertheless, waiting for your approval @salichon and I'll merged this. Thanks.

**Review by salichon — APPROVED** [review]
sweet :) thx

**Pull request merged**
