### PR TITLE
Upgrade of PositioNZ-RT sites to firmware 5.22.

### PR DESCRIPTION
**Pull request by staylorofford**

### CODE REVIEW

**Comment by ozym** [comment]
Checks have failed

**Comment by ozym** [comment]
And is out of sync with master

**Comment by ozym** [comment]
You seem to have added an extra blank line to the end of the firmware file.

**Comment by staylorofford** [comment]
I will resolve this... it's quite unexpected.

**Comment by staylorofford** [comment]
My computer didn't have enough RAM to save the full file... I will tidy things up and make another request.

**Pull request closed without merging**
