### PR TITLE
add new GNSS site MNMW

### PR DESCRIPTION
**Pull request by aleks-spes**
Install Alloy receiver and Zephyr 3 antenna at the new site MNMW.

### CODE REVIEW

**Review by elidana — CHANGES_REQUESTED** [review]
Hi @aleks-spes , thanks for that. I think some info are missing, being this a new site.

Can you please add metadata for `environment/visibility.csv`

And I'm waiting for a couple of info from the field technicians (monument height and antenna serial number) before being able to complete the review

**Review by elidana — APPROVED** [review]
looks good, thanks @aleks-spes !

**Review by CBurton90 — APPROVED** [review]

**Comment by aleks-spes** [comment]
Updated files after installing the calibrated antenna.

**Review by CBurton90 — APPROVED** [review]

**Review by elidana — APPROVED** [review]
looks good thanks @aleks-spes !

**Pull request merged**
