### PR TITLE
Update firmware.csv

### PR DESCRIPTION
**Pull request by ricardojohansson**
updated CR6 logger firmware from version 12.00 to 12.02
(this logger is temporarily in the workshop but will be redeployed to OT013 later this week)

### CODE REVIEW

**Review by elidana — CHANGES_REQUESTED** [review]
hei @ricardojohansson , can you please double check the date? It is in the future right now ! :) thanks!

**Review by elidana — APPROVED** [review]
looks good!

**Comment by EvanCGNS** [comment]
Problem with the delta-apps smoke-test with no obvious cause, merge-updated this branch to re-run tests and it fixed the problem. Not really my place to rebase/merge though, I'll let @elidana do that

**Comment by elidana** [comment]
thanks @EvanCGNS !
waiting on this https://github.com/GeoNet/delta/pull/2179/ to be merged first, then we can pick up the firmware bit.

/cc @rumachan

**Comment by EvanCGNS** [comment]
Hi @elidana this can probably be merged now no?

**Pull request merged**
