### PR TITLE
MLZ datalogger swap

### PR DESCRIPTION
**Pull request by mnaguit**
- from Q330/3 SN2466 to Centaur SN9167
- Centaur firmware v4.5.20
- for LC 10 (LH/HH-ENZ)
- station name updated from Mavora Lakes to Hikuraki Station

### CODE REVIEW

**Review by CBurton90 — COMMENTED** [review]
@mnaguit I'm a little unsure on the name change. On the website drums we have MLZ as Mavora Lakes which I assume could be pulled from stations.csv?

Changing to a specific station and displaying on the website "Hikuraki Station" might infringe on privacy a little?

@ozym will know what would be best practice?

**Comment by ozym** [comment]
I haven't seen any paper work or argument for changing the name.

In general the site names tended to be of the likes of:

"We need a station near XYZ", with XYZ being rather broad (sometimes too broad).

Sometimes a site was moved and the naming got a little more specific, but the idea is to try and keep things at a broadish region (hadn't even thought about privacy then).

**Comment by salichon** [comment]
Kia Ora  !
I reckon the station  `name` change  _: "Name - Used to describe the general geographical location of the Station."_ comes from a care for consistency between it
 and 
 the `place` item: _"Deployed datalogger place"_    for the datalogger 
 
 I guess that Place is used in some process as opposed to the station name.
 
 so  ...  should `Name` and place have to  be consistent to each other in delta  ?

**Comment by ozym** [comment]
The place item is a general term and not related to the station name. It could be, and in some cases is, but it may cause confusion either way. If there's confusion I'd go the other way, change the Place name in the installed datalogger rather than the Station Name. (The station is more related to the sensor, and example is some sites on Volcanoes were recorded on dataloggers at Wairakei).

**Comment by mnaguit** [comment]
That name change is new for me. Just changed it here, to start a discussion 😄 
I've seen a couple of stations with different station name and 'place' name under logger/sensors...and so I wonder if these bits need to be on the same page.

**Comment by CBurton90** [comment]
Maybe lets just throw a question and delta label on it (change ticket) to discuss at the next delta meeting to come to a decision

**Comment by mnaguit** [comment]
Hi @ozym @CBurton90 @salichon 
I have reverted back to the original station name: Mavora Lakes (instead of Hikuraki Station from `loggers/connections` place name). Kindly review again. Thanks!

**Review by CBurton90 — APPROVED** [review]

**Comment by ozym** [comment]
@mnaguit there are some conflicts with this PR since you last updated it.

**Comment by mnaguit** [comment]
> @mnaguit there are some conflicts with this PR since you last updated it.

Ah, probably connected with other PRs I've issued/merged. Will check it out. Thanks @ozym

**Comment by mnaguit** [comment]
Hope that fixed the issues.
Can you please review again? @CBurton90 @ozym @salichon 
Thanks!

**Review by ozym — APPROVED** [review]

**Review by CBurton90 — APPROVED** [review]

**Review by salichon — APPROVED** [review]

**Comment by ozym** [comment]
@mnaguit do you need help with this PR?

It may sometimes be easier to start from scratch if it's only a few changes. I can review it again if needed.

**Comment by mnaguit** [comment]
> @mnaguit do you need help with this PR?
> 
> It may sometimes be easier to start from scratch if it's only a few changes. I can review it again if needed.

Oh I thought it's all good now. Is this PR giving further issues? @ozym 
Apologies if it does. Just doing a lot of updating/catching up on my end, was on leave early this week.

**Comment by mnaguit** [comment]
Checked by all reviewers! I'm ready to squash and merge, all good @ozym ? Thank you.

**Pull request merged**
