### PR TITLE
Add EQR120 response 200HZ strong motion

### PR DESCRIPTION
**Pull request by salichon**
Team work on EQR120 New response 
integration of the recorder

### CODE REVIEW

**Comment by elidana** [comment]
can we please add EQR120 model also for sensor description? This way might be more clear when we add new equipment in /install/recorders.csv

**Review by elidana — CHANGES_REQUESTED** [review]
please add EQR120 sensor model as well (not just datalogger)

**Review by CBurton90 — APPROVED** [review]
As I was there it all looks good. The only thing that may want to be thought of is adding the sensor type D to the EQR120 i.e. calling it in the cusp.yaml file `EQR120D` like the conventions of the CUSP sensors before it.

**Review by mnaguit — APPROVED** [review]
_.yaml_ files look consistent with the already registered equipment. Knowing little about these files, I'm assuming added details are not case sensitive (e.g. EQR120 vs Eqr120 in description). For the _.go_ file, from what I understood this is created automatically.

**Review by elidana — APPROVED** [review]

**Comment by salichon** [comment]
@CBurton90 - i will merge this PR for the EQR120 strong motion CSI 
This should ease the deploys 
FYI @JonoHanson @peanutty

**Pull request merged**
