### PR TITLE
PKE correct metadata

### PR DESCRIPTION
**Pull request by mnaguit**
change datalogger from Q330S/6 SN 6897 to Q330S/6 SN 6839

### CODE REVIEW

**Comment by mnaguit** [comment]
Hi @ozym & @KOgeonet ...quick follow up, if you're happy with the changes in this PR. Cheers!

**Comment by mnaguit** [comment]
Hi @ozym . Are you happy with the changes in this PR? Thanks!

**Comment by mnaguit** [comment]
Quick follow up. For your review @ozym . Thanks.

**Comment by salichon** [comment]
@mnaguit we can merge this one now
thanks
cheers

**Comment by mnaguit** [comment]
Noted @salichon . I'll merge this one.

**Pull request merged**
