### PR TITLE
Adding new A, C, and E constituent values

### PR DESCRIPTION
**Pull request by meganmadley**
New version with start and end dates. 

Files with new values:
[dartNZA_2022utide.csv](https://github.com/GeoNet/delta/files/8194746/dartNZA_2022utide.csv)
[dartNZC_2022utide.csv](https://github.com/GeoNet/delta/files/8194747/dartNZC_2022utide.csv)
[dartNZE_2022utide.csv](https://github.com/GeoNet/delta/files/8194749/dartNZE_2022utide.csv)

Start dates from beta-data:
NZA - 2021-12-18
NZB - 2021-12-11
NZC - 2021-12-13

### CODE REVIEW

**Comment by salichon** [comment]
haha @megan 
you just cretaed the Nonanuary month:  **2000-00-00T00:00:00Z**
As long as it Off and sunny ... ;)  i d take it
_NZA,48,MK4,0.11,141.6,2000-00-00T00:00:00Z,9999-01-01T00:00:00Z_

**Review by salichon — COMMENTED** [review]
typo line 286

**Review by salichon — CHANGES_REQUESTED** [review]
Kia Ora @meganmadley 
i started to have a look, it s a bit painful isn't it ;) 
- Specifically most likely for the new fail test : `"NZA,6,01,5.57,187.2,2021-12-18T00:00:00Z,9999-01-01T00:00:00Z` 
O1 Vs 01 kinda of things  (we need to get some unix trick to deal with these awful list:)) 
- In Overall 
I d need some clarity about these update...
Are the new parameters
 Superseding the previous set (hence we need to "end" the previous) 
OR 
Updating the previous set (hence replacing with the update and keeping the old ones)

I did not really got this from the email (or .. i missed it ..) 

Cheers!

**Comment by salichon** [comment]
@meganmadley yo :) 
check on the https://github.com/GeoNet/delta/environment/README.md
there might be a clue  to me (_Constituent number, used mainly for display and sorting)_
Constituents are attributed a number so that i reckon same constituents cannot have different numbers 

```
NZA,1,Z0,263875.87,0.0,2000-01-01T00:00:00Z,2021-12-17T23:59:59Z
NZA,2,Z0,263467.1,0.0,2021-12-18T00:00:00Z,9999-01-01T00:00:00Z
NZA,3,M2,56.20,156.2,2000-01-01T00:00:00Z,2021-12-17T23:59:59Z
NZA,4,M2,55.18,156.8,2021-12-18T00:00:00Z,9999-01-01T00:00:00
```

Probably relevant to provide same constituents the same number as it is 2 different series.

**Comment by ozym** [comment]
Each time a model is run the results are given with the constituents in order (the number assigned) the name of the constituent doesn't matter in this case.

So for each site:

A 1
B 2
C 3
D 4
B 1
C 2
E  3
...

where there have been two models run A - D, an B,C,E  etc.

**Comment by meganmadley** [comment]
Have made a change to what Mark suggested in slack, doing it this way, instead of reordering will also make it a lot simplier in the future to add changes. This also allows for all of the current values to be the most recent model, instead of some values from the recent model still being around.

**Comment by ozym** [comment]
@meganmadley could you update the gauges.csv file to add the new NZA,NZC,NZE deploys. This updates the depth in the configs.

**Comment by meganmadley** [comment]
@ozym see PR https://github.com/GeoNet/delta/pull/1292, have just done for A, C, and E for now

**Review by salichon — APPROVED** [review]
all good to me yay :) 
I saw a few  swap in the sorting compared to the csv files (smaller ones with same amplitude values) . Order and constituents label don't matter and are  still sorted n amplitudes. ..

**Review by ozym — APPROVED** [review]

**Pull request merged**
