### PR TITLE
fix: switch "Short Period Borehole Seismometer" to "Short Period Seismometer"

### PR DESCRIPTION
**Pull request by ozym**
This should allow Duke sensors on the web site

### CODE REVIEW

**Comment by elidana** [comment]
hi @ozym , this one looks good.

I don't think those are in use anymore, but that type is also used in:
```
resp/auto.go:		Type:         "Short Period Borehole Seismometer",
resp/auto.go:		Description:  "Duke University 2 Short Period Borehole Seismometer",
resp/auto.go:		Type:         "Short Period Borehole Seismometer",
resp/auto.go:		Description:  "Duke University 4.5 Short Period Borehole Seismometer",
```

should the auto.go also be updated or can we just ignore?

**Review by elidana — APPROVED** [review]

**Review by elidana — COMMENTED** [review]
this looks good, but have one question about the response yaml that might also need updating?

**Review by elidana — COMMENTED** [review]
I pushed approve button too early, repeating main comment here to make github happy

Shall the resp/responses/sensors/duke.yaml also be updated in those two entries?
```
resp/responses/sensors/duke.yaml:    type: Short Period Borehole Seismometer
resp/responses/sensors/duke.yaml:    type: Short Period Borehole Seismometer
```

**Comment by ozym** [comment]
That is the old system and is no longer used, I really should put in a PR to remove it completely.

**Comment by elidana** [comment]
ooh ok, so the fact they're obsolete is valid for both(augo.go and yaml files)
...ok, sorry for the confusion. 
And yes, would be good to tidy up anything that is not used!

**Review by elidana — APPROVED** [review]
looks good

**Comment by ozym** [comment]
@elidana https://github.com/GeoNet/delta/pull/2248

**Pull request merged**
