### PR TITLE
Adding Vaisala Weather Transmitters (WXT536) into assets

### PR DESCRIPTION
**Pull request by jacksonshanks**

### CODE REVIEW

**Comment by CBurton90** [comment]
@jacksonshanks This looks fine but when you are adding equipment can you give a little blurb about what they are for (I'll update the title for this PR). Looks like a useful all-in-one weather sensor though, I'll leave a link here for @salichon benefit : )

https://store.vaisala.com/en/products/WXT530#Description

**Comment by jacksonshanks** [comment]
sure thing, this is actually a typo in the repo stoping the merging of other works. so just resolving for now @CBurton90 could you please approve this?

**Review by CBurton90 — APPROVED** [review]
Happy to approve, although what is up with the `001` serial number? Is that a placeholder etc? You will likely need someone with delta merge permissions to merge this PR. @rumachan Is your best bet.

**Comment by jacksonshanks** [comment]
@CBurton90 please merge if you have the rights, cheers

**Pull request merged**
