### PR TITLE
Adding FW upgrades for Tuesday 11 October

### PR DESCRIPTION
**Pull request by meganmadley**
RGUT - 5946R40016 - 2022-10-10T20:52:24Z

### CODE REVIEW

**Comment by aleks-spes** [comment]
TKHL - 6015R40031 - 2022-10-10T20:30:19

**Comment by aleks-spes** [comment]
HORN - 5921R40171 - 2022-10-10T21:34:22

**Comment by meganmadley** [comment]
HANA - 5921R40176 - 2022-10-10T21:31:23

**Comment by meganmadley** [comment]
KAPT - 5946R40033 - 2022-10-10T22:27:32

**Comment by aleks-spes** [comment]
KAWK - 5949R40011 - 2022-10-10T22:35:55

**Comment by meganmadley** [comment]
@aleks-spes your times look good to me!

**Review by aleks-spes — APPROVED** [review]
Everything is fine!

**Pull request merged**
