### PR TITLE
Taiping Camera Swap

### PR DESCRIPTION
**Pull request by Camasher**

### CODE REVIEW

**Comment by Camasher** [comment]
@JonoHanson could you pass this on to someone to give me some help with why this is failing?

**Comment by ozym** [comment]
Entries need to be in order, i.e. model, serial etc. (below is showing what needs to be done).
```
--- FAIL: TestConsistency (0.06s)
    --- FAIL: TestConsistency/check_file_consistency:_cameras (0.00s)
        consistency_test.go:64: unexpected cameras.csv content -got/+exp
              strings.Join({
              	... // 29 identical lines
              	"Mobotix AG,M15,10.18.101.137,CVTP,0.5,290,-2.5,0,0,2019-07-08T00:50:00Z,2019-11-27T20:50:00Z,Tai Ping looking at East Ruapehu & South East Ngauruhoe",
              	"Mobotix AG,M15,10.18.101.137,CVTP,9.5,290,-2.5,0,0,2019-11-27T21:00:00Z,2020-05-07T00:18:00Z,Tai Ping looking at East Ruapehu & South East Ngauruhoe",
            - 	"Mobotix AG,M15,10.20.210.120,CVTP,9.5,290,-2.5,0,0,2020-05-07T00:19:00Z,9999-01-01T00:00:00Z,Tai Ping looking at East Ruapehu & South East Ngauruhoe",
              	"Mobotix AG,M15,10.18.101.33,WIWR,0,0,1.5,0,0,2016-10-03T06:14:00Z,9999-01-01T00:00:00Z,White Island West Rim looking into the crater",
              	"Mobotix AG,M15,10.18.168.61,CVWF,0,0,0,0,0,2016-06-01T23:40:00Z,9999-01-01T00:00:00Z,White Island Factory looking across the crater floor",
            + 	"Mobotix AG,M15,10.20.210.120,CVTP,9.5,290,-2.5,0,0,2020-05-07T00:19:00Z,9999-01-01T00:00:00Z,Tai Ping looking at East Ruapehu & South East Ngauruhoe",
              	"Mobotix AG,M15,10.20.245.115,TOTM,0,0,0,0,0,2018-05-03T00:00:00Z,9999-01-01T00:00:00Z,Karewerewa looking at TeMaari",
              	"Mobotix AG,M15,10.7.46.153,TOTM,0,0,0,0,0,2017-10-12T00:40:00Z,2018-05-02T23:55:00Z,",
              	... // 12 identical lines
              }, "\n")
FAIL
```

**Comment by JonoHanson** [comment]
thanks @ozym

**Comment by Camasher** [comment]
Thanks @ozym , @JonoHanson this is ready for review now that checks have passed

**Comment by staylorofford** [comment]
I am not sure what the timing conventions are for camera swaps, but for GNSS we would set the session end time as the time of first data in the new session - 1 second, and the session start time as the time of first data in the new session. In this case, first data in the new session occurs at `2020-05-07T00:20:00Z` so end time of the previous session would be `2020-05-07T00:19:59Z` and start time of the new session would be `2020-05-07T00:20:00Z`. Unless there is a good reason for the convention you have used, I would recommend using the one used for GNSS data.

@mnaguit and @salichon, would using this convention be in line with what is done for seismic data? It would be good to try align these conventions as much as possible across data types.

**Comment by staylorofford** [comment]
Further, @Camasher I suppose it is unorthodox for you to make this PR as a member of the RIM team as we would usually assign you or some other member of that team as a reviewer to meet the requirements as per https://github.com/GeoNet/tickets/blob/master/change_request_readme.md. Is there someone else on the RIM team you could assign to review?

**Comment by Camasher** [comment]
@staylorofford yeah that'd be fair. There is (was) 1FPS data stored that starts recording almost as soon as the camera is started/booted up (but seeing as this data is perishable, I think its acceptable to treat the 10 minute data going to the FTP as the change time. The one second gap makes sense, have updated to fit

**Comment by staylorofford** [comment]
If there is 1 second data in the archive, we'd need the metadata to reflect that, but it sounds like that is not the case.

**Comment by staylorofford** [comment]
@Camasher as above, I've added @ricardojohansson as a reviewer to meet the delta change review requirements. Once he reviews, it's good to merge.

**Comment by mnaguit** [comment]
> I am not sure what the timing conventions are for camera swaps, but for GNSS we would set the session end time as the time of first data in the new session - 1 second, and the session start time as the time of first data in the new session. In this case, first data in the new session occurs at `2020-05-07T00:20:00Z` so end time of the previous session would be `2020-05-07T00:19:59Z` and start time of the new session would be `2020-05-07T00:20:00Z`. Unless there is a good reason for the convention you have used, I would recommend using the one used for GNSS data.
> 
> @mnaguit and @salichon, would using this convention be in line with what is done for seismic data? It would be good to try align these conventions as much as possible across data types.

Hi. For seismic data & changes with tsunami sensors, we provide the data plots and look at the data gaps pertaining to the time the equipment was changed. From those plots, suggested closing & opening times are captured. Good demos for these in current tickets like TAUT and RPZ.

**Comment by Camasher** [comment]
Last image on old camera: 20200414T014000
First image on new camera: 20200507T000200

**Comment by staylorofford** [comment]
I suppose that comes back to the question of whether the times should reflect when the equipment was removed, or when the data ends? In the model I mention, we use the time of new equipment to close installations of old equipment, even if the equipment is removed before then as there is no data until the new equipment comes in. If we go based on data, then the camera would be uninstalled at the time of the fault that stopped data being produced, but that does not accurately reflect the installation. It is possible to accurately show when the equipment is removed, but if it makes no difference to the data one has to ask why that would be done? Perhaps we should discuss this elsewhere, or in more detail, in future.

**Comment by staylorofford** [comment]
@Camasher good to merge now.

**Comment by Camasher** [comment]
@staylorofford nah sorry mate, dont have permissions to merge this repo. You'll have to click the fancy button

**Comment by staylorofford** [comment]
my pleasure

**Pull request merged**
