### PR TITLE
MAGS re-open station

### PR DESCRIPTION
**Pull request by mnaguit**
Re-open station with LC 21. Recorder is CUSP3D SN 42172

### CODE REVIEW

**Comment by mnaguit** [comment]
I used the previous elevation. Let me know if this detail needs to be updated. @KOgeonet @CBurton90 

Also, kindly check if the changes made for `stations.csv` are correct (e.g. coordinates of the station are updated based on the coordinates of LC 21)

**Review by salichon — CHANGES_REQUESTED** [review]
hi There 
For consistency the station.csv location is not meant to change with the update, 
unless it was historically wrong significantly I reckon.
cheers!
jerome

**Comment by mnaguit** [comment]
Noted with thanks @salichon . Changes made on `stations.csv`

**Review by CBurton90 — APPROVED** [review]
Looks good. For the sites.csv I am assuming (from the previously installed CUSP) the coordinates are based upon WGS84 as the current CUSP did not specify the datum for it's coordinates.

**Review by salichon — APPROVED** [review]

**Comment by mnaguit** [comment]
Hi @ozym . Can you please review this PR? Thanks.

**Comment by mnaguit** [comment]
Hi @ozym . If you can review this PR, it would be great! Thanks!

**Review by ozym — APPROVED** [review]

**Pull request merged**
