### PR TITLE
MAVS:Clsing Bsalt 564,Opning Obsdian 582

### PR DESCRIPTION
**Pull request by salichon**
MAVS recorder change

### CODE REVIEW

**Comment by salichon** [comment]
@samgeonet 
You er pretty damn right!
Last MAVS data is 2018.034  UTC ( 3rd of february ~14:36)
You re right indeed the Basalt closure date is erroneous: 2018-01-16T00:00:00Z
Ihave been fooled by the latest (re)created archive file of the archive for the basalt that is 2018.015 so earlier. 
I ll correct to  this date 2018.034  UTC ( 3rd of february ~14:36) if you agree

**Comment by samgeonet** [comment]
I am checking if there is any data on the Basalt right now

**Comment by samgeonet** [comment]
I have found data in the archive folder on the Basalt from 18th Jan to 15th Feb I will copy to USB drive for someone to add to the archive

**Comment by salichon** [comment]
I ll hold that branch and will update the basalt end times accordingly when sorted
Thanks 
cheers

**Comment by salichon** [comment]
BTW @samgeonet  these dat seems to have recovered already ..

**Comment by samgeonet** [comment]
@salichon @nbalfour  do you want the triggered files as well?

**Comment by salichon** [comment]
@samgeonet 
last archived triggered files  are from 2016.

MAVS is meant to have HN too so why not.

**Comment by salichon** [comment]
@samgeonet I addressed Natalie too as a reviewer for confirmation of the closing/End date 
of the former basalt instrument on MAVS.

**Comment by salichon** [comment]
image

**Comment by salichon** [comment]
12Z components.

First data: 2018-02-14T06:32:48.500000Z
image

**Comment by salichon** [comment]
verified

**Pull request merged**
