### PR TITLE
WEL recorder swap

### PR DESCRIPTION
**Pull request by mnaguit**
from Basalt to Titan SMA

### CODE REVIEW

**Comment by mnaguit** [comment]
Hi @ozym . Thanks for your quick review of this.
I was about to ask in the next delta meeting if this one actually applies to the new set of TitanSMA naming. But I saw from the assets list that the Titan deployed in this station is already registered previously, along with a long list of Titan SMAs. 
So, a clarification: 
Do I need to modify both `assets/recorders.csv` and `intall/recorders.csv` files or just the latter, to adopt the TitanSMA naming?

**Comment by samgeonet** [comment]
@mnaguit I believe you need to change both so that they match

**Comment by mnaguit** [comment]
Changes made on this PR, as per our discussion in Delta meeting today.
@ozym @salichon @samgeonet

**Comment by mnaguit** [comment]
Hi @salichon & @samgeonet 
Just a gentle reminder. Can you please review this PR? Thank you.

**Comment by mnaguit** [comment]
Thanks @ozym 
Do the changes in this PR look ok with you @samgeonet & @salichon ? Thanks.

**Pull request merged**
