### PR TITLE
Add new Mobotix M16 camera assets

### PR DESCRIPTION
**Pull request by Camasher**

### CODE REVIEW

**Comment by Camasher** [comment]
@JonoHanson feel free to pass this to someone else too

**Review by rumachan — APPROVED** [review]
Looks fine, though I haven't checked the IP addresses!! BTW, Mark has changes in the wind for this file too

**Comment by Camasher** [comment]
> Looks fine, though I haven't checked the IP addresses!! BTW, Mark has changes in the wind for this file too

Yep, I'm trying to get my stuff sorted before he does haha. IP addresses in this case are the serial numbers, which are also the factory default ip addresses. The cameras bought late last year for 2020/2021 renewals hadn't been added to the delta system yet, and need to be to be able to update the delta install repo once the new camera period begins

**Review by JonoHanson — APPROVED** [review]
LGTM

**Comment by Camasher** [comment]
@JonoHanson @rumachan this is also ready for a merge

**Comment by Camasher** [comment]
@rumachan could you merge these please, I don't have permissions

**Comment by rumachan** [comment]
Done @Camasher

**Pull request merged**
