### PR TITLE
add trillium borehole T120-BH1

### PR DESCRIPTION
**Pull request by ozym**
An initial go at adding the Nanometrics Trillium Borehole T120-BH1

From the Iris NRL:

> There are several Trillium seismometer models that are represented by the same response, for example the Trillium 120Q or QA vault, Trillium 120 Posthole and Trillium 120 Borehole models, all of which are represented by the Trillium 120Q responses. Some Trillium sensors have been built with different feedback electronics over time. These changes are referred to as "generations" and can be determined by serial number. The table below shows this correlation.

I'm assuming a generation 3 (i.e. serial > 200) so the response should be along the lines of the 120Q. I'm also assuming a name of "Trillium Borehole T120-BH1"  and that the sensors will be aligned Z12 as per a standard borehole.

Needs to be verified against the instrument's output etc.

### CODE REVIEW

**Comment by salichon** [comment]
@ozym thanks

1-  i just saw  a previous commit over Delta (https://github.com/GeoNet/delta/commit/60bccb0c726c6df72f7d6448ee9245aaf4e17525)

I guess they are the same  (besides `B1` to `BH1` commit title) ? 

2- having a browse through the files 
-  `Auto.go` generated 
 for    `TRILLIUM-BOREHOLE-T120-BH1` is using the  `TRILLIUM-120QA` Poles and zeroes and filters
 with the `"Trillium Borehole T120-BH1"` sensor 
so 
- in resp/responses/sensors/nanometrics.yaml 
I saw the references  for the response   the BH1 although no mention to the sensor model `Trillium Borehole T120-BH1` in  the ` sensor-model: ` field  

Does this  come on a later stage ? 

Cheers!
jerome

**Review by mnaguit — APPROVED** [review]
I checked the poles & zeroes and instrument gain. All good.

References:
- https://ds.iris.edu/NRL/sensors/nanometrics/RESP.XX.NS331..BHZ.Trillium120Q_g3.120.1203
- https://ds.iris.edu/NRL/sensors/nanometrics/nanometrics_trillium_sensors.html

**Comment by ozym** [comment]
> @ozym thanks
> 
> 1- i just saw a previous commit over Delta ([60bccb0](https://github.com/GeoNet/delta/commit/60bccb0c726c6df72f7d6448ee9245aaf4e17525))
> 
> I guess they are the same (besides `B1` to `BH1` commit title) ?
> 
> 2- having a browse through the files
> 
> * `Auto.go` generated
>   for    `TRILLIUM-BOREHOLE-T120-BH1` is using the  `TRILLIUM-120QA` Poles and zeroes and filters
>   with the `"Trillium Borehole T120-BH1"` sensor
>   so
> * in resp/responses/sensors/nanometrics.yaml
>   I saw the references  for the response   the BH1 although no mention to the sensor model `Trillium Borehole T120-BH1` in  the `sensor-model:` field
>   Does this  come on a later stage ?
> 
> Cheers!
> jerome

What you see in the resp/responses/sensors/ yaml files are the filters that can be used (by convention they are upper case). These are attached to actual sensors in the resp/configuration files.   There may be a number of sensors with the same response so they can be joined here.

All these yaml files  get turned into the `auto.go` program for easy lookup.

**Comment by CBurton90** [comment]
Looks good to me. Checked the PAZ against the downloaded stationXML from the Centaur deployed at NIC with the T120-BH1 and all matches up. Attached are the response files for reference. 

[NZ.NIC.10.xml.zip](https://github.com/GeoNet/delta/files/6511467/NZ.NIC.10.xml.zip)

**Review by CBurton90 — APPROVED** [review]

**Review by salichon — APPROVED** [review]

**Pull request merged**
