### PR TITLE
MENS Basalt to EQR120 SM sensor swap

### PR DESCRIPTION
**Pull request by Thomas-Benson**
- Remove Kinemetrics Basalt(622) from location 20
- Replacing with CSI EQR120(46618), firmware version 2.3.2
- New sensor orientation N(0), streams changing from axial to non-axial

### CODE REVIEW

**Review by CBurton90 — APPROVED** [review]

**Comment by mnaguit** [comment]
We have the option not to correct the archive if we use these timing:
`Closing` ----- `June 30, 2023/03:07UTC` (approximate end for `12Z`)
`Opening` ----`June 30,2023/03:08UTC` (start of `ENZ`)

What do you think? @Thomas-Benson

**Comment by Thomas-Benson** [comment]
@mnaguit should that timing be for everything, or just for install/streams.csv?

**Comment by mnaguit** [comment]
For all entries, thanks @Thomas-Benson

**Comment by Thomas-Benson** [comment]
@mnaguit updated timings

**Review by mnaguit — APPROVED** [review]
👍

**Pull request merged**
