### PR TITLE
OAHZ Ouaha Hills

### PR DESCRIPTION
**Pull request by mnaguit**
- temporary station for Taupo response
- LC 10 (LH/HH-EHZ) & LC 20 (HN-ENZ) streams
- sensors: TC120-PH2 and Guralp Fortis
- datalogger: Centaur (firmware v4.5.20)
- network code is TP?

### CODE REVIEW

**Comment by salichon** [comment]
this is loads and loads of commits.. :)

**Comment by mnaguit** [comment]
> this is loads and loads of commits.. :)

Yeah, sorry for that Sir @salichon . Building up the metadata for new stations is not entertaining at all! 😸

**Comment by CBurton90** [comment]
@mnaguit This looks good, I might just hold off until after today's delta meeting in case `TP` is changed to `XX` 😬

**Review by ozym — APPROVED** [review]

**Review by CBurton90 — APPROVED** [review]

**Comment by mnaguit** [comment]
Yay! Thanks Gentlemen! Very happy we're done with this 😄

**Pull request merged**
