### PR TITLE
GNSS ANAU equipment receiver swap

### PR DESCRIPTION
**Pull request by meganmadley**
Might create conflicts with QUAR and WMAT will deal with those as they come up

### CODE REVIEW

**Review by aleks-spes — APPROVED** [review]
Looks good!

**Comment by meganmadley** [comment]
Sorry @aleks-spes had to make another commit to resolve the conflicts, can you please review this again? Feel free to wait to review WMAT until after this one has been merged (as it will have the same problem)

**Comment by aleks-spes** [comment]
No worries @meganmadley!  I have review WMAT already, so probably you should assign me there again :)

**Review by aleks-spes — APPROVED** [review]
Looks good!

**Review by CBurton90 — APPROVED** [review]

**Pull request merged**
