### PR TITLE
Swap DISC discoverylodge M12 camera to M16

### PR DESCRIPTION
**Pull request by Camasher**
Theres definitely a few things in this repo that need to be cleaned up....

### CODE REVIEW

**Comment by Camasher** [comment]
Just need to add correct timing and orientation details

**Review by rumachan — COMMENTED** [review]
Are the dates correct? You are adding the M16 on Saturday morning?

It's a bit hard to judge as your changes and Mark's are overlapping. I assume the reference to Mountain Air is because Mark will be adding a change to correct this?

**Comment by Camasher** [comment]
Have updated times to match true last and first images. HAve updated tilt and orientation.

**Comment by staylorofford** [comment]
Superceded by https://github.com/GeoNet/delta/pull/1064

**Pull request closed without merging**
