### PR TITLE
GLKZ change tsunami sensor

### PR DESCRIPTION
**Pull request by mnaguit**
from Druck PTX-1830-LAND to Druck PTX-1830

### CODE REVIEW

**Comment by mnaguit** [comment]
Modifications made. Thanks @ozym . 👍 
Team, can you please do another round of review?

**Comment by ozym** [comment]
this may need to be updated in the assets file as well.

**Comment by mnaguit** [comment]
Oh, that's why there's a Travis error.

> this may need to be updated in the assets file as well.

**Comment by mnaguit** [comment]
Thanks for the quick review team. Gonna merge this one. 👍

**Pull request merged**
