### PR TITLE
initial rework of camera mounts and views

### PR DESCRIPTION
**Pull request by ozym**
An initial attempt to get the camera codes and views switched over. I haven't looked at the location information (lat/lon) or any changes to orientation as I expect that to be the next step.

### CODE REVIEW

**Review by rumachan — CHANGES_REQUESTED** [review]
There is a lot here, and I'm not familiar with the changes in instrumentation.

cameras.csv
DISC entries still have Mountain Air in the text field, need to say Discovery Lodge.
Why is there a double entry for RIMK M12 camera, one 2010-14 another 2014-17. They don't overlap, probably its just historic?
Olympus,CAMEDIA-C860L,46170127,WICF,01,0,306,0,0,0,2001-10-12T12:00:00Z,2009-02-10T00:00:01Z,
Olympus,CAMEDIA-C820L,24043997,WICF,01,0,0,0,0,0,2009-02-10T00:00:03Z,2009-10-27T22:00:00Z,

Split between WIFW.01 and WIFC.01 as per my table.

marks.csv
Need to add WIFC (White Isand Factory). It's intermediate in occupation time between WIFW (on factory wall), and current site WICF (crater floor)

views.csv
WHHB situated at Whakatane harbour
WICF situated on crater floor at the base of Troup Head
add WIFC situated on crater floor, ~100 m south-east of abandoned sulphur works.

**Comment by ozym** [comment]
Thanks @rumachan this is probably going to take a few more loops. Here's the next batch of changes.

**Review by rumachan — CHANGES_REQUESTED** [review]
I don't think you changed the descriptors in views.csv. Can you check those?

WHHB situated at Whakatane harbour
WICF situated on crater floor at the base of Troup Head
add WIFC situated on crater floor, ~100 m south-east of abandoned sulphur works.

**Comment by ozym** [comment]
> I don't think you changed the descriptors in views.csv. Can you check those?
> 
> WHHB situated at Whakatane harbour
> WICF situated on crater floor at the base of Troup Head
> add WIFC situated on crater floor, ~100 m south-east of abandoned sulphur works.

This is where it gets a bit tricky as these are related to the captions and descriptions that (would) go into the images and labels on the web.  I've just left them as is (where it's just a code change) - we can revisit this for historical cameras and update new ones etc.

**Comment by ozym** [comment]
@rumachan have updated the views as per your comments.

**Comment by rumachan** [comment]
Yes, I believe I made all the changes to the big table in https://github.com/GeoNet/tickets/issues/576

**Comment by JonoHanson** [comment]
@rumachan are the changes you requested either done or not required? that needs to be resolved before we can merge this

**Review by rumachan — APPROVED** [review]

**Pull request merged**
