### PR TITLE
chore: standardize citations in classes.csv

### PR DESCRIPTION
**Pull request by elidana**
reference paper is  : https://bulletin.nzsee.org.nz/index.php/bnzsee/article/view/91
source table is: http://dx.doi.org/10.21420/G26P4C

### CODE REVIEW

**Comment by elidana** [comment]
Hi @mnaguit 
after an initial round, here's the list of unique values in the citations column. Still need some work and tidy up

Next step: decide how to handle the extra notes that are not referring to a published paper or report

```
Barker1994 Cousins1996    
Boon2010    
Boon2010 McVerry2011    
Boon2010 Perrin2015    
Boon2010 Perrin2015; McVerry2011    
"Boon2010 Perrin2015  Unpublished ReMi (Kaiser & Louie)"   
"Boon2010  Unpublished HVSR (A. Kaiser)"   
(conflicts exist with Perrin2015)    
(conflicts with Perrin2015)    
Cousins1996    
Cousins1996 (some conflicts with Perrin2015)    
"Cousins1996  Unpublished HVSR (C. Van Houtte) "   
"Cousins1996  Unpublished ReMi (Kaiser & Louie)"   
"Kaiser2013  Cousins1996 (some conflicts with Perrin2015)"   
Kaiser2013; Dorn et al. 2010    
Kaiser2013; Kaiser et al. 2014    
Kaiser2013; McVerry2011    
"Kaiser2013  Perrin2015"   
Kaiser2013; Perrin2015    
"Kaiser2013; Perrin2015  Lee2015"   
"Kaiser2013  Unpublished HVSR (C. Van Houtte)"   
Kaiser2013; Unpublished MASW (C. Van Houtte)    
Kaiser2013; VanHoutte2012    
Massey et al. 2016; Kaiser et al. 2014    
McVerry2011    
McVerry2011     
McVerry2011 (alternative bedrock models available)    
McVerry2011 at 032A (some conflicts with Perrin2015)    
McVerry2011 at 051B; Unpublished HVSR (C. Van Houtte)    
"McVerry2011 at 055A  Unpublished HVSR (C. Van Houtte); Perrin2015"   
McVerry2011 at 226B    
"McVerry2011; borehole data  nearby WCDS (some conflicts)"   
McVerry2011; Perrin2015 (some conflicts)    
" McVerry2011  see HOCS "   
McVerry2011; see PGMS     
"McVerry2011  see QTPS"   
McVerry2011 Semmens2010    
McVerry2011; Semmens2010    
McVerry2011; Semmens2010; Unpublished ReMi data (A. Kaiser & J. Louie); Unpublished HVSR (A. Kaiser & C. Van Houtte)    
"McVerry2011; Semmens2010; Unpublished ReMi data (A. Kaiser & J. Louie)  Unpublished HVSR (C. Van Houtte)"   
"McVerry2011; Semmens2010  Unpublished ReMi (Kaiser & Louie)"   
McVerry2011; Unpublished HVSR (C. Van Houtte)    
McVerry2011; Unpublished HVSR (C. Van Houtte)     
Notes    
Perrin2015    
Perrin2015     
Perrin2015; Boon2010    
Perrin2015; Boon2010 Nearby unpublished ReMi (Kaiser & Louie)    
"Perrin2015; Boon2010  Nearby Unpublished ReMi (Kaiser & Louie)"   
"Perrin2015; Boon2010  Unpublished ReMi (Kaiser & Louie)"   
Perrin2015; Carpentier2013    
Perrin2015 (conflicts exist with Cousins1996)    
"Perrin2015 (conflicts exist with Cousins1996)  Unpublished HVSR (A. Kaiser)"   
Perrin2015 (conflicts with Cousins et al.)    
"Perrin2015  Cousins1996"   
"Perrin2015  Cousins1996 (conflicts exist)"   
"Perrin2015  Cousins1996  see 028A"  
"Perrin2015  Cousins1996 (some conflicts)"   
"Perrin2015  Cousins1996  Unpublished HVSR (A. Kaiser)"  
Perrin2015; HVSR at station HDWS    
"Perrin2015  Kaiser2013"   
Perrin2015; Kaiser2013    
"Perrin2015; Kaiser2013  Lee2015"   
Perrin2015 Lee2015    
"Perrin2015  Lee2015"   
Perrin2015; McVerry2011 (some conflicts)    
Perrin2015; McVerry2011; Unpublished HVSR (C. Van Houtte)    
Perrin2015; McVerry2011; Unpublished HVSR (C. Van Houtte) (conflicts exist)    
"Perrin2015  near 642A"   
Perrin2015; nearby station 294A    
Perrin2015; see site 120A/B; Unpublished HVSR (C. Van Houtte)    
"Perrin2015  Semmens2010"   
Perrin2015; Semmens2010    
Perrin2015; Semmens2010; Taber1992    
Perrin2015 (some conflicts with Cousins1996)    
Perrin2015 Taber1991    
"Perrin2015  Unpublished HVSR (A. Kaiser)"   
Perrin2015; Unpublished HVSR (A. Kaiser)    
Perrin2015; Unpublished HVSR (A. Kaiser & C. Van Houtte)    
Perrin2015; Unpublished HVSR (A. Kaiser); McVerry2011 (some conflicts)     
"Perrin2015  Unpublished HVSR (A. Kaiser) (some conflicts)"   
"Perrin2015  Unpublished HVSR (C. Van Houtte)"   
Perrin2015; Unpublished HVSR (C. Van Houtte)    
Perrin2015; Unpublished HVSR (C. Van Houtte % A. Kaiser)    
"Perrin2015  Unpublished ReMi (Kaiser & Louie)  Boon2010"  
Semmens2010    
Semmens2010; McVerry2011 (some conflicts)    
Semmens2010; Taber1992; Unpublished ReMi (Kaiser & Louie)    
Semmens2010; Unpublished HVSR (A. Kaiser)    
"Semmens2010; Unpublished HVSR (A. Kaiser)  Unpublished ReMi (Kaiser & Louie)"   
"Semmens2010; Unpublished HVSR (C. Van Houtte)  Unpublished ReMi (Kaiser & Louie)"   
"Stephenson1992  Unpublished ReMi (Kaiser & Louie)"   
Stephenson1999; Barker 1996    
Stephenson2011 Perrin2015 Kaiser2013 Lee2015    
Unpublished HVSR (A. Kaiser)    
Unpublished HVSR (A. Kaiser); Boon2010    
Unpublished HVSR (A. Kaiser & C. Van Houtte)    
"Unpublished HVSR (A. Kaiser & C. Van Houtte)  Cousins1996"   
Unpublished HVSR (A. Kaiser & C. Van Houtte); Perrin2015    
Unpublished HVSR (A. Kaiser & C. Van Houtte); Semmens2010 (some conflicts)    
Unpublished HVSR (A. Kaiser); Kaiser & Louie 2006    
Unpublished HVSR (A. Kaiser); Perrin2015    
"Unpublished HVSR (A. Kaiser)  Perrin2015 (some conflicts with Cousins1996)"   
Unpublished HVSR (C. Van Houtte)    
Unpublished HVSR (C. Van Houtte & A. Kaiser)    
Unpublished HVSR (C. Van Houtte & A. Kaiser); Perrin2015    
Unpublished HVSR (C. Van Houtte) (conflicts exist)    
Unpublished HVSR (C. Van Houtte) (conflicts exist with Cousins1996)    
Unpublished HVSR (C. Van Houtte) (conflicts with Perrin2015)    
"Unpublished HVSR (C. Van Houtte)  Cousins1996 "   
Unpublished HVSR (C. Van Houtte); Kaiser2013    
Unpublished HVSR (C. Van Houtte); Kaiser2013; Perrin2015    
Unpublished HVSR (C. Van Houtte); McVerry2011    
"Unpublished HVSR (C. Van Houtte)  McVerry2011 at 129A "   
"Unpublished HVSR (C. Van Houtte); McVerry2011 at 240A  Perrin2015 (some conflicts with 240A in McVerry2011)"   
"Unpublished HVSR (C. Van Houtte)  McVerry2011 at 708A"   
"Unpublished HVSR (C. Van Houtte)  McVerry2011 at 940A"   
"Unpublished HVSR (C. Van Houtte)  Perrin2015"   
Unpublished HVSR (C. Van Houtte); Perrin2015    
"Unpublished HVSR (C. Van Houtte)  Perrin2015  Stephenson1999"  
"Unpublished ReMi data (GNS  A. Kaiser & J. Louie); Unpublished HVSR (A. Kaiser)"   
"Unpublished ReMi data (GNS  A. Kaiser & J. Louie); Unpublished HVSR (C. Van Houtte)"   
"Unpublished ReMi data (GNS  A. Kaiser & J. Louie); Unpublished HVSR (C. Van Houtte)  Boon2010"  
VanHoutte2012; Kaiser2013; Perrin2015    
VanHoutte2012; Perrin2015    
Wotherspoon2014 Wotherspoon2015    
"Wotherspoon2014 Wotherspoon2015 Kaiser2013  Lee2015"   
"Wotherspoon2014 Wotherspoon2015 Kaiser2013; VanHoutte2012; Jeong2015"    
"Wotherspoon2014 Wotherspoon2015 Lee2015"
```

**Comment by mnaguit** [comment]
Suggested citation key:

- Unpublished ReMi (Kaiser & Louie) / / Unpublished ReMi data (GNS  A. Kaiser & J. Louie): `Kaiser2006`
- Unpublished HVSR (A. Kaiser) : `Kaiser2015`
- Unpublished HVSR (C. Van Houtte): `VanHoutte2015`
- Unpublished MASW (C. Van Houtte): `VanHoutte2012`
- Unpublished HVSR (A. Kaiser & C. Van Houtte) / Unpublished HVSR (C. Van Houtte & A. Kaiser): `Kaiser2015` `VanHoutte2015`
- Kaiser & Louie 2006: `Kaiser2006`

Conflict (eg., non-unique author/date)
- `Kaiser2006`
  - Kaiser & Louie 2006: Kaiser2006 --> `Kaiser2006A`
  - Unpublished ReMi (Kaiser & Louie): `Kaiser2006`  --> `Kaiser2006B`

- `VanHoutte2012`
  - Van Houtte, C.; Ktenidou, O-J.; Larkin, T.; Kaiser, A.E. (2012): `VanHoutte2012A`
  - Unpublished MASW (C. Van Houtte): `VanHoutte2012B`

Note:
- from quick checking, it looks like all other keys are unique
- reference details are available (https://github.com/GeoNet/data/tree/main/site-class/concise)

**Comment by elidana** [comment]
just noting here for reference (based on references in https://github.com/GeoNet/data/tree/main/site-class/concise):
- `Kaiser2006a` = Kaiser, A.E.; Louie, J.N. (2006). "Shear-wave velocities in Parkway basin, Wainuiomata, from refraction microtremor surface wave dispersion". Lower Hutt: GNS Science. GNS Science report 2006/24. 16 p. + 1 CDROM
- `Kaiser2006b` = Kaiser, A.; Louie, J. (2006). Unpublished refraction microtremor (ReMi) surveys of Wellington the Lower Hutt, held at GNS Science.

**Comment by mnaguit** [comment]
> thanks @mnaguit ! have a question:
> are these two the same? (and just authors inverted?)
> Unpublished HVSR (A. Kaiser & C. Van Houtte): Kaiser2015
> Unpublished HVSR (C. Van Houtte & A. Kaiser): VanHoutte2015
> 

Not really sure, but there are 2 separate entries on the list. But same description aye? 🤷 

- `Kaiser, A. (2015). Unpublished HVSR held at GNS Science.`
- `Van Houtte, C. (2015). Unpublished HVSR held at GNS Science.`

Thinking in the background, a good next step when all these are sorted would be to collect copies of these reports/papers and probably store in a database for easy access/quick reference.

**Comment by elidana** [comment]
uh yes, that's a great idea! 

for the 2015 citation....Maybe we can check with Anna for that one? or the original table, wherever that is? 
yes, the description is exactly the same (and I had to google what HSVR , but looks like whatever result came from an experiment held at GNS in 2015...)

**Comment by elidana** [comment]
@mnaguit , if you look at the reference paper (https://bulletin.nzsee.org.nz/index.php/bnzsee/article/view/91) there are only two references to unpublished work (one is ReMi and one is HSVR)
I just did a quick look, but maybe you know that paper well? I also think we should double check the references based on that (rather than just copy paste from the `GeoNet/data` repository

**Comment by elidana** [comment]
@mnaguit , I finished polishing the citation files, and added entries for individual papers in the references folder. Can you please carefully review, and potentially add the references in the currently semi empty `references/citations.csv` please?
The second bit can be done on a separate pr or just here.

**Comment by mnaguit** [comment]
> @mnaguit , if you look at the reference paper (https://bulletin.nzsee.org.nz/index.php/bnzsee/article/view/91) there are only two references to unpublished work (one is ReMi and one is HSVR)

> Based on the reference list in the original paper, I propose to use the following for any "Unpublished HSVR...." entry:
> 
> VanHoutte2017 - Van Houtte C and Kaiser A (2017). Unpublished HVSR measurements at GeoNet strong motion sites based on earthquake HVSR, held at GNS Science.
> not sure where you got the 2015 from, but hopefully that's ok?
> 

Hi @elidana . I haven't checked this paper at all. I am just cross checking with the reference list already available here: https://github.com/GeoNet/data/tree/main/site-class/concise

**Comment by mnaguit** [comment]
I have added entries in `references/citations.csv` @elidana

**Comment by elidana** [comment]
thanks @mnaguit !!!
I think there might be a format error in the `citations.csv`
> It looks like row 13 should actually have 10 columns, instead of 11. in line 12.

but great you added all! <3

**Review by mnaguit — APPROVED** [review]

**Pull request merged**
