### PR TITLE
2Hz Duke Malin and Centaur response combination (x40 gain / 1Vpp)

### PR DESCRIPTION
**Pull request by CBurton90**

### CODE REVIEW

**Review by ozym — APPROVED** [review]
Looks good, when should check the first deployment.

**Comment by CBurton90** [comment]
> Looks good, when should check the first deployment.

@ozym I can download a StationXML directly off the box for comparisons. Probably no PAZ entries but was able to set a passive sensor with 62.2 V/m/s in the sensor library.

**Comment by salichon** [comment]
This set  (x40 gain / 1Vpp) (for Centaur)  will be "reserved" to borehole sensors?
 (and is it whatever they are ?) 
 This will allow microseismicity sensibility. - sweet - can this be docuemented somewhere ? thanks

**Comment by salichon** [comment]
This is looking good.

Would you remind me the definition of the  "reversed" parameter in the `shortperiod` yaml?   @CBurton90 
It looks like it appears with the Senso but also with the dalagger filters.
ta.

**Review by salichon — APPROVED** [review]
i give it a go - looks good :)

**Comment by CBurton90** [comment]
> This set (x40 gain / 1Vpp) (for Centaur) will be "reserved" to borehole sensors? (and is it whatever they are ?) This will allow microseismicity sensibility. - sweet - can this be documented somewhere ? thanks

*reserved for sensors with low sensitivities/output, in this case specific to the 2Hz Duke Malin sensor (this is not specific to boreholes).

**Comment by CBurton90** [comment]
> This is looking good.
> 
> Would you remind me the definition of the "reversed" parameter in the `shortperiod` yaml? @CBurton90 It looks like it appears with the Senso but also with the dalagger filters. ta.

@ozym any comment? I thought it may be related to component order (Z12 vs 21Z etc) but I'll let Mark answer.

**Comment by CBurton90** [comment]
Also can somebody with delta merge permissions please merge this after the review are complete. Thank you.

**Comment by ozym** [comment]
Reversed means it's wired backwards, up is down etc.

**Comment by CBurton90** [comment]
@salichon @ozym can one of you merge this PR please : )

**Comment by salichon** [comment]
KK @CBurton90  i m on it :0

**Comment by salichon** [comment]
before i merge @CBurton90 
Question  Does the choice  of the term  `Paz` for the `Preamp gain`    as opposed to `a2d` type of filter makes sense ? 
(me trying to understand...)

**Comment by ozym** [comment]
A pre-amp should change from Volts to Volts, whereas an A2D should go from Volts to Counts.

**Comment by ozym** [comment]
But there are multiple ways of expressing this, paz is just one of them (i.e. no poles/zeros).

**Pull request merged**
