### PR TITLE
DSZ strong Loccode 20 to 21 - **2016 Legacy Correction**

### PR DESCRIPTION
**Pull request by salichon**
Back dating a site change (20 top 21)

Instrumentation and its location have changed 
Date chosen to fit what seen on traces  

This will be paired to a AWS archive data change to match the change (20-->21) as planned in 
https://wiki.geonet.org.nz/pages/viewpage.action?pageId=89129731

### CODE REVIEW

**Review by ozym — APPROVED** [review]
assumed sensor in vault was replaced by recorder in shed

**Comment by salichon** [comment]
> assumed sensor in vault was replaced by recorder in shed
thanks @ozym 
 and that means (i had a look again ... to be sure ... )
   the replacing  Q330/S6 datalogger 
  `Kinemetrics,Q330S/6,6049,Denniston North,,2016-11-09T23:15:00Z,9999-01-01T00:00:00Z` is reserved to the broadband uniquely -

**Comment by mnaguit** [comment]
Thanks @salichon 
Out of curiosity, was there an equipment change ticket for the datalogger change? Reference ticket on the main refers to the change in recorder back in 2019. Just checking, as part of the review process.

**Comment by salichon** [comment]
> Out of curiosity, was there an equipment change ticket for the datalogger change? Reference ticket on the main refers to the change in recorder back in 2019. Just checking, as part of the review process.

Hello @mnaguit indeed  - thanks! 
 i just refered these into the DSZ loccode change tickets

**Review by mnaguit — APPROVED** [review]
Ok. It looks like a lot of 'historical changes' for this site. I can only verify the ones with the existing equipment change ticket. Opening & closing times are consistent for each metadata component.

**Pull request merged**
