### PR TITLE
FOZ Location code 2015 FIX

### PR DESCRIPTION
**Pull request by salichon**
2015 site  change not accounted for,  now it is
10->11
20->21 
as per : https://github.com/GeoNet/tickets/issues/3705

### CODE REVIEW

**Comment by salichon** [comment]
FYI @samgeonet

**Comment by ozym** [comment]
@samgeonet this is related to the `dataloggers.csv` file.

You will see an entry in that file for:
```
Kinemetrics,Obsidian 4X Datalogger,716,The Sugar Loaf Quarry,Strong Motion,2017-03-16T00:00:01Z,9999-01-01T00:00:00Z
```

The `Strong Motion` entry maps the sensor (in the connections file) to this datalogger.

Whereas the Q330 has an empty field (which again is mapped by the empty field in the connections file). It could easily (and probably should) have a entry "Broadband" ...
```
Kinemetrics,Q330S/6,5440,The Sugar Loaf Quarry,,2017-03-14T21:20:01Z,9999-01-01T00:00:00Z
```

**Comment by ozym** [comment]
This would have been part of a more general cleanup related to what was actually recorded.

**Comment by salichon** [comment]
@samgeonet This strong motion was already added, i just change dthe location code on that line. :).

Perhaps strong motion should be added to the other 20s although not a priority  - I dunno the rules there.

**Comment by salichon** [comment]
..And i ll complete the PR with  your requests

**Comment by salichon** [comment]
@ozym
Hello about FOZ datalogger/connections interation.
 and FOZ former Q330 datalogger
Did the
 "kinemetrics,Q330/6,498,The Sugar Loaf Quarry,Broadband,2004-10-13T00:00:00Z,2017-03-14T21:20:00Z"  was used for both strong motion and broadband (6 channels) meaning part of my commits is wrong ?

**Comment by salichon** [comment]
@ozym @samgeonet 
Thanks ! I reverted accordingly the above advices
This should be allright from now

Cheers
Jerome

**Comment by samgeonet** [comment]
@salichon let me know when you merge this one and I will change the location code of the Obsidian on site

**Comment by salichon** [comment]
@samgeonet 
i m going to merge this
cheers
hi there merged it is! sorry for the delay

**Comment by samgeonet** [comment]
@ozym Obsidian changed to location code 21 12pm 12/12/18 NZDT

**Comment by ozym** [comment]
Thanks @samgeonet

**Comment by samgeonet** [comment]
@ozym Also the new Q330 should be on 11

**Comment by salichon** [comment]
@samgeonet: confirmed new incoming data are archived as such

**Pull request merged**
