### PR TITLE
CPXB array recorder upgrade

### PR DESCRIPTION
**Pull request by mnaguit**
from CUSPM to CUSP-Me

### CODE REVIEW

**Review by CBurton90 — APPROVED** [review]
As long as it's definitely a change from HN1 | 2 | Z to HNX | Y | Z (non-axial) then looks good!

**Review by salichon — APPROVED** [review]
yup

**Comment by mnaguit** [comment]
Hi @ozym . Are the changes in this array looking good? Thanks.

**Review by ozym — APPROVED** [review]
noting the switch on components.

**Pull request merged**
