### PR TITLE
fix: update ABAZ streams

### PR DESCRIPTION
**Pull request by ozym**
The sensor was swapped from a short period (EH?) to broadband (HH?) so the streams listing needs updating

### CODE REVIEW

**Review by Thomas-Benson — APPROVED** [review]
LGTM, but noting that the site is still streaming EH?

**Comment by ozym** [comment]
@CBurton90 see above, does any of this make sense?

**Comment by ozym** [comment]
@Thomas-Benson @elidana has been confirmed that the sensor is broadband, but the channels weren't renamed. Once merged, this will need to be added to the "fixup" ticket to rename the channels that have been created since the sensor swap.

**Comment by moorematthew** [comment]
@ozym @Thomas-Benson Also needs a location code update. Sensor has moved from vault to direct bury. 
Apologies this was missed on install

**Comment by moorematthew** [comment]
Update from centaur 

Capture

**Comment by ozym** [comment]
@Thomas-Benson could you check the newly installed sensor location (lives in sites.csv under  ABAZ/11) and update if needed.

**Review by Thomas-Benson — APPROVED** [review]
lgtm

**Pull request merged**
