### PR TITLE
LPOC closure

### PR DESCRIPTION
**Pull request by mnaguit**
For review LPOC closure

### CODE REVIEW

**Comment by salichon** [comment]
@mnaguit o for the review you can shift one reviewer for one another from the same team if not available.
For instance @me or John Ristau ;)  
- as per the guidelines we set.

CC/ @jristau 
Cheers
j

**Comment by mnaguit** [comment]
Hi @salichon. Thanks.
Will wait for @nbalfour to review

**Comment by salichon** [comment]
@mnaguit  you may seek to merge that pull request soon, so that its no more blocking another one see #273.
Ask Natalie, John or me to finalize the last review. (basically just or almost a thumb up )

**Comment by mnaguit** [comment]
Noted, Sir Jerome. I'll add you in the reviewers then. @salichon

**Comment by salichon** [comment]
Last archived data from LPOC is from 2015.190.

**Comment by salichon** [comment]
:+1:

**Pull request merged**
