### PR TITLE
update from db

### PR DESCRIPTION
**Pull request by ozym**

### CODE REVIEW

**Comment by nbalfour** [comment]
In the firmware file, one of the comments uses quotations while the rest don't. Is this an issue?

**Comment by elidana** [comment]
good spotting @nbalfour , thanks! I'll make them the same, without quotes

**Comment by ozym** [comment]
@elidana @nbalfour I've reloaded the delta tables for the firmware changes. As these files are csv format they will (i.e automatically) add double quotes around any fields that have commas in them.

**Comment by elidana** [comment]
@ozym , I've now modified that sentence to be without commas. Apologize for the extra work

**Comment by ozym** [comment]
@elidana I've updated the firmware notes, and one monument change slipped in as well (see below).

The format is "csv" i.e. https://en.wikipedia.org/wiki/Comma-separated_values so it's a little sensitive to commas. It's not a problem in the DB or the files, just a side-effect of using this format.

```
74c74
< LRR1,,Forced Centering,Unknown,0,Unknown,0,2016-11-15T00:00:00Z,2017-05-22T00:00:00Z,,
---
> LRR1,,Forced Centering,Steel Mast,0,Stainless Steel Rod,0,2016-11-15T00:00:00Z,2017-05-22T00:00:00Z,,

```

**Comment by elidana** [comment]
@ozym , sorry if it took so long to reply. Yesterday (and I'm still finalizing it). I was reviewing the _Marks_ and _Monuments_ definition for the temporary sites installed after the Kaikoura eq. Happy for you to merge this pr.

**Comment by ozym** [comment]
really just waiting on @samgeonet

**Pull request merged**
