### PR TITLE
update building array streams

### PR DESCRIPTION
**Pull request by ozym**
This PR updates the streams file to add the building array channel code details.

Basically adds  BN for 50 Hz, and HN for 100 Hz.

The CPLB location 2G is still a mystery, not sure what datalogger the probe was connected to.

### CODE REVIEW

**Comment by ozym** [comment]
Also updated the channels / components files for the CuspM and Cusp-Me devices.

**Review by mnaguit — APPROVED** [review]
Looks good @ozym . Thanks. Some feedback herein:

- LC 2G at CPLB is indeed mysterious. Random data checking shows flat lines at 2G.  
- For the components, is the 12Z/XYZ channel code relevant?

**Comment by ozym** [comment]
Good point, I'll check but there is another mechanism to override 21z with xyz.

**Comment by ozym** [comment]
@mnaguit is there a list of xyz vs 21z?

**Comment by mnaguit** [comment]
@ozym 
here's a summary:
https://gns-science.atlassian.net/wiki/spaces/dmcops/pages/2119499577/Structural+array+Summary+of+streams+and+sensors

**Pull request merged**
