### PR TITLE
GRAS new station 

### PR DESCRIPTION
**Pull request by mnaguit**
For East Cape event response
With LC20, 21 & 22
Continuous HN(12Z) streams
EQR120 Firmware v.08

### CODE REVIEW

**Comment by mnaguit** [comment]
Hi @salichon @ozym @CBurton90 
I'm experiencing Travis error for this PR. Any idea/s which to modify in the PR?
Thanks.

**Comment by CBurton90** [comment]
@mnaguit it may be due to the EQR's not being in assets/recorders.csv

**Comment by CBurton90** [comment]
ignore me they are there!

**Comment by CBurton90** [comment]
Maybe there is a check on the time gap between firmware updates and because it is rather large it doesn't like it. Usual firmware updates have a small gap of <1 hour. @ozym may know?

**Comment by ozym** [comment]
I think it's complaining because there isn't a firmware change.

**Comment by ozym** [comment]
Just needs the previous line to be extended to 9999.

**Comment by mnaguit** [comment]
Yehey! It worked now. Travis is happy. Thanks guys. 👍 
Are you all good with using the same opening time for the station and all LCs?

**Review by CBurton90 — APPROVED** [review]

**Review by salichon — COMMENTED** [review]
elevation to be revisited iwhen relevant

**Comment by mnaguit** [comment]
Thanks @salichon . 
I got the elevation from the main ticket, here quoted as per @CBurton90 response:
> For the station coordinates i'm sure using the GRAS-20 lat/long should be fine, in the network repo I used 26m for elevation for LC20 so maybe this can be the station elevation as well?

**Comment by mnaguit** [comment]
Hi @ozym . Just a follow up for review on this PR. Many thanks!

**Review by ozym — APPROVED** [review]
Looks okay

**Comment by mnaguit** [comment]
Thanks @ozym 👍 
@salichon, are you happy with this PR? Thanks.

**Review by salichon — APPROVED** [review]

**Pull request merged**
