### PR TITLE
Radome check

### PR DESCRIPTION
**Pull request by elidana**
Hi @ozym and @staylorofford , 
I've done a check on radome undeploy time. The timestamp is based on antenna install closing time and when not sure I had a check on data, IGS sitelogs and pictures on the GeoNet Dropbox.
Hopefully I got it right.
When merged, issue https://github.com/GeoNet/tickets/issues/1519 can be closed.
Thanks!

### CODE REVIEW

**Comment by ozym** [comment]
@elidana it may pay to rebase this down to one commit

**Comment by elidana** [comment]
you mean to this one? `3f981ec92bfe8ea495fe0f27e7356afcb2d3aa83`

**Comment by ozym** [comment]
usually if it's a cleanish repo ... "git pull --rebase upstream master" should work (or whatever the remote and branch is that you're trying to merge into).

**Comment by elidana** [comment]
not sure I got it right . If not I'll create a new pr and close this one

**Pull request merged**
