### PR TITLE
WMGZ SM Sensor Swap

### PR DESCRIPTION
**Pull request by Thomas-Benson**
- Removing FBA-ES-T Episensor (2267) from WMGZ LC 20
- Replacing with Fortis (TF1129) at same location
- Updating stream to continuous for sensor lifetime - as far as I can tell this stream has never been triggered since it is treated as a traditional seismic site with sensor + datalogger rather than a stand-alone recorder

### CODE REVIEW

**Review by mnaguit — COMMENTED** [review]
Hi @Thomas-Benson , can you please double check the following:
- Fortis serial number (TF1118 in the main ticket)
- for streams, triggered to continuous switch end/start date to start around February 2020?
- Did I miss something or there was a datalogger swap too aside from the sensor @gva6500? Delta has `Q330S/6` for this station, but recent data capture in the main ticket has `Centaur`.

**Comment by Thomas-Benson** [comment]
- Added updates for datalogger upgrade
 - Fixed Fortis serial number
 - As for the state of the streams, I had to triple check the data, but this station seems to be a bit of a unicorn and has been streaming continuous 200 Hz data since it was installed:
```
4 Trace(s) in Stream:
NZ.WMGZ.20.BNZ | 2016-09-04T06:24:15.200007Z - 2016-09-12T21:23:55.180007Z | 50.0 Hz, 37259000 samples
NZ.WMGZ.20.BNZ | 2016-09-12T21:24:36.200006Z - 2016-10-01T00:00:00.000006Z | 50.0 Hz, 78226191 samples
NZ.WMGZ.20.HNZ | 2016-09-04T06:24:15.915007Z - 2016-09-12T21:23:55.910007Z | 200.0 Hz, 149036000 samples
NZ.WMGZ.20.HNZ | 2016-09-12T21:24:36.915006Z - 2016-10-01T00:00:00.000006Z | 200.0 Hz, 312904618 samples
```

image

**Comment by gva6500** [comment]
> Hi @Thomas-Benson , can you please double check the following:
> 
> - Fortis serial number (TF1118 in the main ticket)
> 
> - for streams, triggered to continuous switch end/start date around February 2020?
> 
> - Did I miss something or there was a datalogger swap too aside from the sensor @gva6500? Delta has `Q330S/6` for this station, but recent data capture in the main ticket has `Centaur`.

Indeed, the site has been a bit of a headache, it was initially thought to be a datalogger fault so it was swapped at a previous visit, turned out to be the cable. So that datalogger swap must have slipped through the cracks 🫣

**Review by gva6500 — APPROVED** [review]

**Review by mnaguit — APPROVED** [review]
Thank you @Thomas-Benson & @gva6500 👍

**Pull request merged**
