### PR TITLE
MXZ recorder swap

### PR DESCRIPTION
**Pull request by mnaguit**
Swap Basalt with Obsidian

### CODE REVIEW

**Comment by salichon** [comment]
Refer to https://github.com/GeoNet/delta/pull/534

Merge is on hold till  further information about the issue

Cheers
Jerome

**Comment by ozym** [comment]
Serial number isn't a number. Unfortunately it's a string and string sorting rules apply, i.e. 1000 < 800

**Comment by mnaguit** [comment]
Thanks @ozym . Any suggestions on what "number" to use for this case (MXZ) and MWZ?

**Comment by mnaguit** [comment]
Hi @ozym . 
@salichon was able to solve it, by placing the Obsidian entry on the first line. Thanks.
@salichon , @samgeonet , @jristau & @brianf3rris can you please do another round of review for this.

**Comment by salichon** [comment]
Hi @mnaguit just put the 
description of the 4 digit datatlogger before the 3 digits  ones.

**Comment by salichon** [comment]
Hello @mnaguit  all right  (got my brain working now) ... 
@samgeonet therefore we have to inquire and correct the orientation in the past BASALT to FIX:
i.e:  
> Kinemetrics,FBA-EST-BASALT,BASALT,1764,MXZ,20,0,0,0,2015-12-09T01:01:01Z,2019-05-29T04:20:00Z

so 
 - we can approve this PR and make another one once we d deem the period of old orientation (OBSIDIAN OK)
or
-  we add a commit  with the above and corrected line if we assume this is the period of misorientation :)) 

Cheers !

**Comment by mnaguit** [comment]
Hi @samgeonet @salichon @jristau @brianf3rris 
Can you kindly do another round or review for this? Changes in azimuth for Basalt from 0 to 20. Thanks.

**Pull request merged**
