### PR TITLE
WTMC LC 21

### PR DESCRIPTION
**Pull request by mnaguit**
update as of Oct 20, 2020:
For the latest install associated with the flapping effect investigation, location code for WTMC is changed to 22 instead of 21.
This PR is updated to open LC 22 for Basalt SN 561.
  
----
open LC 21 with Basalt SN 561 (changed as above-mentioned)

### CODE REVIEW

**Comment by mnaguit** [comment]
Note: I'll update this PR once I receive the final details for coordinates, elevation and azimuth from @CBurton90 .

**Comment by mnaguit** [comment]
Coordinates and elevation have been updated, as per the info provided by @CBurton90 in the ticket.

**Comment by mnaguit** [comment]
Hi. Follow up on this PR. Kindly review. This is one of the two stations for the flapping effect investigation.
Thanks.
@CBurton90 @salichon @ozym

**Review by CBurton90 — CHANGES_REQUESTED** [review]
Very confused as there already is a site of location 21 in sites.csv opening in 2016 and closing in 2017. Have we occupied the same location? Or should the location code have been 22 from the start 😭 ?

**Comment by mnaguit** [comment]
Sorry, I'm not well-versed with the history of this station. I have only followed the standard process to update the metadata, wrt the recent deployment. @CBurton90 

> Very confused as there already is a site of location 21 in sites.csv opening in 2016 and closing in 2017. Have we occupied the same location (according to the coords we have)? Or should the location code have been 22 from the start 😭 or has some old data back filled the archive?

**Comment by CBurton90** [comment]
> Sorry, I'm not well-versed with the history of this station. I have only followed the standard process to update the metadata, wrt the recent deployment. I don't think using LC 21 poses any issue. The metadata just needs to be updated. @CBurton90
> 
> > Very confused as there already is a site of location 21 in sites.csv opening in 2016 and closing in 2017. Have we occupied the same location (according to the coords we have)? Or should the location code have been 22 from the start 😭 or has some old data back filled the archive?

Yeah it's a bit confusing. Maybe one of the others can tell us why there is a 21 already existing in sites.csv? Temporary metadata error @ozym @salichon ?

**Review by salichon — COMMENTED** [review]
Hi @mnaguit if 21 was existing and instrument not at the same position
then do a 22 ? (with a change in configuration)

- [ ] Maybe have to check with RIM  for the position of the instrument.

To me this is a re-occupied site location thta should not even requires change in coord. (unless rounding)

**Comment by mnaguit** [comment]
Hi @salichon @CBurton90 @ozym 
I updated this PR for WTMC, to open LC 22 instead of LC 21. Kindly check the changes. Thanks!

**Comment by ozym** [comment]
Not sure  the 22 is needed?  The 21 was used for this same exercise (comparing recorders) ....

**Comment by mnaguit** [comment]
Hi @ozym 

I quote @CBurton90 message re: opening of LC 22:

> In regards to location code change to 22 here is where the flapping effect Basalt was installed. As it is over 1m from the Kaikoura Obsidian next to the original install I will change LC to 22.

**Review by ozym — APPROVED** [review]

**Review by CBurton90 — CHANGES_REQUESTED** [review]
The opening time in network/sites.csv should be `2020-10-06T23:34:00Z` not in 2016

**Comment by mnaguit** [comment]
Changes made. Kindly review again @CBurton90 @ozym 
Thanks!

**Review by CBurton90 — APPROVED** [review]
Thanks @mnaguit !!! sorry for the exhaustive changes 🤣

**Review by salichon — CHANGES_REQUESTED** [review]
hi  there @mnaguit @CBurton90 
If `22` is one meter away from `21` why is it 15 meters higher ;) ? 
I reckon for consistency  check elevation and set it to 198 meters  i guess

**Review by salichon — CHANGES_REQUESTED** [review]
also if we had a recorder at 21: 
`Kinemetrics | FBA-ES-T-OBSIDIAN | OBSIDIAN | 584 | WTMC | 21 | 62 | 0 | 0 | 2016-11-23T01:50:00Z | 2017-06-26T02:44:0`

where is the stream accordingly in `streams.csv` 

Am i missing something ?

**Comment by mnaguit** [comment]
Good point @salichon 
That is the elevation from a recent GPS receiver check, isn't it @CBurton90 ?
Also, note that LC 20 and 21 have the same metadata for coordinates & elevation.

**Comment by mnaguit** [comment]
> also if we had a recorder at 21:
> `Kinemetrics | FBA-ES-T-OBSIDIAN | OBSIDIAN | 584 | WTMC | 21 | 62 | 0 | 0 | 2016-11-23T01:50:00Z | 2017-06-26T02:44:0`
> 
> where is the stream accordingly in `streams.csv`
> 
> Am i missing something ?

That bit is mentioned in the original ticket. Was agreed to fix this new install first (LC22) for the flapping effect investigation (as this has been on a waiting mode for months now) and then deal with the LC21 later.

**Comment by salichon** [comment]
> Also, note that LC 20 and 21 have the same metadata for coordinates & elevation.
"Almost" the same normally coordinates :)
Does it pass the test on Delta ?

I don t ilke too much shoudl it be sligthly indicatiove of a coordinate chnage , specially when using 9 decimals for latitudes and longitudes!  (Which is the location of grain of sand - according xkcd ;) )

Since the flapping effect seems to require somehow appropriate coordinates. 
 Could we reflect this in Delta ? 
(Even a relative positioning with regards to loc20 for instance)

**Comment by salichon** [comment]
-> We can always push for a first Delta update about WTMC and amend it later upon discussion on @mnaguit  :)

**Review by salichon — APPROVED** [review]

**Comment by CBurton90** [comment]
> hi there @mnaguit @CBurton90
> If `22` is one meter away from `21` why is it 15 meters higher ;) ?
> I reckon for consistency check elevation and set it to 198 meters i guess

The internal gps receiver generally has an accuracy for the elevation of +/- 10m so this is why the value can change a lot at short distances @salichon

**Pull request merged**
