### PR TITLE
add centaur with lenartz mkIII

### PR DESCRIPTION
**Pull request by ozym**
follow up to #1131

### CODE REVIEW

**Review by CBurton90 — APPROVED** [review]
Looks good! Do we need to do the same for an EpiSensor with Centaur as well? I'm happy to try.

So why do we list the PAZ and FIR filters twice both here in auto.go and in their respective folder (sensors/filters) .yaml file? Are they for separate downstream response creation? (seiscomp3, StationXML etc)

**Comment by ozym** [comment]
The XML files are only used to build the auto.go file.

**Review by salichon — APPROVED** [review]

**Review by salichon — CHANGES_REQUESTED** [review]
Hello @ozym 
as for the previous related PR
I noticed that
 `Name: "GNS Dataloggers Connected to Short Period Sensors",`
 are using a "central" frequency at 15 Hz as opposed to the broadband set up at 1 Hz
 
 Hence:

>  				DataloggerList: []string{"Centaur CTR4-6S"},
> 				Type:           "CG",
> 				Label:          "EH",
> 				SampleRate:     100,
> 				Frequency:      1,

should be swapped to Frequency 15, shoudln't it ?

- As a consequence we may amend the previous PR 
  https://github.com/GeoNet/delta/pull/1131
  if this the case 
  
  cheers

**Comment by ozym** [comment]
Yes, good spotting. Won't be a technical issue, but will look nicer at 15hz.

**Comment by CBurton90** [comment]
@salichon @ozym I have made the change here:

https://github.com/GeoNet/delta/pull/1134

I suppose you can run the generate script after it has been merged and it will update this PR?

**Review by salichon — APPROVED** [review]
:+1

**Review by salichon — APPROVED** [review]
this looks good :)

**Review by CBurton90 — APPROVED** [review]

**Review by salichon — APPROVED** [review]

**Comment by salichon** [comment]
Kia Ora @ozym 
Shall we merge this PR ?
 (and finish with the CTR4 combos update  .. for that round of changes ;) )

**Comment by ozym** [comment]
@salichon yup, we can re-open as needed.

**Comment by CBurton90** [comment]
@salichon @ozym just to state again I have no merge permissions here so you two will have to the powers that be 😉

**Pull request merged**
