### PR TITLE
Dart  900s  and 15s Metadata improvement for seiscomp xml   

### PR DESCRIPTION
**Pull request by salichon**
Provide a stage 1 sensor  in delta  - Gain =1 
allows for seiscompml metadata to be complete from fdsxmlstation
Solution clue given by Gempa : https://github.com/GeoNet/tickets/issues/15401#issuecomment-2035418971 

issue found: 
 - stationxml build doubles up the dart metadata content per channel 
 might relate to coexistence  "dart .yaml" and "dart xml snippet"

output: 
- once trimmed conversion fdsnxml ->  seiscompxml is occurring

### CODE REVIEW

**Comment by salichon** [comment]
- passed the local test.sh on delta 
- not over the above ^^   at :  `Delta configuration management / delta-apps / go-test / go-test (pull_request) `
coverage: 60.3% of statements

```
ok  	github.com/GeoNet/delta/tools/spectra	0.004s	coverage: 60.3% of statements
FAIL
Error: Process completed with exit code 1.
```

**Review by ozym — COMMENTED** [review]
don't make changes to the auto systems, this has been deprecated. It will be removed at some point.

**Comment by salichon** [comment]
- Ok thanks Mark  that means then - not doing `go generate` doesn't it   hence not creating some auto xml snippets?

**Comment by salichon** [comment]
superseded by  https://github.com/GeoNet/delta/pull/2018

**Pull request closed without merging**
