### PR TITLE
WEL HH13 Trilium centaur test is over - Removed from delta.

### PR DESCRIPTION
**Pull request by salichon**
Removing centaur and trillium  site 13 
Testing is over,

### CODE REVIEW

**Review by CBurton90 — APPROVED** [review]
Do we remove the entries or close them? Can we remove entries that have data stored in the the archive? (I am happy either way but I feel like the "delta" policy is to close rather than remove if real data is in the archive for LC 13). 

Although if you plan to deleted LC 13 data from the archive then the entries should be removed.

**Review by mnaguit — COMMENTED** [review]
Hi @salichon 
Thanks for working on this.
Like @CBurton90 , do we delete data from the archive for the test site?
If yes, then we can delete these metadata.
Will wait until that question is answered before approving this ticket, hope that's ok. 
Cheers.

**Comment by salichon** [comment]
yes,   delete data from the archive @mnaguit @CBurton90  as mentioned in
  https://github.com/GeoNet/tickets/issues/8408 and
   https://github.com/GeoNet/tickets/issues/10627

**Review by mnaguit — CHANGES_REQUESTED** [review]
Close firmware for Centaur 7989?

**Comment by salichon** [comment]
@mnaguit the Centaur is still alive and should  lay on a shelf before it gets out again.
So the firmware is let opened as the asset is still working. 
to me :)

**Comment by salichon** [comment]
yes,   delete data from the archive @mnaguit @CBurton90  as mentioned in
  https://github.com/GeoNet/tickets/issues/8408 and
   https://github.com/GeoNet/tickets/issues/10627

**Review by mnaguit — APPROVED** [review]

**Pull request merged**
