### PR TITLE
VUWB Building array sensor swap

### PR DESCRIPTION
**Pull request by Thomas-Benson**
- Replacing 12 CuspM-3b sensors at VUWB with EQR120 SM recorders
    - Replaced Cusp 11046 at LC 21 with EQR120 46701
    - Replaced Cusp 11047 at LC 22 with EQR120 46702
    - Replaced Cusp 11025 at LC 23 with EQR120 46703
    - Replaced Cusp 11026 at LC 24 with EQR120 46704
    - Replaced Cusp 11027 at LC 25 with EQR120 46705
    - Replaced Cusp 11028 at LC 26 with EQR120 46706
    - Replaced Cusp 11030 at LC 27 with EQR120 46707
    - Replaced Cusp 11032 at LC 28 with EQR120 46708
    - Replaced Cusp 11036 at LC 29 with EQR120 46709
    - Replaced Cusp 11045 at LC 2A with EQR120 46710
    - Replaced Cusp 11048 at LC 2B with EQR120 46711
    - Replaced Cusp 11049 at LC 2C with EQR120 46712

 - Using latest EQR120 firmware version 2.3.2
 - All new recorders have orientation of `23` degrees

### CODE REVIEW

**Review by CBurton90 — APPROVED** [review]

**Review by mnaguit — COMMENTED** [review]
Thank you @Thomas-Benson 👍 

Tagging @jygns here, more a few queries. A few checks here:

- the depth entries in CUSPM for each LC should be the same for the EQR120s? These depth I would think corresponds to the height(?) from basement to upper levels of the building?
- for LC 22, azimuth for CUSPM was 113. Was the azimuth for EQR120 updated to 23?
Thanks @jygns

**Comment by Thomas-Benson** [comment]
Thanks @mnaguit, I missed that elevation was being tracked in `install/recorders.csv` instead of `network/sites.csv` for this building array, I can update the PR as needed.

**Comment by Thomas-Benson** [comment]
`install/recorders.csv` updated with depths for new recorders

**Comment by jygns** [comment]
Hi Muriel & Thomas
- nothing has changed with regards to the elevation above sea level (these will be negative numbers because they go upwards) and the height above sea level will be the same
- LC 22 azimuth has changed as with the new system I can change them to be all the same

**Review by mnaguit — APPROVED** [review]
Thanks @jygns & @Thomas-Benson 👍 👍

**Review by CBurton90 — APPROVED** [review]

**Pull request merged**
