### PR TITLE
add citations code and add pages column

### PR DESCRIPTION
**Pull request by ozym**
This PR adds the code to read and write citation files.

I've added a "Pages" column mainly as it appears this is a source of an extra comma in the Volume which would then require quoting. To avoid this any page information will naturally flow with a comma following the Volume details.

### CODE REVIEW

**Comment by ozym** [comment]
I have also added another citation related to the classes file.

**Review by salichon — APPROVED** [review]
Wow .. Great!

**Review by mnaguit — DISMISSED** [review]

**Comment by ozym** [comment]
@salichon @mnaguit sorry, had to resolve a conflict. Can you add your ticks again.

**Review by mnaguit — APPROVED** [review]

**Comment by ozym** [comment]
@mnaguit well that was a bit embarrassing, the code needed to be formatted correctly after the conflict was  fixed, Another tick please?

**Comment by mnaguit** [comment]
> @mnaguit well that was a bit embarrassing, the code needed to be formatted correctly after the conflict was fixed, Another tick please?

Sure @ozym . No worries at all.
Thanks to you these items are now moving forward 👍

**Review by mnaguit — APPROVED** [review]

**Review by salichon — COMMENTED** [review]
ticked again  -  sweet

**Pull request merged**
