### PR TITLE
add titan to resp yaml files

### PR DESCRIPTION
**Pull request by ozym**
These are the base text configuration details for the Titan (sensor) and TitanSMA (datalogger) responses.

The instrument provides an internal copy of the response which can be used as a reference. I've trimmed the FIR filters down ... (the time is related to when the request was made, not to when the data was available).

The files are:

* `sensors/nanometrics.yaml` -- holds sensor details, e.g. model types and PAZ responses
* `filters/nanometrics.yaml` -- holds filter information (e.g. FIR) specific to nanometrics dataloggers
* `dataloggers/nanometrics.yaml` -- holds datalogger information including filter stacks
* `configurations/strongmotion.yaml` -- ties the sensors and dataloggers together.

Once this is merged the next step will be the automatically generated code, then finally the response building code changes, if any are needed.

The only slight change in these files is adding an inputsample rate to the FIR filter stages to make the checking easier (not used in the calculations, but can be used to check outputs).

```
#        << Nanometrics RESP Writer (titanSMA v4.3.28)>>
#
#        ======== CHANNEL RESPONSE DATA ========
B050F03     Station:                                WEL
B050F16     Network:                                NZ
B052F03     Location:                               20
B052F04     Channel:                                HNZ
B052F22     Start date:                             2020,149,09:17:28.1
B052F23     End date:                               No Ending Time
#        =======================================
#        +               +--------------------------------------------+                +
#        +               |   Response (Poles & Zeros),  WEL ch HNZ    |                +
#        +               +--------------------------------------------+                +
#
B053F03     Transfer function type:                 A [Laplace Transform (Rad/sec)]
B053F04     Stage sequence number:                  1
B053F05     Response in units lookup:               M/S**2 - Acceleration in Meters Per Second Per Second
B053F06     Response out units lookup:              V - Volts
B053F07     A0 normalization factor:                1.007725E+18
B053F08     Normalization frequency:                1.000000E+00
B053F09     Number of zeroes:                       1
B053F14     Number of poles:                        6
#            Complex zeroes:
#             i  real          imag          real_error    imag_error
B053F10-13    0 -5.150000E+02  0.000000E+00  0.000000E+00  0.000000E+00
#            Complex poles:
#             i  real          imag          real_error    imag_error
B053F15-18    0 -9.770000E+02  3.280000E+02  0.000000E+00  0.000000E+00
B053F15-18    1 -9.770000E+02 -3.280000E+02  0.000000E+00  0.000000E+00
B053F15-18    2 -1.486000E+03  2.512000E+03  0.000000E+00  0.000000E+00
B053F15-18    3 -1.486000E+03 -2.512000E+03  0.000000E+00  0.000000E+00
B053F15-18    4 -5.736000E+03  4.946000E+03  0.000000E+00  0.000000E+00
B053F15-18    5 -5.736000E+03 -4.946000E+03  0.000000E+00  0.000000E+00
#        +               +--------------------------------------------+                +
#        +               |         Channel Gain,  WEL ch HNZ          |                +
#        +               +--------------------------------------------+                +
#
B058F03     Stage sequence number:                  1
B058F04     Gain:                                   5.100000E-01
B058F05     Frequency of gain:                      1.000000E+00 HZ
B058F06     Number of calibrations:                 0
#        +               +--------------------------------------------+                +
#        +               |    Response (Coefficients),  WEL ch HNZ    |                +
#        +               +--------------------------------------------+                +
#
B054F03     Transfer function type:                 D
B054F04     Stage sequence number:                  2
B054F05     Response in units lookup:               V - Volts
B054F06     Response out units lookup:              COUNTS - Digital Counts
B054F07     Number of numerators:                   1
B054F10     Number of denominators:                 0
#            Numerator coefficients:
#             i, coefficient,  error
B054F08-09    0  1.000000E+00  0.000000E+00
#        +               +--------------------------------------------+                +
#        +               |          Decimation,  WEL ch HNZ           |                +
#        +               +--------------------------------------------+                +
#
B057F03     Stage sequence number:                  2
B057F04     Input sample rate:                      3.000000E+04
B057F05     Decimation factor:                      1
B057F06     Decimation offset:                      0
B057F07     Estimated delay (seconds):              0.000000E+00
B057F08     Correction applied (seconds):           0.000000E+00
#        +               +--------------------------------------------+                +
#        +               |         Channel Gain,  WEL ch HNZ          |                +
#        +               +--------------------------------------------+                +
#
B058F03     Stage sequence number:                  2
B058F04     Gain:                                   4.000000E+05
B058F05     Frequency of gain:                      1.000000E+00 HZ
B058F06     Number of calibrations:                 0
#        +               +--------------------------------------------+                +
#        +               |    Response (Coefficients),  WEL ch HNZ    |                +
#        +               +--------------------------------------------+                +
#
B054F03     Transfer function type:                 D
B054F04     Stage sequence number:                  3
B054F05     Response in units lookup:               COUNTS - Digital Counts
B054F06     Response out units lookup:              COUNTS - Digital Counts
B054F07     Number of numerators:                   173
B054F10     Number of denominators:                 0
#            Numerator coefficients:
#             i, coefficient,  error
B054F08-09    0 -4.362506E-10  0.000000E+00
B054F08-09    1 -1.806376E-09  0.000000E+00
%< ------------------ snip -------------------------------------- >%
B054F08-09  171 -1.806376E-09  0.000000E+00
B054F08-09  172 -4.362506E-10  0.000000E+00
#        +               +--------------------------------------------+                +
#        +               |          Decimation,  WEL ch HNZ           |                +
#        +               +--------------------------------------------+                +
#
B057F03     Stage sequence number:                  3
B057F04     Input sample rate:                      3.000000E+04
B057F05     Decimation factor:                      15
B057F06     Decimation offset:                      0
B057F07     Estimated delay (seconds):              2.866667E-03
B057F08     Correction applied (seconds):           2.866667E-03
#        +               +--------------------------------------------+                +
#        +               |         Channel Gain,  WEL ch HNZ          |                +
#        +               +--------------------------------------------+                +
#
B058F03     Stage sequence number:                  3
B058F04     Gain:                                   1.000000E+00
B058F05     Frequency of gain:                      1.000000E+00 HZ
B058F06     Number of calibrations:                 0
#        +               +--------------------------------------------+                +
#        +               |    Response (Coefficients),  WEL ch HNZ    |                +
#        +               +--------------------------------------------+                +
#
B054F03     Transfer function type:                 D
B054F04     Stage sequence number:                  4
B054F05     Response in units lookup:               COUNTS - Digital Counts
B054F06     Response out units lookup:              COUNTS - Digital Counts
B054F07     Number of numerators:                   95
B054F10     Number of denominators:                 0
#            Numerator coefficients:
#             i, coefficient,  error
B054F08-09    0  6.153430E-09  0.000000E+00
B054F08-09    1  3.530519E-08  0.000000E+00
%< ------------------ snip -------------------------------------- >%
B054F08-09   93  3.530519E-08  0.000000E+00
B054F08-09   94  6.153430E-09  0.000000E+00
#        +               +--------------------------------------------+                +
#        +               |          Decimation,  WEL ch HNZ           |                +
#        +               +--------------------------------------------+                +
#
B057F03     Stage sequence number:                  4
B057F04     Input sample rate:                      2.000000E+03
B057F05     Decimation factor:                      5
B057F06     Decimation offset:                      0
B057F07     Estimated delay (seconds):              2.350000E-02
B057F08     Correction applied (seconds):           2.350000E-02
#        +               +--------------------------------------------+                +
#        +               |         Channel Gain,  WEL ch HNZ          |                +
#        +               +--------------------------------------------+                +
#
B058F03     Stage sequence number:                  4
B058F04     Gain:                                   1.000000E+00
B058F05     Frequency of gain:                      1.000000E+00 HZ
B058F06     Number of calibrations:                 0
#        +               +--------------------------------------------+                +
#        +               |    Response (Coefficients),  WEL ch HNZ    |                +
#        +               +--------------------------------------------+                +
#
B054F03     Transfer function type:                 D
B054F04     Stage sequence number:                  5
B054F05     Response in units lookup:               COUNTS - Digital Counts
B054F06     Response out units lookup:              COUNTS - Digital Counts
B054F07     Number of numerators:                   223
B054F10     Number of denominators:                 0
#            Numerator coefficients:
#             i, coefficient,  error
B054F08-09    0 -2.487704E-10  0.000000E+00
B054F08-09    1  4.737440E-09  0.000000E+00
%< ------------------ snip -------------------------------------- >%
B054F08-09  221  4.737440E-09  0.000000E+00
B054F08-09  222 -2.487704E-10  0.000000E+00
#        +               +--------------------------------------------+                +
#        +               |          Decimation,  WEL ch HNZ           |                +
#        +               +--------------------------------------------+                +
#
B057F03     Stage sequence number:                  5
B057F04     Input sample rate:                      4.000000E+02
B057F05     Decimation factor:                      2
B057F06     Decimation offset:                      0
B057F07     Estimated delay (seconds):              2.775000E-01
B057F08     Correction applied (seconds):           2.775000E-01
#        +               +--------------------------------------------+                +
#        +               |         Channel Gain,  WEL ch HNZ          |                +
#        +               +--------------------------------------------+                +
#
B058F03     Stage sequence number:                  5
B058F04     Gain:                                   1.000000E+00
B058F05     Frequency of gain:                      1.000000E+00 HZ
B058F06     Number of calibrations:                 0
#        +               +--------------------------------------------+                +
#        +               |      Channel Sensitivity,  WEL ch HNZ      |                +
#        +               +--------------------------------------------+                +
#
B058F03     Stage sequence number:                  0
B058F04     Sensitivity:                            2.040000E+05
B058F05     Frequency of sensitivity:               1.000000E+00 HZ
B058F06     Number of calibrations:                 0
```

### CODE REVIEW

**Comment by salichon** [comment]
Hello @ozym i  reckon it d be ideal to go through this during the DMC meeting on thursday maybe ? 
so that it s shown to the DMC as a whole

**Comment by mnaguit** [comment]
Hi. I have compared the first few lines with the response file from IRIS for 4G (https://ds.iris.edu/NRL/sensors/nanometrics/nanometrics_titan_sensors.htm), corresponding to poles & zeros, channel gain and response coefficients. They are the same. I think that's how far I can review this. If more checking is required, I'll be happy to do so.

**Comment by salichon** [comment]
Hello @ozym i m trying to reproduce/build the instrument response based upon the 
  https://smp.gempa.de/ website  based on import from the http://ds.iris.edu/NRL/  
and come with a few questions related to the setup of the TITAN SMA (as required in this instrument response builder) in order to document it if relevant. 

1. Datalogger `Titan SMA`
- `Select whether the DC removal filter is on (corner at 1 mHz)` -->  ON/OFF  ?
- `Select final filter phase` Linear phase / Minimum phase ? 
 what are the purpose of these parameter and how are they in our setup  ?
2. Sensor  `Titan accelerometer`
Sensibility 4G (straightforward set up)

I got  as an output 
         - Datalogger: `NRL/Nanometrics/CENTAUR.1.200.OFF.LP`
         - Sensor `NRL/Nanometrics/Titan.DC_430.20V.4G`
         - Gain `204000 COUNTS / <Unit>`
         - Gain frequency `1 Hz`
         - Gain unit `M/S**2`

so the datalogger is a  CENTAUR or equivallent  and the sensor is Titan.  
is there anything Oddd

**Comment by ozym** [comment]
@salichon The reason is the instrument uses Steim-1

**Comment by ozym** [comment]
@salichon there should be no implications except if there's heavy reprocessing of data (resampling / repacking etc.)

**Comment by salichon** [comment]
Titan Compression format "slight difference" Vs our current NZ  data
indeed should be right :) 
 AU MILA used in our systems is having a Steim1 compression

**Comment by ozym** [comment]
@salichon the order is important as it maps the channel number with the sensor pin, although in this case its probably not an issue as all pins have the same response.

The default install of a titan is as an urban / regional stand alone site, where the components are Z12, however when installed at a national network site it uses ZNE (as it is expected to be aligned). There's a column in the streams.csv file with label 'Axial' which is a mechanism to flip these about as needed. (the titan at WEL will mostly be in the smaller group of installs to start with, the rest will use Z12).

**Pull request merged**
