### PR TITLE
Streams 20,21,22,2G 1Hz LN Removed - Legacy - Data deletion process

### PR DESCRIPTION
**Pull request by salichon**
Data - Metadata archive management.

### CODE REVIEW

**Comment by salichon** [comment]
will require specific attention to detail around the few  building array streams involved - prior to merging and AWs actions :)

**Review by mnaguit — COMMENTED** [review]
Wait until John provides further info for CPLB? 
https://github.com/GeoNet/tickets/issues/10413

@salichon

**Comment by salichon** [comment]
@mnaguit We ait indeed until closer verifications about the odd streams 1Hz LN 
 that could be related to specific instrumentation and legacy

**Comment by salichon** [comment]
Nothing supports to keep the LN 1Hz in any of the change to me 
good for reviewing

**Comment by salichon** [comment]
Kia Ora @mnaguit 
would you bless this PR  again  ta!

**Review by mnaguit — APPROVED** [review]
Approving this now. Thanks @salichon 
One quick question: have we already "deleted" 1hz data from all these sites?

**Comment by salichon** [comment]
@mnaguit not yet - i ll aim at having no delay between applying the delta update and the archive cleaning process.
ideally within a day - so getting alll the thing ready before pulling the trigger :)

**Comment by mnaguit** [comment]
Okidoki @salichon 
Great work! 👍 
Looking forward to do archive cleaning with you, esp if it's not PITA 😆

**Comment by salichon** [comment]
@mnaguit i will proceed

**Pull request merged**
