### PR TITLE
EPAZ datalogger swap

### PR DESCRIPTION
**Pull request by mnaguit**
- from Q330/3 SN2537 to Centaur SN9501
- for LC 10 (EH-12Z)
- Centaur firmware v4.5.20

### CODE REVIEW

**Review by salichon — APPROVED** [review]
ouioui

**Review by moorematthew — APPROVED** [review]
Wonderful!

**Comment by mnaguit** [comment]
Hey gentlemen, this one needs another 👍 , as I have resolved the conflict with HBAZ (PRs issued almost at the same time). Any quick ✔️ is appreciated!
@moorematthew @salichon

**Review by moorematthew — APPROVED** [review]
Still looking great :)

**Pull request merged**
