### PR TITLE
HAVS recorder swap

### PR DESCRIPTION
**Pull request by mnaguit**
from Basalt 614 to Basalt 2419
from axial to non axial streams (reverted to axial)
Note: only 200 hz for this PR (50 hz for this station is closed in another PR)

### CODE REVIEW

**Comment by mnaguit** [comment]
Hi @ozym 
I think @samgeonet can provide an answer to your question.
I only follow the data that is available after an equipment is changed. I'll revert the streams to its original configuration once the instrument is fixed.

FYI @salichon

**Comment by samgeonet** [comment]
I'm guessing misconfiguration. I will correct on device

**Comment by mnaguit** [comment]
I revert the streams to axial. The opening time used refers to the time the recorder was swapped. Would that be alright?

FYI @samgeonet @ozym @salichon

**Comment by mnaguit** [comment]
Hi @ozym & @samgeonet 
Are you happy with the changes in this PR? Thanks!

**Comment by mnaguit** [comment]
Waiting for your approval Sir @samgeonet

**Pull request merged**
