### PR TITLE
CKHZ replacement

### PR DESCRIPTION
**Pull request by mnaguit**
instrument replacement

### CODE REVIEW

**Comment by salichon** [comment]
@peanutty @jristau 
Hello, can you review the change so that his one is updated if  all good  :)
Thanks !
Jerome

**Comment by mnaguit** [comment]
waiting for John's review before I merge it =) @jristau

**Comment by salichon** [comment]
@jristau... sorry and another one :)))

**Comment by mnaguit** [comment]
@jristau Waiting for your review Sir John before I can merge this pull request. A gentle reminder. Super thanks. =)

**Comment by mnaguit** [comment]
Many thanks John 👍  @jristau

**Pull request merged**
