### PR TITLE
MPSS recorder swap

### PR DESCRIPTION
**Pull request by mnaguit**
from CUSP3D 42009 to EQR120 46505
Firmware m001.03.08

### CODE REVIEW

**Review by salichon — APPROVED** [review]
thanks @mnaguit 
Interesting SM  site pretty quiet - BEFORE the school starts and then ....
(quiet time  :) UTC between  04:00am  and 20:00)

**Comment by mnaguit** [comment]
Hi @ozym 
Special request to review this PR, as @CBurton90 is currently in the field for today & tom.
Thanks in advance!

**Review by ozym — APPROVED** [review]

**Comment by mnaguit** [comment]
Many thanks @ozym (and @salichon). Much appreciated! 👍

**Comment by bglendinning** [comment]
> thanks @mnaguit
> Interesting SM site pretty quiet - BEFORE the school starts and then ....
> (quiet time :) UTC between 04:00am and 20:00)

Hi @salichon I saw this comment pop up and thought I'd give some insight, They are demolishing a few buildings right next to this one with a big excavator, The ground was shaking when i was there, so this would be why haha.  This one is also going to be demolished in the not too distant future, hopefully they give us notice to get our gear out first or you'll see even more noise

**Pull request merged**
