### PR TITLE
WTAZ borehole orientation update

### PR DESCRIPTION
**Pull request by Thomas-Benson**
Updating orientation of borehole sensor at LC 13 to 138

### CODE REVIEW

**Review by CBurton90 — DISMISSED** [review]

**Comment by CBurton90** [comment]
@Thomas-Benson @mnaguit Will two entries pass the CI/CD tests for sensors.csv? How do we track historical orientations? Just came to mind that the old azimuth might be forever lost.

**Comment by Thomas-Benson** [comment]
Two entries should pass as long as the times don't overlap. I should've done it like that in the first place, will fix shortly.

**Review by CBurton90 — APPROVED** [review]

**Comment by CBurton90** [comment]
Thanks @Thomas-Benson

**Comment by mnaguit** [comment]
Thanks @CBurton90 @Thomas-Benson 
I got to check the metadata history for WTAZ (due to discussion to track orientations). Orientation updates here, with the 2 entries, look good to me. 

Just got curious that `LC 13` in `sites.csv` opened in `2022-04-12T03:28:00Z`, but the all other metadata started in `2023-04-12T03:28:00Z`. This might be a good PR to update that too, as needed. 😄

**Comment by Thomas-Benson** [comment]
Nice catch @mnaguit , LC 13 should indeed have an opening time of 2023-04-12 (https://github.com/GeoNet/tickets/issues/12135#issuecomment-1537584015), will update.

**Review by CBurton90 — APPROVED** [review]

**Review by mnaguit — APPROVED** [review]
thanks @Thomas-Benson 👍

**Pull request merged**
