### PR TITLE
CPIT TG Sensor+Datalogger change

### PR DESCRIPTION
**Pull request by salichon**
Castelpont Tsunami gauge and datalogger change

### CODE REVIEW

**Review by megankortink — CHANGES_REQUESTED** [review]
Thanks Jerome! Few things, 
- shouldn't the closing time on the Q330 be 2021-07-25 etc in the install/dataloggers file not 2021-11-02?
- also I'm wondering if the closing time was actually 2021-07-26T0800 UTC from
CPIT_close
and

```
t1 = UTCDateTime("2021-07-26T00:00:00.000")
t2 = UTCDateTime("2021-07-26T23:00:00.000")
```

CPIT

**Comment by megankortink** [comment]
Sorry I had been meaning to do this tomorrow, thanks for beating me to it! :)

**Review by CBurton90 — APPROVED** [review]

**Comment by salichon** [comment]
@megankortink  hello 
Closing time for datalogger was corrected i reckon. and you re right i 2021  is not a leap year, data are finishing a bit before 0830 i can 08:15    .. thanks! 
Will push a new one soon :)

**Review by megankortink — APPROVED** [review]
LGTM! Thanks Jerome!

**Pull request merged**
