### PR TITLE
TEST Obsidian 8X  strong response on FOZ - NOT to be merged - WIP

### PR DESCRIPTION
**Pull request by salichon**
Follow up PR  with  https://github.com/GeoNet/delta/pull/1232
 **Testing response creation for 200 Hz Strong Only for FOZ** 
 Mount is `datalogger 8X + FBA-ES-T`
 
 For a Completed Obs8X 200Hz response: 
  - The `obsidian 8x  datalogger` previous PR #1232   provides only  a filter for 200Hz (oobsidian 8X) 
 - Added and changed the configuration for having a `strong motion combo for 200 Hz obsidian8X`  in strong motion

For the Testing a full obsid8X response:
- Isolated the FOZ  original kinemetrics  combo (obsidian 4X+FBA) 
- Modifying the combo to mount and output a  test response for   `datalogger 8X + FBA-ES-T` for FOZ ( _from 2017 onward_.)
 
---------------------------------

 Is it legit for testing and complementary from the #1232 ? 

--------

NB: of course this PR  will fail the auto tests (since i ditched all but one stations ... )
 --> For local testing only and will be fed back to the main PR or another more definitive one :)

### CODE REVIEW

**Comment by salichon** [comment]
- the final  station xml  output of FOZ 200Hz overall sensivity is **6.84 e+6** (count to m/s**2) as opposed to the original  which is **1.71e+6**
-> as expected a ratio of ~ 4 (0.25)  betwen the mount sensitivities of the Obsidian 8X Vs the 4x  
 which  is looking good

**Comment by mnaguit** [comment]
> * the final  station xml  output of FOZ 200Hz overall sensivity is **6.84 e+6** (count to m/s**2) as opposed to the original  which is **1.71e+6**
>   -> as expected a ratio of ~ 4 (0.25)  betwen the mount sensitivities of the Obsidian 8X Vs the 4x
>   which  is looking good

Great to note the significant difference in sensitivities.  👍

**Comment by salichon** [comment]
@ozym @CBurton90 @mnaguit 
I added an example in the test "PR" FOZ strong motion 200Hz station xml  output (from stationxml delta tool)
the "original" 4x and the "tuned" 8X

**Comment by salichon** [comment]
will  test new branch when filters/gains are agreed and sorted

**Pull request closed without merging**
