### PR TITLE
TUZ Strong Sitecode change Legacy 20to21

### PR DESCRIPTION
**Pull request by salichon**
Added also HN 200HZ continuous dates

### CODE REVIEW

**Review by mnaguit — CHANGES_REQUESTED** [review]
A few other comments:

- transition of LC 20 to 21 ok, and aligned with `install/connections.csv` and `install/sensors.csv`
- is there a need for on the dot closing for LC 20? (e.g. closing should be 2015-10-26, as per data plot shown in the main ticket)

**Comment by salichon** [comment]
- Corrected for the stream overlap

**Comment by salichon** [comment]
- for the LOC 20  closing date i used the one provide from the `install/sensors.csv`  `2015-10-27T05:00:00Z` for  `TUZ 20` 
- the LN files are rogue files left over of bad configuration.maniputaltion namely:
`TUZ_2015_strong.lst:s3://geonet-archive/miniseed/2015/2015.300/TUZ.NZ/2015.300.TUZ.20-LNE.NZ.D
TUZ_2015_strong.lst:s3://geonet-archive/miniseed/2015/2015.300/TUZ.NZ/2015.300.TUZ.20-LNN.NZ.D
TUZ_2015_strong.lst:s3://geonet-archive/miniseed/2015/2015.300/TUZ.NZ/2015.300.TUZ.20-LNZ.NZ.D
TUZ_2015_strong.lst:s3://geonet-archive/miniseed/2015/2015.301/TUZ.NZ/2015.301.TUZ.20-LNE.NZ.D
TUZ_2015_strong.lst:s3://geonet-archive/miniseed/2015/2015.301/TUZ.NZ/2015.301.TUZ.20-LNN.NZ.D
TUZ_2015_strong.lst:s3://geonet-archive/miniseed/2015/2015.301/TUZ.NZ/2015.301.TUZ.20-LNZ.NZ.D`

they should be eradicated :) i reckon 

Probably  needs to re-verify that the change occurred actually at the date that was informed in delta  ...
 sigh sigh sigh :)

**Review by mnaguit — APPROVED** [review]
Thank you for double-checking @salichon 
👍

**Pull request merged**
