### PR TITLE
NZH Site 42 opening

### PR DESCRIPTION
**Pull request by EvanCGNS**
Opened NZH site 42 with timestamp `2024-06-25T21:37:00Z`, matching first message time in deployment sheet

 Made this change to `install/recorders.csv`, `firmware.csv`, `streams.csv`, `sites.csv`, and `gauges.csv`.

Updated the ending timestamps for NZH site 41 to `2024-06-24T18:00:00Z`

Closed old NZL BPR in `firmware.csv` to match timestamp in `install/recorders.csv`, as the NZH BPR used to be at NZL.

### CODE REVIEW

**Comment by EvanCGNS** [comment]
It looks like the tests didn't appreciate closing where 201002 used to be in firmware.csv. I'll remove it from this PR and make a separate one tomorrow.

**Comment by EvanCGNS** [comment]
Reverted my changes to firmware.csv, which has fixed the problem

**Review by JonoHanson — APPROVED** [review]
Approved - please double check there is no deployment data based on that start time, then good to go

**Comment by JonoHanson** [comment]
also, happy to see this merged, but i can't confirm the firmware changes

**Comment by EvanCGNS** [comment]
> Approved - please double check there is no deployment data based on that start time, then good to go

No messages from this time onwards until the normal-looking BPR N1 data. Merging request

**Pull request merged**
