### PR TITLE
NBRT Equipment Install of centaur and PTX1835

### PR DESCRIPTION
**Pull request by megankortink**
Hi, first one so please check especially the following:
- install sensors
- network/sites - have used External GPS Clock, also note coordinates Conrad supplied slightly different from NBLC (used Conrad's)
- network/stations - used same coordinates as above, the ones in the ticket

Have also kept elevation as '0' for now

### CODE REVIEW

**Review by mnaguit — COMMENTED** [review]
Many thanks @megankortink . Good job! 👍 

I'll just need to double check the elevation with @CBurton90 . 
Shall we incorporate that 23m elevation measured from the GPS antenna?

**Review by CBurton90 — CHANGES_REQUESTED** [review]
Thanks @megankortink . I think the dip should be `90` in `install/sensors` as the sensors are sitting vertically in the pipe rather than horizontally on the seabed (sorry forgot to mention). 

Also brendon and I have looked at the sensor coords on google earth and have found that 
```
 -43.5059694°, 172.7349917°
 ```
Is the actual sensors location in `install/sensors`. 0m is fine for now I would say as a lot of others have this depth/elevation. 

Station and sites looks fine, both NBLC and NBRT should be very close as both gps antennas are run into the same cabinet (which is the station coords in my eyes).

**Comment by megankortink** [comment]
@CBurton90 so would you like:
```
-43.5059694°, 172.7349917°
```
for network/sites and network/station?

**Comment by salichon** [comment]
@megankortink  it s a **TG new site**
May need review  too from Platform experts :)

**Comment by CBurton90** [comment]
> @CBurton90 so would you like:
> 
> ```
> -43.5059694°, 172.7349917°
> ```
> 
> for `network/sites` and `network/station`?
> 
> I've added `90` degrees to the azimuth field in the `install/sensors`

Just in `install/sensors` @megankortink . Cheers.

**Review by salichon — CHANGES_REQUESTED** [review]
It is missing one bit ;) 
hint ... between the datalogger and the sensor ...  (cf wiki graphs) 
As a test:
 over linux use  the ./test.sh script to  ..guide you ;)

**Comment by megankortink** [comment]
Changed coordinates for network/sites, looking into install/connections now. @salichon would Mark be the appropriate person to review?

**Comment by mnaguit** [comment]
Yeah @salichon . 
It means, even without the `connections.csv`, there is no Travis error?
For the station elevation, what is the norm with the rest of tsunami gauges? Apologies, i don't have much ideas on this bit.

**Comment by CBurton90** [comment]
Ok so the consensus is:

Sites (should be the actual location of the sensors)
Stations (the general location of the cabinet housing equipment)

So we will update the network/sites.csv of 40/41 to the google earth coords (actual sensor location)

aaaand network/stations.csv can be left as is, the elevation of the gps antennas (tsunami gauge Centaur and strong motion TitanSMA) is 23m/26m respectively. I'm not sure if it's appropriate for these elevations to be used as they are much higher than the actual station/cabinet (happy to hear thoughts).

**Comment by CBurton90** [comment]
> Yeah @salichon .
> It means, even without the `connections.csv`, there is no Travis error?
> For the station elevation, what is the norm with the rest of tsunami gauges? Apologies, i don't have much ideas on this bit.

@mnaguit generally they are 0m in stations.csv

**Comment by megankortink** [comment]
Should hopefully be all good now, have just added the install/connections file. Let me know what you think. Have also added @ozym to review as a new site

**Comment by ozym** [comment]
Couple of things, I understood the station location will be roughly where the sensors are (not so much the recorder as that has not relevance to the data). (I.e. if you lookup the station location it won't be in the water so may raise eyebrows).

Is it too late to make the name "New Brighton Pier" to distinguish it a little?

**Comment by salichon** [comment]
hi  there
i guess we are not using really the `role` for the tide/tsunami gauges
so indeed  replacing "New Brighton" by "New Brighton Pier" 
makes more sense and helps in identifying what is likyle plugged. yup

**Comment by megankortink** [comment]
@ozym and @salichon would we like 'New Brighton Pier' for all mentions? (install/connections.csv, network/stations.csv, and install/dataloggers.csv).

**Comment by mnaguit** [comment]
All good with me on the changes in name (e.g. add Pier) for all relevant csv files. And I agree with Conrad on coordinates set for sites and stations files.

**Comment by megankortink** [comment]
Added 'Pier' to the three files that mention the name.

**Comment by CBurton90** [comment]
> Couple of things, I understood the station location will be roughly where the sensors are (not so much the recorder as that has not relevance to the data). (I.e. if you lookup the station location it won't be in the water so may raise eyebrows).
> 
> Is it too late to make the name "New Brighton Pier" to distinguish it a little?

@ozym so station location (station.csv) and sites location (sites.csv) should both be where the sensors are i.e. the same coordinates?

**Review by salichon — APPROVED** [review]
ok thanks Megan!

**Review by CBurton90 — APPROVED** [review]
My only thought is the stations.csv coord should match the sites.csv coords and elevation dropped to zero so in stations.csv.
```
NBRT,TG,New Brighton Pier,-43.5059694,172.7349917,0,,WGS84,2021-05-14T02:07:00Z,9999-01-01T00:00:00`
```
And as the new coordinates were estimated from Google Earth the survey column in sites.csv may need to be `Topographic Map` so in sites.csv.
```
NBRT,40,-43.5059694,172.7349917,1,,WGS84,Topographic Map,2021-05-14T02:07:00Z,9999-01-01T00:00:00Z
NBRT,41,-43.5059694,172.7349917,1,,WGS84,Topographic Map,2021-05-14T02:07:00Z,9999-01-01T00:00:00Z
```

I assume that was what @ozym was suggesting. I guess this site is one of the longest cable runs from the sensors to the cabinet/digitiser so narrowing down the actual location of the site/station may be quite important instead of co-locating the station coordinates with the strong motion site at the cabinet.

**Comment by megankortink** [comment]
Followed Conrad's suggestions as above for the sites/staions files. @ozym hope this works for you.

**Comment by CBurton90** [comment]
@megankortink missing `Z` on stations.csv

**Review by CBurton90 — APPROVED** [review]
LGTM

**Review by mnaguit — APPROVED** [review]

**Pull request merged**
