### PR TITLE
Adding FW upgrades

### PR DESCRIPTION
**Pull request by meganmadley**
Adding PNUI - 6013R40113 - 2022-10-18T20:32:21

### CODE REVIEW

**Comment by aleks-spes** [comment]
WMAT - 6139R40184 - 2022-10-18T20:30:54

**Comment by aleks-spes** [comment]
VGWT - 5946R40014 - 2022-10-18T21:34:47

**Comment by meganmadley** [comment]
WAKA 6015R40027 - 2022-10-18T22:59:02

**Comment by meganmadley** [comment]
@aleks-spes LGTM!

**Review by aleks-spes — APPROVED** [review]
Looks good!

**Pull request merged**
