### PR TITLE
FEGZ new RCET station

### PR DESCRIPTION
**Pull request by mnaguit**
- for LC 10 (HH/LH-12Z) streams
- borehole with sensor TC120PH-2 (9203) 
- Centaur (9454) with firmware v4.5.20

Note: orientation to be updated later @CBurton90

### CODE REVIEW

**Review by salichon — CHANGES_REQUESTED** [review]
Kia Ora
for consistency in elwvation and altitude of site Vs the station 
157 meters against 410 seems  a big difference

**Comment by mnaguit** [comment]
> Kia Ora for consistency in elwvation and altitude of site Vs the station 157 meters against 410 seems a big difference

Sorry, my mistake there Sir @salichon 
Will modify that + the start date-time for LH streams

**Comment by mnaguit** [comment]
Elevated updated to 192m, as per @CBurton90 recent comment in the main ticket. LH-12Z start date/time also fixed.
This on is just waiting for the orientation, and it is ready to go.

**Comment by CBurton90** [comment]
@mnaguit `284` for orientation : )

**Review by CBurton90 — DISMISSED** [review]

**Comment by mnaguit** [comment]
All good with this one, just waiting for at least 👍 👍 , and ready to merge!
@salichon @CBurton90 @ozym

**Review by ozym — APPROVED** [review]

**Pull request merged**
