### PR TITLE
GNSS FW 6.14 Monday 10th Upgrades

### PR DESCRIPTION
**Pull request by meganmadley**
CMBL - 6107R40025 start time of new firmware 2022-10-09T20:41:22

### CODE REVIEW

**Comment by meganmadley** [comment]
Added ANAU - 6141R40102 start time of new firmware 2022-10-09T21:33:12

**Comment by meganmadley** [comment]
Added RGHD - 5944R40021 start time of new firmware 2022-10-09T22:38:04

**Comment by aleks-spes** [comment]
Added 2406 - 6016R40025 - start time for new firmware 2022-10-09T21:32:11
Added HANM - 5921R40168 - start time for new firmware 2022-10-09T22:28:09
Added 2406 - 6221R40081 - start time for new firmware 2022-10-09T23:25:14

**Comment by aleks-spes** [comment]
Hey @meganmadley! Could you please review my records?

**Review by aleks-spes — APPROVED** [review]
Looks good!

**Comment by meganmadley** [comment]
Yip, LGTM!

**Pull request merged**
